CMakeLists.txt, plugins/network/CMakeLists.txt
Building only client-side code currently requires _libzmq_ and _libarchive_ to be installed, which is unnecessary as the code does not use these libraries' facilities at all.  This PR removes these unnecessary libraries.
There are probably others, but this suffices to build the iRODS CMake targets needed for my third-party client development without requiring excess system libraries to be installed.  It remains undocumented what CMake targets are actually needed for various purposes (cf #3228), but for now I have been building with `make irods_client irods_plugin_dependencies irods_common tcp_client native_client`.
In general many of the CMakeLists have overly-conservative `target_link_libraries` that list lots of link libraries that are unused by the particular targets.  Part of the …
=> Remove unnecessary linker prerequisites

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/arithmetics.cpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/functions.cpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/include/restructs.hpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/parser.cpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/typing.cpp, scripts/irods/test/test_all_rules.py
This add a feature to the rule language that allows specifying the type of an expression to avoid the type checker from using the default type that may cause type errors.
=> [#3575] type ascription

plugins/network/ssl/libssl.cpp
_msg_buf, _error_buf, and _stream_bbuf are parameters of the function
and are not null-checked before dereferencing when printing to log or
when attempting to write to socket.
This change adds the needed null checks to accompany the zero-length
buffer checks such that the result returned by the function is the
same for either case.
The buffer lengths "should" never be non-zero when _msg_buf,
_error_buf, and _stream_bbuf are null, so the null pointer
dereferences "should" never happen. This adds an extra layer of
protection.
=> [#3679] Fix dereference of null pointer in ssl_send_rods_msg

lib/core/src/packStruct.cpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/functions.cpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/index.cpp, server/core/src/rodsServer.cpp, server/re/src/extractAvuMS.cpp
There are several places where the program can return early due to some kind of error. Make sure any allocated memory is freed up before returning.
=> [#3701] Fix missing frees on early returns

plugins/network/ssl/libssl.cpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/utils.cpp, server/api/src/rsCollCreate.cpp, server/core/src/dataObjOpr.cpp
In l3Mkdir:
Added early return in l3Mkdir if dataObjInfo is null.
In updateInEnv:
updateInEnv takes an Env pointer as argument, and the pointer can be
null. Since the entire function depends on env, ensure that it is
not null before proceeding with any operations.
In getDataObjInfoIncSpecColl:
This change adds a null check before dereferencing dataObjInfo or
checking specColl.
Also fixed constants going on the left in change with SHA:
eaab3c4549b954d2df701117d8a7b631449998fb
=> [#3679] Add null pointer checks in a few files

plugins/network/ssl/libssl.cpp
_msg_buf, _error_buf, and _stream_bbuf are parameters of the function and are not null-checked before dereferencing when printing to log or when attempting to write to socket.
This change adds the needed null checks to accompany the zero-length buffer checks such that the result returned by the function is the same for either case.
The buffer lengths "should" never be non-zero when _msg_buf, _error_buf, and _stream_bbuf are null, so the null pointer dereferences "should" never happen. This adds an extra layer of protection.
(cherry-picked from SHA: eaab3c4549b954d2df701117d8a7b631449998fb)
=> [#3679] Fix dereference of null pointer in ssl_send_rods_msg (#1)

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/arithmetics.cpp
When freeing the argument vector, need to make sure the args structures are not null before dereferencing to get the exprType. exprType should be non-null, since it is a pointer in the node structure which is dereferenced.
=> [#3679] Fix dereference of null pointers in execMicroService3

plugins/resources/load_balanced/libload_balanced.cpp, plugins/resources/mockarchive/libmockarchive.cpp, plugins/resources/nonblocking/libnonblocking.cpp, plugins/resources/random/librandom.cpp, plugins/resources/unixfilesystem/libunixfilesystem.cpp, server/core/src/irods_resource_plugin_impostor.cpp
This change removes usages of ASSERT_ERROR and ASSERT_PASS in order to reduce confusion and to appease static analyzers that do not assert the assertions. Required a little bit of refactoring to produce equivalent behavior.
Functions changed are resolving hierarchies for the different resource plugins, so each file change is very similar to the others.
=> [#3679] Reduce usage of ASSERT_ERROR/PASS

lib/core/src/packStruct.cpp, server/core/src/physPath.cpp
This fixes a few places where null parameters are being passed into
functions which do not accept null parameters for their arguments.
(cherry-picked from SHA: d8a66dc9b404bfa84dfdd2dfaef9d9362d1d725f)
=> [#3678] Fix null parameters going into non-null arguments

scripts/irods/test/test_iquest.py, server/api/src/rsGenQuery.cpp
Adds some tests for iquest in DATA_RESC_HIER which expose an issue
where the hier name is not being substituted correctly in the output.
If DATA_RESC_HIER is used in a GenQuery, the DATA_RESC_ID for the
hierarchy is used instead in the actual query and then replaced at the end
with DATA_RESC_HIER again. There is a bug where selecting DATA_RESC_HIER
as a column and using the DATA_RESC_HIER as a filter causes the replacement
of the ID at the end to fail. This change fixes this issue by not
allowing the inputs for the filter to override the saved position of
the column in the output.
=> [#3705] Fix iquest not returning DATA_RESC_HIER

plugins/auth/native/libnative.cpp
Even though it is not a valid code path, the static analyzer has detected some potential null pointer dereferences.
Note: This should be the last of the null pointer dereferences from scanbuild. Must have missed these in the last round.
=> [#3679] Fix null pointer dereferences in libnative.cpp

scripts/irods/test/test_iquest.py, server/api/src/rsGenQuery.cpp, server/core/include/irods_resource_manager.hpp, server/core/src/irods_resource_manager.cpp
DATA_RESC_HIER is no longer stored in the metadata table, so SQL cannot be used to query resource hierarchies directly. As a result, using DATA_RESC_HIER in the WHERE clause of a GenQuery can cause strange returns. Using DATA_RESC_HIER in the WHERE clause of a GenQuery will now return a
result consistent with the rules below:
- '=' with %: error
- '=' without %: direct match for leaf
- 'like' without %: direct match for leaf
- 'like' with %: consistent with 'like' for other columns
Add tests for expected behavior when using GenQuery with DATA_RESC_HIER. This includes adding a number of resources in a hierarchy to demonstrate results from the various queries.
Also replaced some raw asserts in the 3705 test with self.assertTrue.
---
=> [#3714] Fix GenQuery for resource hierarchies

plugins/resources/replication/librepl.cpp, server/api/src/rsRmColl.cpp
Fix the remaining dead stores reported by scanbuild.
---
For this change, I took the short path to quiet scanbuild. However, there is great potential for improvement in the code surrounding these changes, so I am open to doing some refactoring, if desired. In particular, the massive conditional in rsRmColl.cpp could be inverted so that the status = 0 could be removed, but I found it even harder to understand than in its original form.
=> [#3711] Remove remaining dead stores

scripts/irods/test/test_iquest.py, server/api/src/rsGenQuery.cpp
Wildcard-less likes (that is, direct matches) should be interpreted as direct matches for hierarchies instead of for leaves. This modifies the rules to be consistent with the following:
- '=' with %: error
- '=' without %: direct match
- 'like' without %: direct match (like '=')
- 'like' with %: consistent with 'like' for other columns
---
Passed Jenkins tests
=> [#3714] Tweak behavior of LIKE for DATA_RESC_HIER

msiExecCmd_bin/irodsServerMonPerf, scripts/irods/test/test_all_rules.py
Due to restructuring in 4.2, msiServerMonPerf refers to a dependency in a location where it does not reside.
---
Jenkins tests passed except for occasional failure described in #3706 (cen6-psql-resc-ssl)
I can move the test to a different file if desired. Current location seemed the most appropriate from what I was able to find.
=> [#3736] Fix msiServerMonPerf wrong dir reference

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/rules.cpp, server/re/src/reIn2p3SysRule.cpp
Fixed a malloc of 0 bytes (undefined behavior) and dereference of an uninitialized pointer.
---
Jenkins tests passed except for occasional failure noted in #3689 (ub16-oracle)
=> [#3769] Fix remaining scanbuild issues

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/rules.cpp, scripts/irods/test/test_federation.py
Remote rule execution will fail in versions >4.2.1 due to a segmentation fault in convertHashtableToMsParamArray. To prevent this, msParamArray is being generated for rei before calling the offending function in the event that it is made null.
Tests write to the server log using the remote execution microservice. First test writes to the local zone's log. Second test writes to the remote zone's log (configured in test_federation).
=> [#3722] Fix segfault in remote rule execution

iRODS/clients/icommands/src/ichksum.cpp, iRODS/lib/core/src/chksumUtil.cpp, tests/pydevtest/test_icommands_file_operations.py
ichksum can now be run with the '-M' option to run the command in admin mode. This allows admin users to ichksum files that they do not have permissions for.
---
All Jenkins tests passed except for ub16 (which was not part of the test suite for 4-1-stable up to this point).
=> [#3265] Add admin flag to ichksum

plugins/database/src/db_plugin.cpp
In the process of fixing issue #3787 , code blocks  which had been obviated by that change were commented out rather than deleted. This change is simply the removal of that redundant content, as well as of other commented-out code blocks from past changes.
=> [#3787] removed commented-out code related to this and previous deltas

scripts/irods/database_interface.py
```
Traceback (most recent call last):
File "/var/lib/irods/scripts/setup_irods.py", line 448, in <module>
sys.exit(main())
File "/var/lib/irods/scripts/setup_irods.py", line 436, in main
setup_server(irods_config, json_configuration_file=options.json_configuration_file)
File "/var/lib/irods/scripts/setup_irods.py", line 115, in setup_server
database_interface.setup_database_config(irods_config)
File "/var/lib/irods/scripts/irods/database_interface.py", line 95, in setup_database_config
for k in irods_config.server_config.setdefault('plugin_configuration', {}).setdefault('database', {}):
RuntimeError: dictionary changed size during iteration
```
=> database_interface.py: don't modify dict while iterating through it

CMakeLists.txt, cmake/development_library.cmake, lib/core/include/irods_generic_auth_object.hpp, lib/core/src/irods_auth_factory.cpp, lib/core/src/irods_generic_auth_object.cpp
Fall through in auth factory to resolve a string value to a library containing an arbitrary subclass of generic_auth_object. 
Utilized by an openid auth plugin here: https://github.com/irods-contrib/irods_auth_plugin_openid
=> Add functionality for generic auth object

lib/core/src/sockComm.cpp, plugins/resources/CMakeLists.txt, plugins/resources/replication/irods_create_write_replicator.cpp, plugins/resources/replication/irods_repl_rebalance.cpp, plugins/resources/replication/irods_repl_rebalance.hpp, plugins/resources/replication/irods_repl_retry.cpp, plugins/resources/replication/irods_repl_retry.hpp, plugins/resources/replication/librepl.cpp, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_resource_types.py
This change adds a configurable retry mechanism to the replication resource. The replication resources can be configured via 3 new settings in the context string of the resource. The retry applies when the replication from an iput or a replication rebalance fails. The default value for each setting is 1, which means a single retry after 1 second has passed.
Passed 4 test runs on Jenkins. Two of the runs hit #3689 for ub16-oracle. One run hit #3706 for topo-cen6-psql-resc-ssl.
=> [#3436] Add retry capability to replication resource

.gitignore, lib/core/src/rodsPath.cpp, scripts/irods/test/test_ireg.py, scripts/irods/test/test_log_levels.py, server/api/src/rsPhyPathReg.cpp, server/core/src/rodsServer.cpp
Resolves:
#3658 irods/irods ireg should trim trailing slash
In lib/core/src/rodsPath.cpp (around line# 268), a check is made for trailing slashes in the physical directory path, and they are removed if they're there. (This is the code path for dealing with "ireg -C ......").
In server/api/src/rsPhyPathReg.cpp (line# around 730), a check is made by the server for trailing slashes in the physical directory path, and they are removed if they're there before a /filename is appended to that string. This takes care of physical directory paths associated with resources in the catalog pre-dating this fix.
Test case:  test_ireg_double_slashes__issue_3658() in scripts/irods/test/test_ireg.py
Continuous Integration:  Build 713 - http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-wo …
=> Collection of bug fixes: [#3658] [#858] [#3865]

tests/pydevtest/configuration.py, tests/pydevtest/run_tests.py
Adapted from SHA ae7c06f2125bbeb71ed4e9a1a5d2a0b6ccc42032
--
=> [#3854] changes made to support mungefs

iRODS/lib/core/src/sockComm.cpp, plugins/resources/replication/Makefile, plugins/resources/replication/irods_create_write_replicator.cpp, plugins/resources/replication/irods_repl_rebalance.cpp, plugins/resources/replication/irods_repl_rebalance.hpp, plugins/resources/replication/irods_repl_retry.cpp, plugins/resources/replication/irods_repl_retry.hpp, plugins/resources/replication/librepl.cpp, tests/pydevtest/test_icommands_file_operations.py, tests/pydevtest/test_resource_types.py
This change adds a configurable retry mechanism to the replication resource. The replication resources can be configured via 3 new settings in the context string of the resource. The retry applies when the replication from an iput or a replication rebalance fails. The default value for each setting is 1, which means a single retry after 1 second has passed.
Adapted changes from master. Jenkins tests passed.
=> [#3436] Add retry capability to replication resc

scripts/irods/test/test_resource_types.py
Test framework will run anything that starts with "test", so we need to change the name to something else.
--
Passed CI tests.
=> [#3436] Rename test_scenario to retry_scenario

scripts/irods/test/test_resource_types.py
test_repl_num_policy was trying to assert both the number of replicas being made based on the num_repl context string and the destination resources of those replicas. As the destination resource is
determined by voting (locality of reference, order in the catalog, etc.), the test was technically non-deterministic and could fail on occasion.
This change modifies the test to just count the number of replicas being produced by the replication resource to ensure that the num_repl policy is being enforced.
--
Waiting for one more CI test. Do not submit until # is added to issue number in commit message.
=> [#3706] More determinism in test_repl_num_policy

scripts/irods/test/test_resource_types.py
test_repl_num_policy was trying to assert both the number of replicas being made based on the num_repl context string and the destination resources of those replicas. As the destination resource is
determined by voting (locality of reference, order in the catalog, etc.), the test was technically non-deterministic and could fail on occasion.
This change modifies the test to just count the number of replicas being produced by the replication resource to ensure that the num_repl policy is being enforced.
(cherry-picked from SHA: 37d419c1e5a113ff31d44c6f2fc4fe28fa3f3ae0)
--
Tests passed in CI.
=> [#3706] Make test_repl_num_policy count repls

iRODS/lib/core/src/scanUtil.cpp, tests/pydevtest/test_iscan.py
Running iscan against a data path which resides on a resource in a hierarchy will result in failure, even if the file is registered in iRODS. In 4.1.x, the resource associated with the data object in the catalog is the root resource, which is not necessarily the storage resource. The query fails because the root resource is not associated with any particular hostname, which is needed to determine if the path is associated with any data objects in iRODS.
This changes chkObjExist to perform three steps:
1. Get all hierarchies for the given data path.
2. Get all resource names for the given hostname.
3. Compare the leaf nodes of each hierarchy to all the resources. If a match is found, the data path exists on the given hostname, and this combination of information in the catalog indicates …
=> [#3419] Fix iscan for resource hierarchies

plugins/resources/replication/librepl.cpp, tests/pydevtest/test_resource_types.py
The redirect map for the operation replication in the replication resource was being re-used over a single connection via a check for an existing property map value.
This change removes the check so that the redirect map is re-generated for each replication.
--
Passed CI tests.
=> [#3904] Generate new child list for each repl (4-1-stable)

scripts/irods/test/test_iscan.py
iscan test is missing hierarchy coverage, so this change adds a passthru resource and puts the testresc in the hierarchy.
(adapted from SHA: 15c38470da974e417895ac1b6a734d8aa873d1d0)
--
Passed CI tests.
=> [#3081] Add hierarchy to iscan test (master)

scripts/irods/test/test_iscan.py
iscan test is missing hierarchy coverage, so this change adds a passthru resource and puts the testresc in the hierarchy.
(adapted from SHA: 15c38470da974e417895ac1b6a734d8aa873d1d0)
--
Passed CI tests.
=> [#3081] Add hierarchy to iscan test (4-2-stable)

plugins/resources/replication/librepl.cpp, scripts/irods/test/test_resource_types.py
The redirect map for the operation replication in the replication resource was being re-used over a single connection via a check for an existing property map value.
This change removes the check so that the redirect map is re-generated for each replication.
(adapted from SHA: 1b758c2)
---
Passed CI tests
=> [#3904] Generate new child list for each repl (master)

plugins/resources/replication/librepl.cpp, scripts/irods/test/test_resource_types.py
The redirect map for the operation replication in the replication resource was being re-used over a single connection via a check for an existing property map value.
This change removes the check so that the redirect map is re-generated for each replication.
---
CI tests passed.
=> [#3904] Generate new child list for each repl (4-2-stable)

plugins/database/src/db_plugin.cpp, plugins/microservices/administration/msi_update_unixfilesystem_resource_free_space/libmsi_update_unixfilesystem_resource_free_space.cpp, tests/pydevtest/test_iadmin.py, tests/pydevtest/test_resource_types.py
When msi_update_unixfilesystem_resource_free_space() updates the free space on a non-existent vault path (or one that boost::filesystem interprets as non-existent), it checks the parent directories of the resource vault path until it finds one that exists, even if it is the root directory ('/' on UNIX systems).
Root directory should not be used as a vault path. An error is now produced if the vault path is set to root directory. Additionally, the root path should not be used in updating the free space on a resource. This change causes msi_update_unixfilesystem_resource_free_space() to log an error and exit if the path_to_stat becomes the root directory because this gives misleading information about the free space on a resource.
---
CI tests passed.
Could not find any portable way to …
=> [#3928] Error when root dir used with vault paths (4-1-stable)

server/re/src/reIn2p3SysRule.cpp
Hi,
The loop counter `index` is double incremented, leading to discard half of the metrics update.
The issue appeared in 4.1.0 with commit c4d070d .
Regards,
Marco
=> Remove double increment for loop counter in rodsMonPerfLog

cmake/development_library.cmake
Building S3 plugin ran into an issue with this file missing. It is included in dataObjOpr.hpp
=> add linked_list header to dev library

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/cache.cpp
See https://github.com/irods/irods/issues/3932
=> Significantly enlarge objectMap hashtable to speed up rule caching.

plugins/database/src/db_plugin.cpp, plugins/microservices/administration/msi_update_unixfilesystem_resource_free_space/libmsi_update_unixfilesystem_resource_free_space.cpp, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_resource_types.py
When msi_update_unixfilesystem_resource_free_space() updates the free space on a non-existent vault path (or one that boost::filesystem interprets as non-existent), it checks the parent directories of the resource vault path until it finds one that exists, even if it is the root directory ('/' on UNIX systems).
Root directory should not be used as a vault path. An error is now produced if the vault path is set to root directory. Additionally, the root path should not be used in updating the free space on a resource. This change causes msi_update_unixfilesystem_resource_free_space() to log an error and exit if the path_to_stat becomes the root directory because this gives misleading information about the free space on a resource.
(cherry-picked from SHA: 4a2cf90)
---
[CI tests …
=> [#3928] Error when root dir used with vault paths (4-2-stable)

scripts/irods/test/test_all_rules.py
(cherry-picked from SHA: bd48352ba1a9216cae077459b46b6a629da2304d)
=> python rule engine testing fails due to leftover shmem (master)

lib/core/include/rodsGenQueryNames.h, scripts/irods/test/test_resource_types.py, server/api/include/rsStructFileExtAndReg.hpp, server/api/src/rsBulkDataObjPut.cpp, server/api/src/rsStructFileExtAndReg.cpp
Fixes a bug where attempting to replicate files extracted from a bundle in a rebalance operation would fail with a BAD_LEXICAL_CAST due to a missing DATA_MODE column. Struct file extraction and registration now includes data mode in the data object information when registering subfiles.
Many dependencies between rsBulkDataObjPut and rsStructFileExtAndReg were not needed, so they were removed as appropriate. Some formatting cleanup at the tops of the files as well.
---
[CI tests passed.](http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/984/)
=> [#3855] Add dataMode in dataObjectInfo for ibun -x (master)

lib/core/include/rodsGenQueryNames.h, scripts/irods/test/test_resource_types.py, server/api/include/rsStructFileExtAndReg.hpp, server/api/src/rsBulkDataObjPut.cpp, server/api/src/rsStructFileExtAndReg.cpp
Fixes a bug where attempting to replicate files extracted from a bundle in a rebalance operation would fail with a BAD_LEXICAL_CAST due to a missing DATA_MODE column. Struct file extraction and registration now includes data mode in the data object information when registering subfiles.
Many dependencies between rsBulkDataObjPut and rsStructFileExtAndReg were not needed, so they were removed as appropriate. Some formatting cleanup at the tops of the files as well.
---
[CI tests passed](http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/985/), but running again after rebase.
=> [#3855] Add dataMode in dataObjectInfo for ibun -x  (4-2-stable)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iadmin.py, server/core/include/irods_database_constants.hpp, server/icat/include/icatHighLevelRoutines.hpp, server/icat/src/icatHighLevelRoutines.cpp
Obsolete columns in R_DATA_MAIN have inconsistent empty values. This change uses well-defined values (EMPTY_*) in a few unused columns for all new data objects registered in iRODS. Replicas made of said data objects will contain the same garbage information. Any data objects or replicas registered before this change will have the out of date information (pre-4.2) or empty values (as of 4.2).
resc_hier and resc_name do not actually store the resc_hier or resc_name anymore, so any code related to repaving these has been removed. Nothing that was removed is in use anymore.
---
[Passed CI](http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/1053/) before rebase. Running again.
=> [#3853] Use known strings in obsolete columns

server/core/src/reServerLib.cpp
When forking to run delayed rules, process more than
maximum_number_of_concurrent_rule_engine_server_processes per batch.
=> [#3941] Process more delayed rules per batch

scripts/irods/test/test_native_rule_engine_plugin.py, server/core/src/reServerLib.cpp
Test ensures that all queued jobs are processed if they can be in the rule engine server execution timeframe.
Also includes fix for double rule exec in delay queue.
---
[CI tests passed.](http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/1137/) Do not merge until #3942 is merged.
=> [#3941] Add test for delay queue batch processing (master)

plugins/auth/pam/libpam.cpp, plugins/database/src/general_query.cpp, server/api/src/rsChkObjPermAndStat.cpp, server/api/src/rsDataObjCopy.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsDataObjUnlink.cpp, server/api/src/rsRmColl.cpp, server/api/src/rsRuleExecDel.cpp, server/core/include/initServer.hpp, server/core/include/rodsConnect.h, server/core/src/initServer.cpp, server/core/src/irods_resource_redirect.cpp, server/core/src/irods_server_control_plane.cpp, server/core/src/objMetaOpr.cpp, server/core/src/physPath.cpp, server/core/src/rodsAgent.cpp, server/core/src/rodsConnect.cpp, server/core/src/rodsServer.cpp, server/re/src/reSysDataObjOpr.cpp
Partial rework of 3ad667c
Instead of removing references to the unused variables, usage was actually implemented (mostly error checking and logging).
---
[Passed CI tests.](http://172.25.14.125:8080/job/irods-build-and-test-workflow/1095/) This change is for master only. A little less rodsLog and que and a little more irods::log and queue, as well.
=> [#3940] Various error handling where there was none (master)

iRODS/clients/icommands/src/iapitest.cpp, iRODS/clients/icommands/src/izonereport.cpp, plugins/resources/replication/librepl.cpp
spOption is the environment variable that the server checks to identify connected client. This variable should be set for all the icommands. izonereport, iapitest, and iclienthints do not set this environment variable. In the case of izonereport and iclienthints, the -h flag was actually not supported at all, despite claiming to have support.
(cherry-picked from irods/irods_client_icommands SHA: 008b5343e086e452cbf62173d94fc4f8fbafd05a)
Also reverts failing when failing to find the child list when replicating create/write, where before it returned with success.
---
[CI tests passed.](http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/1206/)
=> [#3991] Set spOption everywhere (4-1-stable)

server/core/src/physPath.cpp
These two calls were populating a data structure and then never used.
If the username and groupname need to be determined later, the uid/gid
are still being recorded.
=> [#4040] remove calls to determine username/groupname (master)

server/core/src/physPath.cpp
These two calls were populating a data structure and then never used.
If the username and groupname need to be determined later, the uid/gid
are still being recorded.
=> [#4040] remove calls to determine username/groupname (4-2-stable)

scripts/irods/database_interface.py, scripts/update_deprecated_database_columns.py
Adds a script to be run when updating past 4.2.4 which updates the following columns in `R_DATA_MAIN` to contain "known values":
- resc_name: EMPTY_RESC_NAME
- resc_hier: EMPTY_RESC_HIER
- resc_group_name: EMPTY_RESC_GROUP_NAME
Skips any rows with "invalid" resc_id column. A resc_id is considered invalid if it does not exist in R_RESC_MAIN or it maps to a known non-storage resource (i.e. coordinating resource).
Added get_database_type to database_interface for reusability.
---
This script must be run manually.
=> [#3981] Add script for updating obsolete columns in R_DATA_MAIN (master)

scripts/irods/database_interface.py, scripts/update_deprecated_database_columns.py
Adds a script to be run when updating past 4.2.4 which updates the
following columns in R_DATA_MAIN to contain "known values":
- resc_name: EMPTY_RESC_NAME
- resc_hier: EMPTY_RESC_HIER
- resc_group_name: EMPTY_RESC_GROUP_NAME
Skips any rows with "invalid" resc_id column. A resc_id is considered
invalid if it does not exist in R_RESC_MAIN or it maps to a known
non-storage resource (i.e. coordinating resource).
Added get_database_type to database_interface for reusability.
(cherry-picked from SHA: 002b80efa917d089835629c1ab2bba5d43f9645a)
=> [#3981] Script to normalize unused R_DATA_MAIN columns

plugins/database/src/db_plugin.cpp, server/api/src/rsPhyPathReg.cpp
Added support for data size and modify keywords in dataObjInp for rsPhyPathReg. This allows the client to pass DATA_SIZE_KW and DATA_MODIFY_KW to specify the size and modify time of the data object
being registered.
---
[CI tests passed.](http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/1292/)
=> [#4066] Add data size/modify KWs in rsPhyPathReg

plugins/database/src/db_plugin.cpp, server/api/src/rsPhyPathReg.cpp
Added support for data size and modify keywords in dataObjInp for rsPhyPathReg. This allows the client to pass DATA_SIZE_KW and DATA_MODIFY_KW to specify the size and modify time of the data object
being registered.
(cherry-picked from SHA: e24dfb6412a26f60623fff541acada666db05b28)
---
[CI tests running.](http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/1295/)
=> [#4066] Add data size/modify KWs in rsPhyPathReg (master)

lib/core/src/scanUtil.cpp, scripts/irods/test/test_iscan.py
Fixes a problem with `iscan -rd <collection>` where **iscan** would not iterate past a page within a listing of data objects registered  from a filesystem if any entries on that page had had their counterparts in the filesystem deleted.
=> [#4029] Correct checking of statPhysFile return codes in scanObjCol

server/api/src/rsPhyPathReg.cpp
When the size KW is provided in the call to rsPhyPathReg, there is no need to stat the file. As such, there is no need to redirect to the remote server at all. This also resolves an issue with stat'ing 0-length files even in the presence of the size KW.
---
[CI tests passed.](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1327/)
=> [#4066] Skip redirect in reg with size KW (4-2-stable)

scripts/irods/test/test_native_rule_engine_plugin.py
Skips test added in commit for python rule engine plugin:
c553f66
---
CI tests running [for native REP](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1349/) and [python REP](http://172.25.14.63:8080/job/rule-engine-plugin-python-build-test-workflow/92/)
=> [#3906] Skip delay with output param test for PREP (4-2-stable)

scripts/irods/test/test_native_rule_engine_plugin.py
Skips test added in commit for python rule engine plugin:
c553f6633195fa86f5ddb2a05f75825d29886bbd
(cherry-picked from SHA: 166a48b165d96cb9684f81b5736466e6be34bf62)
---
CI tests passed.
=> [#3906] Skip delay with output param test for PREP (master)

scripts/irods/test/test_iscan.py
An extra dir has been created in the setUp step of test_iscan but was not being cleaned up in tearDown.
---
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1319/)
=> [#4029] Clean up dir created in test_iscan setUp (4-2-stable)

scripts/irods/test/test_iscan.py
An extra dir has been created in the setUp step of test_iscan but was not being cleaned up in tearDown.
(cherry-picked from SHA: f1d6c0bde3937d56ec1476de02c83ec098151f2c)
---
[CI tests running](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1385/)
=> [#4029] Clean up dir created in test_iscan setUp (master)

iRODS/server/api/src/rsGetHostForGet.cpp, iRODS/server/api/src/rsGetHostForPut.cpp
rsGetHostForGet and rsGetHostForPut need to make sure they are connected to the correct zone before attempting any operation. If a resource hierarchy is involved, the operation will fail because
the target could be on a remote zone with a resource heirarchy which differs from the connected zone (or worse - one which doesn't differ and data is pulled/put from/to the wrong zone).
---
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1369/) (minus ub16 - investigating)
Discussion point: How would one go about adding a test for this change? I thought about making a microservice for the API calls because by my estimation this is not used internally in iRODS.
=> [#4100] Add zone checking to rsGetHostForGet/Put (4-1-stable)

server/api/src/rsGetHostForGet.cpp, server/api/src/rsGetHostForPut.cpp
rsGetHostForGet and rsGetHostForPut need to make sure they are connected to the correct zone before attempting any operation. If a resource hierarchy is involved, the operation will fail because
the target could be on a remote zone with a resource heirarchy which differs from the connected zone (or worse - one which doesn't differ and data is pulled/put from/to the wrong zone).
(cherry-picked from SHA: eec41ba84bde5687f8fa83acbd377c41fcdfa821)
---
[CI tests running](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1404/)
=> [#4100] Add zone checking to rsGetHostForGet/Put (master)

server/api/src/rsGetHostForGet.cpp, server/api/src/rsGetHostForPut.cpp
rsGetHostForGet and rsGetHostForPut need to make sure they are connected to the correct zone before attempting any operation. If a resource hierarchy is involved, the operation will fail because
the target could be on a remote zone with a resource heirarchy which differs from the connected zone (or worse - one which doesn't differ and data is pulled/put from/to the wrong zone).
(cherry-picked from SHA: eec41ba84bde5687f8fa83acbd377c41fcdfa821)
---
[CI tests running](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1405/)
=> [#4100] Add zone checking to rsGetHostForGet/Put (4-2-stable)

server/api/src/rsPhyPathReg.cpp, server/api/src/rsRegReplica.cpp
rsRegReplica was not honoring DATA_SIZE_KW which means it had to do a stat for every registration. This change adds handling for the DATA_SIZE_KW when registering a data object as a replica.
(cherry-picked from SHA: 18c3df2fd230b11503b599224b0eaa755614c936)
---
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1428/)
=> [#4119] Honor DATA_SIZE_KW in rsRegReplica (4-2-stable)

plugins/database/include/low_level_odbc.hpp, plugins/database/include/mid_level.hpp, plugins/database/src/db_plugin.cpp, plugins/database/src/general_query.cpp, plugins/database/src/low_level_odbc.cpp, plugins/database/src/mid_level_routines.cpp, scripts/irods/test/test_iadmin.py
- Added test cases.
- Initialized memsets in DB structs because on a cllFreeStatement call
pointers are freed and these pointers are sometimes not allocated
(specifically when an error cllFreeStatement() is called after a DB
error.
- This has passed CI.
=> [#3862] Updated code to call cllFreeStatement consistently.

iRODS/lib/core/include/rodsKeyWdDef.h, iRODS/server/api/src/rsDataObjClose.cpp, iRODS/server/api/src/rsDataObjCreate.cpp, iRODS/server/api/src/rsDataObjRepl.cpp, iRODS/server/api/src/rsModDataObjMeta.cpp, iRODS/server/api/src/rsRegReplica.cpp, iRODS/server/api/src/rsStructFileExtAndReg.cpp, iRODS/server/core/src/objDesc.cpp, plugins/resources/replication/irods_repl_types.hpp, plugins/resources/replication/librepl.cpp, tests/pydevtest/test_iadmin.py, tests/pydevtest/test_resource_types.py
This change restricts when fileModified is called in rsModDataObjMeta. This should prevent replication (in the case of replication or compound hierarchies) on any non-write/create operation.
The replication resource has been modified such that the child replication list is generated at the time of fileModified instead of in resolve resource hierarchy. This ensures that the replication list is made available to the machine doing the replication as the property map may not be populated from machine to machine.
---
[CI tests passed](http://172.25.14.63:8080/job/test-ub14-oracle/1651/testReport/). Topo tests pending.
=> [#4099] Prevent file_modified on non-write ops (4-1-stable)

lib/core/include/rodsKeyWdDef.h, plugins/resources/replication/irods_repl_types.hpp, plugins/resources/replication/librepl.cpp, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_resource_types.py, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjCreate.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsModDataObjMeta.cpp, server/api/src/rsRegReplica.cpp, server/api/src/rsStructFileExtAndReg.cpp, server/core/src/objDesc.cpp, server/drivers/src/fileDriver.cpp
This change restricts when fileModified is called in rsModDataObjMeta. This should prevent replication (in the case of replication or compound hierarchies) on any non-write/create operation.
The replication resource has been modified such that the child replication list is generated at the time of fileModified instead of in resolve resource hierarchy. This ensures that the replication list is made available to the machine doing the replication as the property map may not be populated from machine to machine.
Adapted from 0290c7895669525edc1c0b1bcc5209f6f62ace6d
---
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1592/)
=> [#4099] Prevent file_modified on non-write ops (master)

lib/core/include/rodsKeyWdDef.h, plugins/resources/replication/irods_repl_types.hpp, plugins/resources/replication/librepl.cpp, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_resource_types.py, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjCreate.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsModDataObjMeta.cpp, server/api/src/rsRegReplica.cpp, server/api/src/rsStructFileExtAndReg.cpp, server/core/src/objDesc.cpp, server/drivers/src/fileDriver.cpp
This change restricts when fileModified is called in rsModDataObjMeta. This should prevent replication (in the case of replication or compound hierarchies) on any non-write/create operation.
The replication resource has been modified such that the child replication list is generated at the time of fileModified instead of in resolve resource hierarchy. This ensures that the replication list is made available to the machine doing the replication as the property map may not be populated from machine to machine.
Adapted from 0290c78
---
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1593/)
=> [#4099] Prevent file_modified on non-write ops (4-2-stable)

tests/pydevtest/resource_suite.py, tests/pydevtest/test_auth.py
Added to address #3939
(adapted from SHA: afebf9b1ae420f44d38e6d6c5da366cd11ae98d7)
---
[CI tests running](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1601/)
=> [#858] specify RSA key size on generation (4-1-stable)

scripts/irods/paths.py, scripts/run_tests.py
This will run any tests in the `scripts/irods/test/plugins/` directory where the containing file is prefixed with `test_` .
=> [#4146] Added plugins test directory and 'run_plugin_tests' option

CMakeLists.txt, cmake/development_library.cmake, irods_consortium_continuous_integration_build_hook.py, lib/core/include/apiHandler.hpp, lib/core/include/irods_configuration_keywords.hpp, lib/core/src/rcMisc.cpp, lib/core/src/rodsLog.cpp, packaging/server_config.json.template, scripts/run_tests.py, server/core/include/irods_logger.hpp, server/core/include/irods_logger.tpp, server/core/src/irods_logger.cpp, server/core/src/irods_server_control_plane.cpp, server/core/src/rodsAgent.cpp, server/core/src/rodsConnect.cpp, server/core/src/rodsServer.cpp
Depends on: [irods/externals#15]
Fixes Issues: [#2112][#2730][#3131][#3132]
New logging API built on top of the spdlog logging library.  The new logging API
writes to the syslog only.  Messages are formatted as JSON to allow easy
integration with other tools.  All rodsLog style functions also forward the
message to the new logging API.
The server now returns a trace of what happened while processing a
request whenever the verbose flag is detected.  This allows the client to
diagnose what the server was doing without needing to view any log
files.
Replaces std::random_shuffle with std::shuffle.
Requires custom Avro build that replaces deprecated code (std::auto_ptr)
with supported code (std::unique_ptr).
- Dependency satisfied (built using irods-externals-avropre190cpp17-0 package). …
=> [#4074] Introduces new logging API and enables C++17 support.

CMakeLists.txt, cmake/development_library.cmake, lib/core/include/rodsKeyWdDef.h, plugins/database/src/db_plugin.cpp, server/api/src/rsModColl.cpp, server/core/include/irods_rs_comm_query.hpp, server/core/src/irods_rs_comm_query.cpp
- Modified db_mod_coll_op function to also accept a timestamp from the client.
- Adjusted server-side code to allow setting the r_coll_main.modify_ts column of the ICAT database.
- Modified db_mod_coll_op to allow elevating privileges.
- Added missing irods_at_scope_exit header to irods-dev package.
- Created new server-side library for rsComm_t queries.
[Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1650/)
**This branch passing in CI only indicates that the code change did not break existing behavior.**
=> [#4144] Added support to allow clients to manually update the mtime of collections

scripts/irods/test/test_iput_options.py, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjPut.cpp, server/core/src/objDesc.cpp
[#3883] Updated the code to treat zero length files the same as non-zero length
files.  The iput with --purgec and -k option now works the same for
both.
=> [3883] Updated code for zero length files

scripts/irods/test/test_iput_options.py, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjPut.cpp, server/core/src/objDesc.cpp
[#3883] Updated the code to treat zero length files the same as non-zero length
files.  The iput with --purgec and -k option now works the same for
both.
=> [#3883] Updated code for zero length files

server/core/src/initServer.cpp, server/core/src/rodsAgent.cpp
This addresses the resource cleanup problem with rule engines, and in particular fixes a problem expressed by the python rule engine plugin where it would not import a new core file for new agents.
=> [4197] moved stop operation into the cleanup

scripts/irods/core_file.py, scripts/irods/test/test_iput_options.py, scripts/irods/test/test_prep_genquery_iterator.py, scripts/run_tests.py
Created new tests  (test_prep_genquery_iterator.py) for the Python RE
plugin's upcoming [genquery iterator](https://github.com/irods/irods_rule_engine_plugin_python) capability.
In addition a change was made to a test of recursive iput from "./" in
test_iput_options.py that related to irods/irods [#2010].  This was in order
to stabilize an erratic behavior which (in addition to being problem in
itself) interacted badly in CI with the tests outlined here.
The tests are dependent on the existence of /etc/irods/genquery.py which,
as alluded to, will be present in versions >= 4.2.5  of the python rule plugin.
If the module is not seen at the path /etc/irods/genquery.py (such as if the
python rule plugin is not installed, or outdated), all tests of it will be
skipped.
Two iteration methods are …
=> [#1805] wrote tests for PREP genquery iterators

server/core/include/rodsServer.hpp, server/core/src/rodsAgent.cpp, server/core/src/rodsServer.cpp
The main server agent spawner which handles connection requests can
fail when communicating with the agent factory. On failure, the
connection request is freed by the spawning thread and continues.
Later, procChildren comes to clean up the connection request queue
and also frees the connection request, which results in a double free.
This change puts a new message exchange between the main server and
the agent factory when establishing the connection. After the connection
is made, an acknowledgement is sent from the main server to the agent
factory. If anything other than the expected value (a success message)
is received, the agent factory will not fork an agent process.
The server process now consistently cleans up the open sockets and
associated socket files before returning from …
=> [#3776] Prevent double free in agent spawner (master)

server/core/include/rodsServer.hpp, server/core/src/rodsAgent.cpp, server/core/src/rodsServer.cpp
The main server agent spawner which handles connection requests can
fail when communicating with the agent factory. On failure, the
connection request is freed by the spawning thread and continues.
Later, procChildren comes to clean up the connection request queue
and also frees the connection request, which results in a double free.
This change puts a new message exchange between the main server and
the agent factory when establishing the connection. After the connection
is made, an acknowledgement is sent from the main server to the agent
factory. If anything other than the expected value (a success message)
is received, the agent factory will not fork an agent process.
The server process now consistently cleans up the open sockets and
associated socket files before returning from …
=> [#3776] Prevent double free in agent spawner (4-2-stable)

lib/core/include/irods_query.hpp, scripts/irods/test/test_iuserinfo.py, scripts/run_tests.py
max_rows has changed to query_limit conceptually within the query
iterator. Now the user of query objects passes a limit for the
number of results that the iterator will traverse before stopping.
The default value of 0 means that there is no limit and the iterator
will continue until there are no more results. The iterator tracks
how many rows it has processed and when this value exceeds the limit
value, the iterator enters the end iteration state.
The query string is now copied into the query base implementation
object instead of just holding a reference in case the user has passed
a temporary when constructing the query object.
Also...
Adds tests with varying types of inputs for iuserinfo to make sure
zone names are interpreted appropriately by the client.
---
[CI tests …
=> [#4194][#4240] Integrate new query iterator with iuserinfo (master)

lib/core/src/msParam.cpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/functions.cpp, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_rulebase.py
In remote execution blocks, ruleExecOut is not always assigned a type.
This causes a strcmp on a null pointer to char in addMsParamToArray. This
change adds a check in smsi_remoteExec before copying around the ruleExecOut
param to ensure that its type is not null. A check is also done in
addMsParamToArray to ensure type is not null before attempting the strcmp.
---
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1777/)
=> [#3998] Prevent reading of msParam with no type (4-2-stable)

lib/core/src/msParam.cpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/functions.cpp, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_rulebase.py
In remote execution blocks, ruleExecOut is not always assigned a type.
This causes a strcmp on a null pointer to char in addMsParamToArray. This
change adds a check in smsi_remoteExec before copying around the ruleExecOut
param to ensure that its type is not null. A check is also done in
addMsParamToArray to ensure type is not null before attempting the strcmp.
---
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1778/)
=> [#3998] Prevent reading of msParam with no type (master)

scripts/irods/test/test_prep_genquery_iterator.py, server/re/src/genQueryMS.cpp
… on page boundary. Make rei->status 0 instead of a negative value so that
continueInx is propagated back to output variables in the argument list (iRODS 
rule language) or the arguments return list (in Python rules).
This change restores continueInx flag (in the genQueryOut structure) as the sole
and proper indication of when msiGetMoreRows has reached its last serviceable
iteration within an ICAT query spanning more than 1 page of results.
=> [#4157] in msiGetMoreRows don't return CAT_NO_ROWS_FOUND 

CMakeLists.txt, cmake/development_library.cmake, lib/core/include/connection_pool.hpp, lib/core/include/thread_pool.hpp, lib/core/src/connection_pool.cpp
Adds a light wrapper around a boost::asio::io_service and thread_group
to represent a thread_pool (boost::thread::thread_pool was introduced
in boost 1.66, which is newer than the version in use in 4-2-stable).
Each thread points to an io_service and a work object which can be
modified via free-standing functions irods::thread_pool::post and
irods::thread_pool::dispatch (again, modeled after boost::asio).
Adds a mechanism for pooling iRODS connections using irods::thread_pool.
When a connection taken from the pool is destructed, it is returned to the
pool.
These are part of the iRODS dev package.
=> [#4269][#4271] Add thread pool and connection pool (4-2-stable)

scripts/irods/test/test_prep_genquery_iterator.py, server/re/src/genQueryMS.cpp
This change also restores continueInx flag (in the genQueryOut structure) as the sole
and proper indication of when msiGetMoreRows has reached its last serviceable
iteration within an ICAT query spanning more than 1 page of results. (nonzero rei->status
codes prevent the propagation of return values in arithmetics.cpp)
=> [#4157] in msiGetMoreRows prevent CAT_NO_ROWS_FOUND on page boundary

lib/core/src/rcMisc.cpp, lib/core/src/rsyncUtil.cpp
Replaced using namespace directives with namespace alias.
=> [#3995] Moved usage of namespace boost::filesystem into functions (4-2-stable)

lib/core/src/rcMisc.cpp, lib/core/src/rsyncUtil.cpp
Replaced using namespace directives with namespace alias.
=> [#3995] Moved usage of namespace boost::filesystem into functions (master)

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/include/parser.hpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/parser.cpp, scripts/irods/test/test_native_rule_engine_plugin.py
Fixing [irods/irods #4311] which was in response to this [iRODS Chat message](https://groups.google.com/forum/#!topic/irod-chat/NTgPmfzRW0M) wherein long string literals in iRODS native rule language were not being capped by a terminating null character.
=> [#4311] return error for string literals > 1021 characters

plugins/resources/univmss/libunivmss.cpp, plugins/resources/unixfilesystem/libunixfilesystem.cpp, server/api/src/rsFileRename.cpp, server/core/include/irods_resource_constants.hpp
[4326] Do not set the physical path in rsFileRename.cpp.  Set it in libunixfilesystem.cpp and libunivmss.cpp.
=> [4326] Update so that the plugins must set the physical path (4-2-stable)

plugins/resources/univmss/libunivmss.cpp, plugins/resources/unixfilesystem/libunixfilesystem.cpp, server/api/src/rsFileRename.cpp, server/core/include/irods_resource_constants.hpp
[4326] Do not set the physical path in rsFileRename.cpp.  Set it in libunixfilesystem.cpp and libunivmss.cpp.
=> [4326] Update so that the plugins must set the physical path (master)

scripts/irods/test/test_resource_types.py, server/api/src/rsDataCopy.cpp
When performing a remote data copy, the destination l3descInx in the
dataOprInp structure passed to rcDataCopy is converted to match a valid
value on the remote machine. This also needs to be done for the source
l3descInx or else the remote copy may fail if it is not valid on the
other machine. This has been demonstrated on locally executed replications
being driven by a remote call.
=> [#4319] Convert source l3descInx for remote copies (4-2-stable)

scripts/irods/test/test_resource_types.py, server/api/src/rsDataCopy.cpp
When performing a remote data copy, the destination l3descInx in the
dataOprInp structure passed to rcDataCopy is converted to match a valid
value on the remote machine. This also needs to be done for the source
l3descInx or else the remote copy may fail if it is not valid on the
other machine. This has been demonstrated on locally executed replications
being driven by a remote call.
=> [#4319] Convert source l3descInx for remote copies (master)

scripts/irods/test/test_native_rule_engine_plugin.py
This is a temporary measure to write a passing test for the fix to string literals overrunning a buffer in the iRODS rule language.
Merely checking for an error is an adequate test.
[CI tests running](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1921/)
=> [#4311] Fix failing test for long strings (4-2-stable)

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/functions.cpp, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_native_rule_engine_plugin.py, server/core/src/irodsReServer.cpp
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1936/)
test_sigpipe_in_delay_server and test_exception_in_delay_server are nearly identical, but they are testing two different scenarios. In a way, test_exception_in_delay_server covers test_sigpipe_in_delay_server, but I wanted to keep them distinct. I am fine with removing test_sigpipe_in_delay_server if we feel it is not needed.
=> [#4351] Make delay server more resilient (4-2-stable)

CMakeLists.txt, lib/core/include/irods_query.hpp, lib/core/src/packStruct.cpp, plugins/rule_engines/CMakeLists.txt, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/include/reFuncDefs.hpp, server/core/src/irodsReServer.cpp, server/re/include/irods_re_structs.hpp, server/re/src/reStruct.cpp
Query iterator and several places in the delay server itself had leaks
detected in Valgrind.
[CI tests running](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1963/)
=> [#1376] Fix memory leaks detected in delay server (4-2-stable)

plugins/database/src/low_level_odbc.cpp, scripts/irods/test/test_icommands_file_operations.py
A warning message is appearing in the logs stating that there is pending
SQL at cllDisconnect when in fact the number of pending statements is 0.
This change ensures that there are pending statements before attempting
to process or log them.
---
[CI tests running](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1944/)
For reference, the comparison used to be:
https://github.com/irods/irods/blob/e521a02daa8af971fddc9beb62ad02dd57242632/plugins/database/src/low_level_odbc.cpp#L284
=> [#4356] Make "pending SQL at cllDisconnect" true (master)

scripts/irods/configuration.py, scripts/irods/paths.py, scripts/irods/test/test_delay_queue.py, server/core/src/irodsReServer.cpp
As of this change, irodsReServer will no longer write to the reLog.
Adjusts tests to check inside server log for delay server messages.
---
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/)
Not sure why the irods::experimental::log::init() call is necessary (not needed for agent spawner process, which is what I based this change upon), but it seems that the irodsReServer process becomes a zombie if not. Am I holding it wrong, @korydraughn?
=> [#4344] Use syslog utility in delay server (master)

scripts/irods/test/test_dynamic_peps.py, scripts/run_tests.py, server/re/src/irods_re_serialization.cpp
Tested in CI and Docker.
All tests passed in CI (excluding upgrade tests).  See results [here](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1981/).
All tests passed in Docker except the following (which I believe are docker related issues):
- test_resource_types
- test_resource_tree
=> Re-exposes dataObjInp_t to Native Rule Language (4-2-stable)

lib/core/include/irods_query.hpp, lib/core/src/connection_pool.cpp, scripts/irods/test/test_dynamic_peps.py, scripts/run_tests.py, server/re/src/irods_re_serialization.cpp
Tested in Docker.
All tests passed in Docker except the following (which I believe are docker related issues):
- test_resource_types
- test_resource_tree
=> Re-exposes dataObjInp_t to Native Rule Language - (master)

plugins/database/src/general_query.cpp, scripts/irods/test/test_irm.py
All tests passed in Docker (except the ones that usually fail).
All tests passed in CI.  See [here](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1988/)
=> [#3398] Properly handle "&&" in collection names when removing (4-2-stable)

plugins/database/src/general_query.cpp, scripts/irods/test/test_irm.py
All tests passed in Docker (except the ones that usually fail).
=> [#3398] Properly handle "&&" in collection names when removing (master)

scripts/irods/test/test_stacktrace.py, scripts/run_tests.py, server/core/src/irods_signal.cpp
Docker - Passed
[CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/2086/) - Passed (with a false positive)
FYI: Boost has a stacktrace library and notes about handling stacktraces with signals.
- [Boost.Stacktrace](https://www.boost.org/doc/libs/1_67_0/doc/html/stacktrace/getting_started.html#stacktrace.getting_started.handle_terminates_aborts_and_seg)
The man pages for [signal safety](http://man7.org/linux/man-pages//man7/signal-safety.7.html) lists the functions that are safe to use in signals too.
=> [#4382] Stacktraces now appear in the log file (master)

lib/core/include/rodsPath.h, lib/core/src/lsUtil.cpp, lib/core/src/rodsPath.cpp, scripts/core_tests_list.json, scripts/irods/test/test_ipwd.py
Passed in new CI (core tests and federation only)
=> [#4060] Paths now escape '\f' character (4-2-stable)

plugins/resources/structfile/libstructfile.cpp, scripts/core_tests_list.json, scripts/irods/lib.py, scripts/irods/test/test_ibun.py
The extract operation in structfile resource plugin reads in entire files into a memory buffer without regard for size. If the file in question overflows an int when its size in bytes is calculated, libarchive will fail to read the file and extraction will do nothing. This change iterates over the file using a block size and the buffer pointer in use today. The block_size has been hard-coded to 1MB as performance gains above this are negligible, and block sizes below this only become increasingly worse as the value decreases.
The `make_file` utility in lib.py grew an option to pass a block size as well. This allows for much larger files than was possible before as `dd` will not always be able to generate a file large enough to meet the requested size in the current implementation. Now the …
=> [#4495] Chunk libarchive reads for extractions (master)

plugins/resources/structfile/libstructfile.cpp, scripts/core_tests_list.json, scripts/irods/lib.py, scripts/irods/test/test_ibun.py
The extract operation in structfile resource plugin reads in entire files into a memory buffer without regard for size. If the file in question overflows an int when its size in bytes is calculated, libarchive will fail to read the file and extraction will do nothing. This change iterates over the file using a block size and the buffer pointer in use today. The block_size has been hard-coded to 1MB as performance gains above this are negligible, and block sizes below this only become increasingly worse as the value decreases.
The make_file utility in lib.py grew an option to pass a block size as well. This allows for much larger files than was possible before as dd will not always be able to generate a file large enough to meet the requested size in the current implementation. Now the …
=> [#4495] Chunk libarchive reads for extractions (4-2-stable)

scripts/irods/lib.py, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_ibun.py
ibun -x of sufficiently large tar files needs a test to match the
test for extraction of sufficiently large zip files.
Also, fixed bug with "leftover" size for creating files in lib.make_file.
=> [#4118] Add test for extracting large tar file (master)

scripts/irods/lib.py, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_ibun.py
ibun -x of sufficiently large tar files needs a test to match the
test for extraction of sufficiently large zip files.
Also, fixed bug with "leftover" size for creating files in lib.make_file.
=> [#4118] Add test for extracting large tar file (4-2-stable)

lib/core/src/rodsPath.cpp, lib/filesystem/include/filesystem/detail.hpp, lib/filesystem/include/filesystem/path.hpp, lib/filesystem/src/path.cpp, unit_tests/src/filesystem/test_path.cpp
=> [#4534] irods::filesystem::path::lexically_normal now follows the standard (4-2-stable)

lib/filesystem/src/filesystem.cpp, lib/filesystem/src/path.cpp, unit_tests/src/filesystem/test_filesystem.cpp, unit_tests/src/filesystem/test_path.cpp
=> [#4551] irods::filesystem::path::parent_path() is compliant with the standard (4-2-stable)

scripts/irods/database_upgrade.py
When pypyodbc talks to oracle, the implicit cast from
string->int->numbers(38) was dropping the last character of the string.
It is not yet clear if this is a pypyodbc bug or Oracle ODBC bug.
--
Needs to go through CI to confirm mysql/postgres not affected by this new int().
=> [4459] fix implicit cast bug when talking to oracle (4-2-stable)

scripts/irods/database_upgrade.py
When pypyodbc talks to oracle, the implicit cast from
string->int->numbers(38) was dropping the last character of the string.
It is not yet clear if this is a pypyodbc bug or Oracle ODBC bug.
=> [#4459] fix implicit cast bug when talking to oracle

server/api/src/rsDataObjWrite.cpp
Should `bytesWritten` in the L1 descriptor hold the total bytes written over the connection or should it hold the bytes written from the last call?
=> [#4598] rsDataObjWrite now updates bytesWritten in L1 descriptors (master)

server/api/src/rsDataObjWrite.cpp
Should `bytesWritten` in the L1 descriptor hold the total bytes written over the connection or should it hold the bytes written from the last call?
=> [#4598] rsDataObjWrite now updates bytesWritten in L1 descriptors (4-2-stable)

VERSION.json.dist.in, scripts/irods/database_connect.py, scripts/irods/database_upgrade.py
- Allows "rodsadmin" and "public" groups to be found via USER_GROUP_NAME.
- Bumps catalog schema version.
=> [#4672][#4632] Add missing entries to r_user_group table (4-2-stable)

lib/core/src/rmUtil.cpp, lib/core/src/trimUtil.cpp, plugins/database/src/db_plugin.cpp, scripts/irods/lib.py, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_control_plane.py, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_dynamic_peps.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_ireg.py, scripts/irods/test/test_irm.py, scripts/irods/test/test_irule.py, scripts/irods/test/test_iunreg.py, scripts/irods/test/test_log_levels.py, scripts/irods/test/test_native_rule_engine_plugin.py, scripts/irods/test/test_resource_types.py, scripts/irods/test/test_rule_engine_plugin_framework.py, scripts/irods/test/test_rulebase.py, scripts/irods/test/test_stacktrace.py, server/api/src/rsDataObjUnlink.cpp, server/api/src/rsRmColl.cpp
All tests pass in CI except for `test_all_rules.Test_AllRules.test_rulemsiServerMonPerf_r ` (#4720 - note: this passes at the bench) and `Test_Replication_With_Retry` (#4727)
Requires irods/irods_client_icommands#113
=> [#4506] Add support for iunreg + fix tests checking logs (master)

scripts/irods/test/rule_texts_for_tests.py
REPF no longer emits failure to rsExecRuleExpression when executing
rules with no targeted rule engine plugin instance, so there is no
error message logged on failure. Need to target the default rule
engine plugin instance to ensure that the failure is emitted.
=> [#4736] Target default RE instance in delay queue test (master)

scripts/irods/test/test_federation.py, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_iticket.py, server/api/include/rsDataObjCreate.hpp, server/api/src/rsDataObjCreate.cpp, server/api/src/rsDataObjPut.cpp
rsDataObjPut and rsDataObjCreate now register data objects before
touching the disk. This prevents situations in which existing data
objects being overwritten by unauthorized users would have their
associated files unlinked from the data object (orphan).
Adds a test to put to a resource with a vault path for which iRODS
has no write access. Modifies ticket put/get tests to trigger parallel
transfer.
---
CI tests passed. More tests to come later as this may fix additional issues, so hold off on merging.
=> [#4410] Attempt registration before moving data (4-2-stable)

scripts/irods/test/test_federation.py, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_iticket.py, server/api/include/rsDataObjCreate.hpp, server/api/src/rsDataObjCreate.cpp, server/api/src/rsDataObjPut.cpp
rsDataObjPut and rsDataObjCreate now register data objects before
touching the disk. This prevents situations in which existing data
objects being overwritten by unauthorized users would have their
associated files unlinked from the data object (orphan).
Adds a test to put to a resource with a vault path for which iRODS
has no write access. Modifies ticket put/get tests to trigger parallel
transfer.
---
CI tests running. More tests to come later as this may fix additional issues, so hold off on merging.
=> [#4410] Attempt registration before moving data (master)

server/core/src/irodsReServer.cpp
Passed CI tests as part of #4749 and removed due to being a separate issue.
=> [#4735] Use free function to create single-conn pool (master)

server/core/src/irodsReServer.cpp
Passed CI tests as part of #4751 and removed due to being a separate issue.
=> [#4735] Use free function to create single-conn pool (4-2-stable)

scripts/irods/test/test_resource_types.py
This reverts commit 6a68379b7e8218cb0420e6550db477b61bf5ef09.
Accompanied by irods/irods_testing_jenkins#67, the tests pass in CI.
=> Revert "[#4727] Skip Test_Resource_Replication_With_Retry" (4-2-stable)

CMakeLists.txt, cmake/development_library.cmake, lib/core/include/group.hpp, lib/core/include/user.hpp, lib/core/include/user_administration.hpp, lib/core/src/group.cpp, lib/core/src/user.cpp, lib/core/src/user_administration.cpp, scripts/irods/database_upgrade.py, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_user_administration.cmake, unit_tests/src/test_user_administration.cpp, unit_tests/unit_tests_list.json
- Added new specific query for listing all groups a user is a member of.
- Unit-testing of remote operations is disabled by default. To enable,
define the macro "IRODS_TEST_REMOTE_USER_ADMINISTRATION_OPERATIONS".
=> [#4650] User Administration Library (4-2-stable)

CMakeLists.txt, cmake/development_library.cmake, lib/core/include/group.hpp, lib/core/include/user.hpp, lib/core/include/user_administration.hpp, lib/core/src/group.cpp, lib/core/src/user.cpp, lib/core/src/user_administration.cpp, scripts/irods/database_upgrade.py, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_user_administration.cmake, unit_tests/src/test_user_administration.cpp, unit_tests/unit_tests_list.json
- Added new specific query for listing all groups a user is a member of.
- Unit-testing of remote operations is disabled by default. To enable,
define the macro "IRODS_TEST_REMOTE_USER_ADMINISTRATION_OPERATIONS".
=> [#4650] User Administration Library (master)

packaging/preremove.sh
The script was attempting to cleanup the iRODS catalog of any
iRODS resources resident on this to-be-removed catalog consumer server.
Any cleanup should be performed by a rodsadmin at a later time.
Removing this code in service of the 'Principle of Least Surprise'.
=> [4612] no longer attempt to cleanup in preremove.sh (4-2-stable)

packaging/preremove.sh
The script was attempting to cleanup the iRODS catalog of any
iRODS resources resident on this to-be-removed catalog consumer server.
Any cleanup should be performed by a rodsadmin at a later time.
Removing this code in service of the 'Principle of Least Surprise'.
=> [#4612] no longer attempt to cleanup in preremove.sh (master)

scripts/generate_iadmin_commands_for_41_to_42_upgrade.py
provides additional confidence in light of any confusion
from the packaged preremove.sh script included in 4.1.x.
=> [4307] add helper script for 41 to 42 upgrade

scripts/irods/test/resource_suite.py
Files registered outside of vault are no longer deleted so they need to be cleaned up in test.
=> [4848] Update resource suite to clean up registered file

plugins/api/src/atomic_apply_metadata_operations.cpp, scripts/irods/test/test_all_rules.py, unit_tests/CMakeLists.txt, unit_tests/src/filesystem/test_filesystem.cpp
Disables all tests that call the database plugin and nanodbc within the same process.
=> [#4916] Atomic API plugin detects database flavor and uses the correct SQL syntax (4-2-stable)

plugins/api/src/atomic_apply_metadata_operations.cpp, scripts/irods/test/test_all_rules.py, unit_tests/CMakeLists.txt, unit_tests/src/filesystem/test_filesystem.cpp
Disables all tests that call the database plugin and nanodbc within the same process.
=> [#4916] Atomic API plugin detects database flavor and uses the correct SQL syntax (master)

lib/core/include/dstream.hpp, unit_tests/src/filesystem/test_path.cpp
It is a little naughty to use std::memcpy and similar without directly including #include <cstring> and this behaviour is not guaranteed to work on all platforms or with future C++ library versions.
=> Include <cstring> if using std:mem functions

scripts/irods/test/test_federation.py
Skips two tests that were fixed in 4.2.3 for any version older than
4.2.3. Modifies the remote vault path if the remote version is less
than 4.0.0 as /var/lib/irods does not exist in those versions.
---
Tests pass
=> [#4978] Fix for federation tests in 3.x (4-2-stable)

scripts/irods/test/test_federation.py
Skips two tests that were fixed in 4.2.3 for any version older than
4.2.3. Modifies the remote vault path if the remote version is less
than 4.0.0 as /var/lib/irods does not exist in those versions.
---
Tested successfully against 4-2-stable, need to run against master.
=> [#4978] Fix for federation tests in 3.x (master)

lib/core/include/key_value_proxy.hpp, lib/core/src/rcMisc.cpp, server/api/src/rsDataObjOpen.cpp, unit_tests/src/test_irods_key_value_proxy.cpp
Adds template class for key_value_proxy to support const keyValPair_t
as well as enforcing the fact that the proxy only manages keyValPair_t's.
Several missing pieces were added to the iterator and handle classes to
flesh out the interface a little more.
`get()` was changed to return a pointer instead of a reference to the
underlying object in order to maintain const-ness of underlying struct.
Without this, a const keyValPair_t could be given to a proxy object and
returned as non-const.
=> Add const struct support in key_value_proxy and change interface a little (master)

lib/core/include/key_value_proxy.hpp, lib/core/src/rcMisc.cpp, unit_tests/src/test_irods_key_value_proxy.cpp
Adds template class for key_value_proxy to support const keyValPair_t
as well as enforcing the fact that the proxy only manages keyValPair_t's.
Several missing pieces were added to the iterator and handle classes to
flesh out the interface a little more.
get() was changed to return a pointer instead of a reference to the
underlying object in order to maintain const-ness of underlying struct.
Without this, a const keyValPair_t could be given to a proxy object and
returned as non-const.
=> [#4972] Support const struct in key_value_proxy (4-2-stable)

lib/api/src/rcSetRoundRobinContext.cpp, server/api/src/rsSetRoundRobinContext.cpp
Simply adds `[[deprecated]]` and logs a warning whenever the server-side API call is used.
=> [#4964] Deprecate rxSetRoundRobinContext (4-2-stable)

CMakeLists.txt, plugins/api/src/atomic_apply_metadata_operations.cpp, server/core/include/catalog.hpp, server/core/include/catalog_utilities.hpp, server/core/src/catalog.cpp, server/core/src/catalog_utilities.cpp, server/re/src/extractAvuMS.cpp
Adds a new catalog library for general catalog transaction execution.
Adds a new catalog utilities library for adding more specific operations.
---
Currently leaning on tests for atomic_apply_metadata_operations API plugin, but probably needs further testing (hence, draft for now).
=> [#5011] Add catalog utility libraries (master)

CMakeLists.txt
Hi,
during the build, avrogencpp from externals was failing because it wasn't finding (the correct) boost libraries that also are in externals. 
```
[ 80%] Generating lib/core/include/server_control_plane_command.hpp
/home/hastings/work/irods/irods-externals/avro1.9.0-0/bin/avrogencpp -n irods -o /home/hastings/work/irods/irods/build3/lib/core/include/server_control_plane_command.hpp -i /home/hastings/work/irods/irods/irods_schema_messaging/v1/server_control_plane_command.json
/home/hastings/work/irods/irods-externals/avro1.9.0-0/bin/avrogencpp: symbol lookup error: /home/hastings/work/irods/irods-externals/avro1.9.0-0/bin/avrogencpp: undefined symbol: _ZNK5boost15program_options29value_semantic_codecvt_helperIcE5parseERNS_3anyERKNSt3__16vectorINS5_12basic_stringIcNS5_11char_traitsIcEENS5_ …
```
=> Use LD_LIBRARY_PATH so that avrogencpp finds the correct boost libs.

server/core/src/rsLog.cpp
It is unnecessary to close() a fd before calling dup2() on it - dup2
will close the fd if necessary. Importantly, dup2 will do so
atomically, whereas the code here is racy - some other thread could
open() something inbetween the close() and dup2(), in which case that
other thread's FD will be overwritten.
This is a partial fix for #4943
Signed-off-by: Matthew Vernon <mv3@sanger.ac.uk>
=> Don't close() fds before calling dup2() on them

server/core/src/rsLog.cpp
It is unnecessary to close() a fd before calling dup2() on it - dup2
will close the fd if necessary. Importantly, dup2 will do so
atomically, whereas the code here is racy - some other thread could
open() something inbetween the close() and dup2(), in which case that
other thread's FD will be overwritten.
This is a partial fix for #4943
Signed-off-by: Matthew Vernon <mv3@sanger.ac.uk>
=> [#4943] Don't close() fds before calling dup2() on them (4-2-stable)

lib/core/include/lifetime_manager.hpp, lib/core/include/replica_proxy.hpp, server/api/include/rsPhyBundleColl.hpp, server/api/src/rsChkObjPermAndStat.cpp, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsPhyBundleColl.cpp, server/api/src/rsPhyPathReg.cpp, server/core/include/irods_get_l1desc.hpp, server/core/src/irods_get_l1desc.cpp, unit_tests/src/test_irods_key_value_proxy.cpp, unit_tests/src/test_irods_lifetime_manager.cpp
CI tests are running - previously failing tests passed at the bench.
Some notes here...
1. rsPhyPathReg must now return the dataObjInfo_t of the replica that was just registered in the catalog. As such, some of the free's have been removed. This is not leaking these structs, but rather transfers ownership to the global L1 descriptor table, which is cleaned up on agent exit. Otherwise, the lifetime_manager provided by the replica_proxy factory method cleans up the dataObjInfo_t.
2. The shift to returning pointers in the get() and release() methods of the lifetime_manager is consistent with the proxy objects' get() methods. This was needed in order to prevent freeing the dataObjInfo_t generated in rsPhyPathReg.
=> Fix rsPhyPathReg for create + lifetime_manager tweaks + suppress some non-error log messages (master)

plugins/microservices/CMakeLists.txt, plugins/microservices/msi_get_agent_pid/CMakeLists.txt, plugins/microservices/msi_get_agent_pid/libmsi_get_agent_pid.cpp, plugins/resources/replication/irods_create_write_replicator.cpp, plugins/resources/replication/irods_repl_retry.cpp, scripts/irods/lib.py, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_native_rule_engine_plugin.py, scripts/irods/test/test_resource_types.py, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjRepl.cpp
In order to increase coverage in distributed testing and prevent timing issues with respect to flushing to logs, this change uses `msiAssociateKeyValuePairsToObj` instead of `writeLine` in several rules in the delay queue tests and the NREP tests. Also adds a new microservice to get the PID of the agent executing it.
Tests are being run now.
=> Remove some server log reading in tests (master)

plugins/microservices/msi_get_agent_pid/CMakeLists.txt
Does not link for debug builds, apparently. Made to match other microservice plugins.
=> [#4949] Link libboost_system in msi_get_agent_pid (master)

plugins/microservices/msi_get_agent_pid/CMakeLists.txt
Cherry-picked from #5196 . Made to match other microservice plugins.
=> [#4949] Link libboost_system in msi_get_agent_pid (4-2-stable)

scripts/core_tests_list.json, scripts/irods/test/test_catalog.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_izonereport.py, server/core/src/irods_report_plugins_in_json.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_zone_report.cmake, unit_tests/src/test_zone_report.cpp, unit_tests/unit_tests_list.json
This is meant to address #5170. I'll make another pull request for the `4-2-stable` branch once this one has passed review.
If a test case is required, I may need some direction. I've tried adding one to `test_resource_administration.cpp`, but the resources added with `adm::client` do not show up in the output from `rcServerReport`.
=> [#5170] Add id to resource json serialization (master)

scripts/core_tests_list.json, scripts/irods/test/test_imeta_interactive.py
#5204 cherry-picked into stable.
Companion pull request for irods/irods_client_icommands#164
A few tests for interactive `imeta`
Addresses #5081
Currently being pushed through jenkins, will update when done
=> [#5081] Add test class for interactive imeta (4-2-stable)

CMakeLists.txt, lib/core/include/dstream.hpp, lib/core/src/packStruct.cpp, lib/core/src/rcMisc.cpp, lib/filesystem/include/filesystem/path_traits.hpp, unit_tests/src/test_irods_lifetime_manager.cpp, unit_tests/src/test_irods_linked_list_iterator.cpp
Cherry-pick of #5209
Polished up the changes I've made to my local clone so that I can build with the version of clang I have installed.
I've verified that clang 6 is still happy, too.
See the individual commit messages for more information.
Addresses #5213
Cherry-pick wasn't clean, so I'm going to push it through jenkins again. Will update when that's done.
=> [#5213] Make Clang 10 happy (4-2-stable)

server/api/src/rsDataObjClose.cpp
CI tests running.
A note about the TODO: This is technically incorrect as we need to check for the expected size of the replica before we determine that it is good. This PR will restore the historical behavior of assuming new replicas with no bytes written are good. Future changes will require more vetting with respect to the expected size of the replica.
=> [#5193] Mark newly created replicas as good with no bytes written (master)

lib/filesystem/src/filesystem.cpp
=> [#5319] Filesystem library deallocates memory correctly for C structures (4-2-stable)

scripts/irods/test/test_catalog.py
Passed at bench.
CI not required.
Depends on https://github.com/irods/irods_client_icommands/pull/185
=> [#4761] Added test for ilocate case-insensitive search (4-2-stable)

scripts/irods/test/test_catalog.py
Passed at bench.
CI not required.
Depends on https://github.com/irods/irods_client_icommands/pull/184
=> [#4761] Added test for ilocate case-insensitive search (master)

scripts/setup_irods.py
allows systemd to have better visibility of iRODS processes
=> [_5275] stop the server at end of setup_irods.py (master)

scripts/setup_irods.py
allows systemd to have better visibility of iRODS processes
=> [_5275] stop the server at end of setup_irods.py (4-2-stable)

lib/api/include/specificQuery.h, lib/core/include/irods_query.hpp, lib/core/include/query_processor.hpp, lib/core/include/replica.hpp, lib/core/include/transport/default_transport.hpp, lib/core/src/chksumUtil.cpp, scripts/irods/test/test_ichksum.py, unit_tests/src/filesystem/test_filesystem.cpp, unit_tests/src/test_get_file_descriptor_info.cpp
This change will likely break code using the `query_processor` due to a change in the interface. Fixing the broken plugins, etc. should be an easy fix.
=> Fixed memory leaks and ichksum -r output (4-2-stable)

scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_rulebase.py
Adds a test which creates a data object and closes it without writing to
it using the microservices in a rule. The resultant replica should be
marked as good. The python version of this rule was implemented but not
tested.
=> [#5018] add msiDataObjCreate/Close test (4-2-stable)

scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_rulebase.py
Adds a test which creates a data object and closes it without writing to
it using the microservices in a rule. The resultant replica should be
marked as good. The python version of this rule was implemented but not
tested.
=> [#5018] add msiDataObjCreate/Close test (master)

CMakeLists.txt, cmake/Modules/CheckCPPMacroDefinition.cmake, cmake/Modules/FindLibCXX.cmake
@korydraughn discovered that our irods-externals package for libc++ lacks unversioned symlinks for libc++ and libc++abi, which was causing FindLibCXX to miss them and choose the libraries that lived in our clang irods-externals package.
This PR fixes the issue by having `find_library` additionally search for the verioned library symlink when looking in the irods-externals libc++ prefix.
Fixes #5354 for master.
Touches #5250.
Currently pushing through jenkins
=> [#5354] Handle missing unversioned libc++ symlink in FindLibCXX.cmake (master)

CMakeLists.txt, cmake/Modules/CheckCPPMacroDefinition.cmake, cmake/Modules/FindLibCXX.cmake
Cherry-pick of #5355 into stable
Fixes #5354 for stable.
Touches #5250.
=> [#5354] Handle missing unversioned libc++ symlink in FindLibCXX.cmake (4-2-stable)

plugins/api/src/replica_open.cpp, scripts/irods/test/test_istream.py, server/api/src/rsDataObjOpen.cpp
This change keeps the server log quiet.
=> [#5419] Opening non-existent data object for read does not produce a stacktrace (4-2-stable)

lib/api/include/data_object_finalize.h, plugins/api/src/data_object_finalize.cpp, plugins/api/src/replica_close.cpp, scripts/irods/test/resource_suite.py, server/api/include/rs_data_object_finalize.hpp, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsModDataObjMeta.cpp, server/core/include/replica_state_table.hpp, server/core/src/initServer.cpp, server/core/src/replica_state_table.cpp, unit_tests/src/test_data_object_finalize.cpp, unit_tests/src/test_replica_state_table.cpp
The data_object_finalize and replica_state_table interfaces are very
closely related and so the JSON passed between the two has been modified
to bring a sense of consistency and clarity to their usage.
The RST interfaces underwent the following changes:
- RST entries are now keyed via data_id instead of full logical
path (has to be a string for JSON compliance)
- update now takes only a list of r_data_main column-string pairs
- publish_to_catalog:
- now takes a replica number and a JSON object which, if
present, indicates that file_modified should be triggered
- JSON object is added as a field to the replica indicated
by the replica number input
The data_object_finalize API underwent the following changes:
- data_id field was removed as it served no purpose - this should be
retrieved from …
=> [#4331] Update data_object_finalize/RST interfaces (master)

lib/api/include/data_object_finalize.h, plugins/api/src/data_object_finalize.cpp, plugins/api/src/replica_close.cpp, scripts/irods/test/resource_suite.py, server/api/include/rs_data_object_finalize.hpp, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsModDataObjMeta.cpp, server/core/include/replica_state_table.hpp, server/core/src/initServer.cpp, server/core/src/replica_state_table.cpp, unit_tests/src/test_data_object_finalize.cpp, unit_tests/src/test_replica_state_table.cpp
The data_object_finalize and replica_state_table interfaces are very
closely related and so the JSON passed between the two has been modified
to bring a sense of consistency and clarity to their usage.
The RST interfaces underwent the following changes:
- RST is now a std::map<std::uint64_t, nlohmann::json> instead of
simply a JSON map for key-type flexibility
- Entries are keyed by data_id instead of logical path
- update now takes only a list of r_data_main column-string pairs
- publish_to_catalog:
- now takes a replica number and a JSON object which, if
present, indicates that file_modified should be triggered
- JSON object is added as a field to the replica indicated
by the replica number input
The data_object_finalize API underwent the following changes:
- data_id field was removed …
=> [#4331] Update data_object_finalize/RST interfaces (4-2-stable)

server/api/include/rsDataObjGet.hpp, server/api/src/rsDataObjGet.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsL3FileGetSingleBuf.cpp
Implements single buffer gets (that is, gets of replicas whose size is
under the configured maximum_size_for_single_buffer_in_megabytes value)
as an open/read/close rather than using l3GetDataSingleBuf and
determining whether to perform a physical file open via the
PHYOPEN_BY_SIZE_KW. The open is now performed as normal and the size
information included in the L1 descriptor table is used to determine if
the get will be single buffer or parallel.
---
CI tests passed. I have outlined potential impacts (or lack thereof) here: https://github.com/irods/irods/issues/5494#issuecomment-810417599
=> [#5494] Remove use of PHYOPEN_BY_SIZE_KW in server (master)

scripts/irods/test/test_imeta_interactive.py
Issue was addressed in this  [icommands PR](https://github.com/irods/irods_client_icommands/pull/199)
=> [5518] test quoted arguments in imeta interactive mode (4-2-stable)

server/api/include/rsDataObjGet.hpp, server/api/src/rsDataObjGet.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsL3FileGetSingleBuf.cpp
Implements single buffer gets (that is, gets of replicas whose size is
under the configured maximum_size_for_single_buffer_in_megabytes value)
as an open/read/close rather than using l3GetDataSingleBuf and
determining whether to perform a physical file open via the
PHYOPEN_BY_SIZE_KW. The open is now performed as normal and the size
information included in the L1 descriptor table is used to determine if
the get will be single buffer or parallel.
---
cherry-picked from ef80a36583bfb6f77856d47163f4662b8c620a39 
=> [#5494] Remove use of PHYOPEN_BY_SIZE_KW in server (4-2-stable)

plugins/database/src/db_plugin.cpp, scripts/core_tests_list.json, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_iqmod.py, server/api/src/rsRuleExecSubmit.cpp, server/core/src/irodsReServer.cpp, server/re/src/irods_re_structs.cpp
Valid priority levels are defined by the following range: [1 - 9]
The delay server gathers and schedules rules in descending order of
priority level.
`<PRI>` tag is no longer supported by the delay(). Use `<PRIORITY>` instead.
Attempting to use `<PRI>` will result in an error.
Reoccurring rules that have an empty priority level will be updated to
have a priority level of 5 following successful execution. This also
applies to rules that have an invalid priority level.
=> [#2759] Delay server now honors a rule's priority (master)

plugins/database/src/db_plugin.cpp, scripts/core_tests_list.json, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_iqmod.py, server/api/src/rsRuleExecSubmit.cpp, server/core/src/irodsReServer.cpp, server/re/src/irods_re_structs.cpp
Valid priority levels are defined by the following range: [1 - 9]
The delay server gathers and schedules rules in descending order of
priority level.
`<PRI>` tag is no longer supported by the delay(). Use `<PRIORITY>` instead.
Attempting to use `<PRI>` will result in an error.
Reoccurring rules that have an empty priority level will be updated to have a
priority level of 5 following successful execution. This also applies to
rules that have an invalid priority level.
=> [#2759] Delay server now honors a rule's priority (4-2-stable)

plugins/api/src/atomic_apply_acl_operations.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, plugins/api/src/data_object_finalize.cpp, plugins/api/src/get_file_descriptor_info.cpp, plugins/api/src/replica_close.cpp, plugins/api/src/replica_open.cpp, plugins/api/src/touch.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_json_apis_from_client.cmake, unit_tests/src/test_json_apis_from_client.cpp, unit_tests/unit_tests_list.json
Use `BinBytesBuf_PI` (instead of `BytesBuf_PI`) as packing instructions when contained text fields are likely to contain XML special characters (ie `<`, `>`, `&`) or other arbitrary content possibly unsuitable for use with iRODS `XML_PROT` (JSON api requests and/or responses for example).
=> [5520] use BinBytesBuf_PI for new API's (4-2-stable)

plugins/api/src/atomic_apply_acl_operations.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, plugins/api/src/data_object_finalize.cpp, plugins/api/src/experimental_api_plugin_adaptor.cpp, plugins/api/src/get_file_descriptor_info.cpp, plugins/api/src/replica_close.cpp, plugins/api/src/replica_open.cpp, plugins/api/src/touch.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_json_apis_from_client.cmake, unit_tests/src/test_json_apis_from_client.cpp, unit_tests/unit_tests_list.json
Use `BinBytesBuf_PI` (instead of `BytesBuf_PI`) as packing instructions when contained text fields are likely to contain XML special characters (ie `<`, `>`, `&`) or other arbitrary content possibly unsuitable for use with iRODS `XML_PROT` (JSON api requests and/or responses for example).
=> [5520] use BinBytesBuf_PI for new API's (master)

scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_dynamic_peps.py
The dataObjInfo struct was not being fully populated when registering a
data object in the database. In particular, the user name, zone name,
and create time were not populated so PEPs which look inside these
structs were not able to extract the appropriate information. This has
been fixed but needed a test which this change provides.
=> [#5554] Add test for reg_data_obj dynamic post-PEP (4-2-stable)

scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_dynamic_peps.py
The dataObjInfo struct was not being fully populated when registering a
data object in the database. In particular, the user name, zone name,
and create time were not populated so PEPs which look inside these
structs were not able to extract the appropriate information. This has
been fixed but needed a test which this change provides.
---
Test passes
=> [#5554] Add test for reg_data_obj dynamic post-PEP (master)

plugins/api/src/replica_close.cpp, scripts/irods/test/test_iput.py, scripts/irods/test/test_istream.py, scripts/irods/test/test_resource_types.py, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRepl.cpp, server/core/src/initServer.cpp, unit_tests/src/test_rc_data_obj.cpp, unit_tests/src/test_replica.cpp, unit_tests/src/unit_test_utils.hpp
Passed CI before trace log message removal. Running through CI again.
Do we want to keep any of the trace messages for 4-2-stable? master? Click on commit ba949ed to see the removed messages.
=> [#5496] Checksums are erased on overwrite of replica (4-2-stable)

plugins/api/src/get_file_descriptor_info.cpp, plugins/api/src/replica_close.cpp, plugins/api/src/replica_open.cpp, scripts/irods/test/test_istream.py
When replica_close is finalizing a newly created replica or a replica
which has been overwritten, sibling replicas should be marked as stale
because the newest replica reflects a potentially different truth from
that of the existing replicas. As part of this effort, replica_open has
been modified to handle failures from rs_get_file_descriptor_info a bit
more gracefully by unlocking the replica which was opened and unlinking
in the event that the open was meant for a create.
Add istream test for sibling replica marked stale on overwrite and
create.
Also makes sure that all exceptions in rs_get_file_descriptor_info are
caught.
---
CI tests are running.
=> [#5187][#5422] Stale sibling replicas on write (master)

lib/core/include/data_object_proxy.hpp, scripts/irods/test/test_ichksum.py, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjRename.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsDataObjTrim.cpp, server/api/src/rsDataObjUnlink.cpp, server/core/include/logical_locking.hpp, server/core/src/logical_locking.cpp, server/core/src/voting.cpp, unit_tests/src/test_logical_locking.cpp, unit_tests/src/test_replica_open_and_close.cpp
This passed CI tests except for 1 test which passes at the bench... and the failure doesn't seem... wrong, necessarily...
`irods.test.test_resource_types.Test_Resource_ReplicationToTwoCompoundResourcesWithPreferArchive.test_iget_with_purgec`
```
...
--- IrodsSession: icommand executed by [otherrods] [iput purgecgetfile.txt] --- 
Assert Command: iput purgecgetfile.txt
Expecting EMPTY: ['']
stdout:
| 
stderr:
| 
Output found
--- IrodsSession: icommand executed by [otherrods] [iget -f --purgec purgecgetfile.txt] --- 
Assert Command: iget -f --purgec purgecgetfile.txt
Expecting EMPTY: ['']
stdout:
| 
stderr:
| 
Output found
--- IrodsSession: icommand executed by [otherrods] [ils -L purgecgetfile.txt] --- 
Assert FAIL Command: ils -L purgecgetfile.txt
Expecting STDOUT_SINGLELINE: [' 0 ', …
```
=> [#5421] Enforce ILL in unlink/rename/trim (master)

scripts/irods/lib.py, scripts/irods/test/test_irepl.py, server/api/src/rsDataObjRepl.cpp
Do we want to erase the checksum if replication fails?
Right now, if a replication fails, the replica is marked as stale, but keeps the bad checksum.
=> [#5592] Added test for irepl (4-2-stable)

irods_consortium_continuous_integration_build_hook.py
This is required so that iRODS can be built in CI
=> Fixed nanodbc dependency in build hook (4-2-stable)

lib/api/include/data_object_finalize.h, plugins/api/src/atomic_apply_acl_operations.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, plugins/api/src/data_object_finalize.cpp, plugins/api/src/replica_close.cpp, scripts/irods/test/test_iadmin.py, server/api/src/rsBulkDataObjReg.cpp, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRename.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsDataObjUnlink.cpp, server/core/include/catalog_utilities.hpp, server/core/include/finalize_utilities.hpp, server/core/include/logical_locking.hpp, server/core/include/replica_state_table.hpp, server/core/src/catalog_utilities.cpp, server/core/src/finalize_utilities.cpp, server/core/src/initServer.cpp, server/core/src/logical_locking.cpp, server/core/src/replica_state_table.cpp, unit_tests/src/test_data_object_finalize.cpp
Adds 2 features to the data_object_finalize API plugin:
1. Checks permissions of the authenticated user to update system
metadata on the specified data object.
2. There are now a few immutable columns in r_data_main when attempting
to modify through this interface. These include the data_id,
data_name, and coll_id. These are logical level information which
should not be changed outside of a specific operation (e.g. rename).
---
=> [#4331] Bumpers for data_object_finalize (master)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iadmin.py
helps to distinguish between resource not being empty
=> [5545] send better error code when resource is in a hierarchy (4-2-stable)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iadmin.py
helps to distinguish between resource not being empty
=> [5545] send better error code when resource is in a hierarchy (master)

CMakeLists.txt
Cherry-pick of #5637 into stable.
This fixes the disappearing `/var` issue for master.
Related to #5220
=> [#5220] Fix makeinstall-time schema updating (4-2-stable)

CMakeLists.txt
This fixes the disappearing `/var` issue for master.
Related to #5220
=> [#5220] Fix makeinstall-time schema updating (master)

scripts/irods/test/test_federation.py, server/api/src/rsDataObjCopy.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPut.cpp, server/core/include/rodsConnect.h, server/core/src/objDesc.cpp, server/core/src/rodsConnect.cpp
Fixes several issues concerning federation (mostly parallel transfer related) which have occurred over time in master and 4-2-stable:
- `icp` does not need to resolve the resource hierarchy for the destination replica as this can be done in `rsDataObjOpen`. This logic was here mainly to uphold the `OVERWRITE_WITHOUT_FORCE_FLAG` rules for `icp`, but this is being handled earlier in the function and the deleted logic was only checking for existing replicas anyway.
- The `dataSize` parameter and `bytesWritten` are very touchy in `rsDataObjCopy` so I've put back a couple of these to more closely resemble how they were being set in the past. This mainly involves using the size of the data object for the source data object as the "expected" dataSize for the destination data object as well as …
=> Various fixes for federation (master)

packaging/core.re.template, scripts/irods/test/settings.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_icp.py, scripts/irods/test/test_iphymv.py, scripts/irods/test/test_irepl.py
shown to be enough to saturate a connection
defined in server_config.json as advanced_settings.default_number_of_transfer_threads
=> [5654] change default maximum threads to "default" (4-2-stable)

packaging/core.re.template, scripts/irods/test/settings.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_icp.py, scripts/irods/test/test_iphymv.py, scripts/irods/test/test_irepl.py
shown to be enough to saturate a connection
defined in server_config.json as advanced_settings.default_number_of_transfer_threads
=> [5654] change default maximum threads to "default", which is 4 (master)

plugins/api/src/atomic_apply_acl_operations.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, plugins/api/src/data_object_finalize.cpp, plugins/database/packaging/localhost_setup_mysql.input, server/core/include/catalog_utilities.hpp, server/core/src/catalog_utilities.cpp
- Verified that the atomic ACLs/Metadata API plugins work against Oracle.
- Verified that the data object finalize API plugin (using nanodbc) works against Oracle.
This needs to be run through CI.
=> Oracle support and Large IDs (4-2-stable)

server/api/src/rsDataObjOpen.cpp
When an operation requires that the connection be redirected to the
catalog consumer which owns the storage resource, the replica
information from the database operation to register the new replica in
the catalog is lost because the rsPhyPathReg interface has no way of
returning the information.
This change allows the logic for creating a new replica to detect the
situation in which the rsPhyPathReg call had to redirect to the catalog
provider and queries the database in order to retrieve the information
which was generated by the registration database operation.
---
CI tests for topology are currently running. Testing branch based on branch in #5680
=> [#5682] Query for missing replica info in create (4-2-stable)

scripts/irods/test/test_ichksum.py, scripts/irods/test/test_iphymv.py, scripts/irods/test/test_iput.py, scripts/irods/test/test_irepl.py, scripts/irods/test/test_iticket.py, scripts/irods/test/test_native_rule_engine_plugin.py, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRepl.cpp, server/core/src/irods_resource_redirect.cpp
Matches 4.2.8 behavior. Topology tests still running, but passed in CI for timing, unit, core, and federation tests.
=> [#5691] Relax usage of default resource for put (4-2-stable)

scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_all_rules.py, server/api/src/rsDataObjRead.cpp
in rsDataObjRead(), dataObjReadInp->len sometimes became negative
because `min<int>` casted  (dataSize - offset) without checking
that the rodsLong_t result would fit into the int (=int32) type, thus causing
no bytes ever to be read by a client for data object sizes greater
than 2 GB.
See https://github.com/irods/python-irodsclient/issues/280
=> limit chunking to integer size (4-2-stable)

plugins/api/src/data_object_finalize.cpp
In cases where the connected server is not the catalog service
provider, the call to the remote data_object_finalize should not attempt
to perform the file_modified operation, should it be requested in the
input. After the catalog has been updated in the CSP, the RPC should
return and the control should continue on the connected server to
execute the file_modified operation.
This change now explicitly turns off trigger_file_modified in the input
to the redirected call to data_object_finalize in order to only update
the catalog on the CSP (again, if it is not the connected server).
---
CI tests running. Will run tests in topology overnight.
=> [#5689] Limit redirection in data_object_finalize (4-2-stable)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_quotas.py
This is not the complete solution for #5733, but does eliminate the bulk of the warning messages in the database logs. This will still result in a warning message when checking the permissions for an object being finalized via ticket access when no update has occurred for the ticket, but this is a much more niche case than every single call to finalize.
Tests running now
=> [#5733] Only commit for tickets in check_permission_to_modify_data_object (master)

scripts/irods/test/test_iget.py, server/api/src/rsDataObjGet.cpp
This solution fixes #5723 for `iget` and Jargon 4.3.2.2-SNAPSHOT.
I'm not aware of any other clients experiencing this issue.
=> [#5723] rsDataObjGet sets output buffer size to zero for zero length data object (4-2-stable)

server/core/src/finalize_utilities.cpp
=> [#5744] Prevent use of non-existent L1 descriptor (4-2-stable)

scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_iget.py, scripts/irods/test/test_iput_options.py, server/api/src/rsDataObjOpen.cpp
CI tests passed, federation tests passed, confirmed that `test_delay_queue` is passing both connected to the catalog consumer and provider.
=> [#5760] Prevent staling replicas on open for read + test_delay_queue resilience (4-2-stable)

scripts/irods/lib.py, server/core/src/rodsServer.cpp
This PR attempts to keep the irodsctl script from killing iRODS processes inside of a container by introducing a PID file.
With the PID file, the irodsctl script can confidently determine if a process is a descendant or not.
=> [#5300] Server now creates PID file (master)

cmake/development_library.cmake, lib/filesystem/include/filesystem/filesystem.hpp, lib/filesystem/include/filesystem/object_status.hpp, lib/filesystem/include/filesystem/permissions.hpp, lib/filesystem/src/filesystem.cpp, server/core/include/scoped_permission.hpp, unit_tests/src/filesystem/test_filesystem.cpp
Allows operations to temporarily grant permissions on a collection or data
object for the duration of a scoped block.
=> Implemented new library: scoped_permission (master)

cmake/development_library.cmake, lib/filesystem/include/filesystem/filesystem.hpp, lib/filesystem/include/filesystem/object_status.hpp, lib/filesystem/include/filesystem/permissions.hpp, lib/filesystem/src/filesystem.cpp, server/core/include/scoped_permission.hpp, unit_tests/src/filesystem/test_filesystem.cpp
Allows operations to temporarily grant permissions on a collection or data
object for the duration of a scoped block.
=> Implemented new library: scoped_permission (4-2-stable)

CMakeLists.txt, server/api/src/rsPhyPathReg.cpp
In service of #4083
In libstdc++ 11, `#include <memory>` does not implicitly `#include <cstdlib>`, where `std::free( void* )` is found.
Also, I forgot to mark the `IrodsCXXCompiler` CMake module for installation.
=> [#4083] Install IrodsCXXCompiler CMake module and fix rsPhyPathReg.cpp includes

plugins/api/src/atomic_apply_acl_operations.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, plugins/api/src/data_object_finalize.cpp, plugins/api/src/touch.cpp, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_native_rule_engine_plugin.py, scripts/run_tests.py, server/api/src/rsRuleExecSubmit.cpp, server/core/include/catalog_utilities.hpp, server/core/include/rodsConnect.h, server/core/include/rsGlobalExtern.hpp, server/core/src/catalog_utilities.cpp
Setting up CSCs now works and have confirmed that no disconnection error messages appear in the CSP log when a CSC-connected agent goes away (meaning, the connections are now cleaning up appropriately).
=> Fix redirection logic and add hostname configuration to run_tests.py (master)

lib/core/include/stream_factory_utility.hpp, plugins/api/src/replica_close.cpp, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjPut.cpp, server/core/src/initServer.cpp, unit_tests/src/test_logical_locking.cpp, unit_tests/src/test_rc_data_obj.cpp, unit_tests/src/unit_test_utils.hpp
Historically, the mtime for a replica was only updated if it was opened
for write (that is, it must have already existed) and bytes were written
during the operation. This changes the logic such that any operation
that results in a create or a bytes-writing open-for-write will update
the mtime for the target replica. This means that the mtime and create
time for a new replica may not be equal.
___
=> [#5863] Update mtime for creates/non-empty writes (master)

lib/core/src/msParam.cpp, scripts/irods/test/test_all_rules.py
This PR also modifies `getStdoutInExecCmdOut()` so that it shares the same implementation as `getStderrInExecCmdOut()`.
=> [#5791] msiGetStderrInExecCmdOut() no longer segfaults on bad input (master)

lib/core/src/msParam.cpp, scripts/irods/test/test_all_rules.py
This PR also modifies `getStdoutInExecCmdOut()` so that it shares the same implementation as `getStderrInExecCmdOut()`.
=> [#5791] msiGetStderrInExecCmdOut() no longer segfaults on bad input (4-2-stable)

lib/core/src/sslSockComm.cpp, plugins/network/ssl/libssl.cpp
Add SNI support to outgoing irods connections. This makes icommands and
irods behave as the python client and jargon applications such as
metalnx. It allows for advanced proxy setups.
Signed-off-by: Peter Verraedt <peter.verraedt@kuleuven.be>
=> Support SNI when connecting to remote irods server

lib/core/src/sslSockComm.cpp, plugins/network/ssl/libssl.cpp
Add SNI support to outgoing irods connections. This makes icommands and
irods behave as the python client and jargon applications such as
metalnx. It allows for advanced proxy setups.
Signed-off-by: Peter Verraedt <peter.verraedt@kuleuven.be>
=> [#5832] Support SNI when connecting to remote irods server

unit_tests/cmake/test_config/irods_client_server_negotiation.cmake
Found this while trying to track down a different issue
=> [5828] Add fmt irods-externals include dir to client_server_negotiation test

CMakeLists.txt, cmake/development_library.cmake, lib/core/include/rodsErrorTable.h, plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iadmin.py, server/api/src/rsGeneralAdmin.cpp, server/core/include/atomic_apply_database_operations.hpp, server/core/include/catalog.hpp, server/core/src/atomic_apply_database_operations.cpp, server/core/src/catalog.cpp
This new function executes multiple database operations under a single
transaction.
The following SQL operations are supported:
- insert
- update
- delete
The following tables are supported:
- r_data_main
- r_coll_main
- r_meta_main
- r_objt_metamap
- r_resc_main
See https://github.com/irods/irods/pull/5485 for additional comments regarding this work.
=> [#5324] Implemented atomic database operations function (main)

server/api/src/rsGeneralAdmin.cpp, server/api/src/rsUserAdmin.cpp, server/core/include/administration_utilities.hpp, server/core/src/administration_utilities.cpp
The zone name can now be provided via argument in the GeneralAdmin API
as well as the UserAdmin API. This is done to support clients which
provide the argument. iadmin will provide the desired zone name through
the octothorpe-delimited method.
---
CI tests running. cherry-picked from work for #6015
=> [#4231] Restore support for zone name param in admin API (master)

server/api/src/rsGeneralAdmin.cpp, server/api/src/rsUserAdmin.cpp, server/core/include/administration_utilities.hpp, server/core/src/administration_utilities.cpp
The zone name can now be provided via argument in the GeneralAdmin API
as well as the UserAdmin API. This is done to support clients which
provide the argument. iadmin will provide the desired zone name through
the octothorpe-delimited method.
---
CI tests passed. The PRC tests which began to fail are now passing at the bench.
I started to add unit tests for this API but didn't find it to be particularly beneficial at this time. Please let me know if we want to add a unit test for the APIs.
=> [#4231] Restore support for zone name param in admin API (4-2-stable)

cmake/development_library.cmake, lib/core/include/capped_memory_resource.hpp, lib/core/include/fixed_buffer_resource.hpp, server/core/include/irods_delay_queue.hpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_capped_memory_resource.cmake, unit_tests/src/test_capped_memory_resource.cpp, unit_tests/src/test_fixed_buffer_resource.cpp, unit_tests/unit_tests_list.json
A unit test for `capped_memory_resource` is in the works for this PR.
This PR resolves several issues with `fixed_buffer_resource` and Boost.Container. The changes are required for 4-2-stable as well. Once this PR is complete, the changes introduced here will be ported to 4-2-stable.
=> Undefined behavior / Memory Alignment / Boost.Container bug non-intrusive solution (main)

plugins/resources/univmss/libunivmss.cpp
I had trouble with white spaces in filenames when syncing to archive. This should fix it until someone has filenames with single quotes in it.
=> added missing single quotes in univmss/syncToArch

packaging/irods
prevents a non-zero return value when the file does not exist
=> [6053] more graceful stop when server already stopped (4-2-stable)

plugins/resources/compound/libcompound.cpp, scripts/irods/test/test_resource_types.py, server/api/src/rsDataObjClose.cpp
=> [#6089] Prevent checksums on archive replicas (4-2-stable)

scripts/irods/database_connect.py, scripts/irods/lib.py, scripts/irods/test/resource_suite.py, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_chunkydevtest.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_ichksum.py, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_icp.py, scripts/irods/test/test_imeta_interactive.py, scripts/irods/test/test_iphymv.py, scripts/irods/test/test_iput_options.py, scripts/irods/test/test_irepl.py, scripts/irods/test/test_irsync.py, scripts/irods/test/test_iscan.py, scripts/irods/test/test_iticket.py, scripts/irods/test/test_izonereport.py, scripts/irods/test/test_misc.py, scripts/irods/test/test_native_rule_engine_plugin.py, scripts/irods/test/test_resource_configuration.py, scripts/irods/test/test_resource_types.py, scripts/irods/test/test_rule_engine_plugin_framework.py, scripts/irods/test/test_rule_engine_plugin_passthrough.py, scripts/irods/test/test_rulebase.py, scripts/irods/test/test_symlink_operations.py, scripts/irods/test/timing_tests.py
All tests passed. A good chunk of the change was moving some calls in the `setUp()` method of one of the test classes to reduce the amount of work done for other test cases.
=> [#6114] Make (almost) all tests in main pass (main)

scripts/irods/test/test_all_rules.py
Use the `six` module's portable metaclass syntax (instead of \_\_metaclass\_\_ which won't work starting in Python3). More importantly we use `-r` in irule invocations to guarantee a nonzero rule code causes the tests generated from rule file directories to return the appropriate pass / fail status to the testing framework. We target:
- native plugin instance for the [icommands rulefiles](https://github.com/irods/irods_client_icommands/tree/4-2-stable/test/rules), and
- Python  plugin instance for the   Python rule plugin [rule files](https://github.com/irods/irods_rule_engine_plugin_python/tree/4-2-stable/python_rules)
=> [_6169] updates for metaclass, test generation (4-2-stable)

scripts/irods/test/test_all_rules.py
=> [6169] updates for metaclass, test generation (main)

scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_rulebase.py, server/api/src/rsExecMyRule.cpp, server/core/src/rodsConnect.cpp
cherry-picked from work for #6243 
Test suite running now
=> [#4260] Enforce valid hostname for remote rule execution (4-2-stable)

scripts/setup_irods.py
I've only been able to partially test the code in its current form as I solved the problem with one change and then retrospectively fixed some issues in the script. I don't have multiple test environments to test with. 
The existing code had issues if the proposed irods service group was defined externally (to the /etc/group file) e.g. via Active Directory binding.
In the setup_service_account function, 'grp.getgrall()' was used to find all groups in /etc/group and if the new service account group did not appear, it would be created with a system call to 'groupadd -r <irods_group>'. If the group in question did indeed exist, but in an external authentication system, then it would throw an exception and terminate.
I've proposed a change that wraps the group creation command in an …
=> Handling of federated groups

lib/core/include/irods/irods_logger.tpp, scripts/irods/log.py
I'm not sure we actually need this, but we can discuss how important/useful this is here.
This needs to be ran through the test suite.
=> [#3602] Timestamps in python log output are now displayed in UTC time (main)

scripts/irods/lib.py, scripts/setup_irods.py
Instead of raising an IrodsError with the stderr contents, we should
handle the error case as we would with something that was executed using
execute_command. This provides more context for the error that occurred
for investigation for failures.
related to #6245 and #6280
=> [#858] Fix up error handling in setup_service_account (main)

lib/core/src/irods_gsi_object.cpp, lib/core/src/irods_krb_object.cpp
In the event that an auth object fails to resolve an auth plugin
interface, it may be the case that the plugin hasn't been loaded yet.
The failure should indicate that an attempt to load the plugin should be
made before returning an error. On success, a resolved plugin interface
will be returned and the resolution will be considered successful.
Confirmed fix by hand for Kerberos. GSI has been nearly identical for all time so the fixes were applied there as well.
=> [#3727] Fix auth objects resolving/loading plugins (main)

server/delay_server/src/irodsDelayServer.cpp
When a rule in the queue is not found in the catalog for whatever
reason, it should be removed from the delay queue without doing any
additional work. This can happen due to a timing issue wherein the delay
server fetches work from the catalog that is currently being done and
then place it back on the queue after it has been removed. This is
normal and a side effect of the asynchronous producer-consumers model
employed by the delay server.
---
Tests cannot run yet due to changes in the setup script and upcoming changes to configuration files. I will confirm once these issues are resolved in the testing environment. Until then, this will be considered WIP.
=> [#6232] Dequeue delay rules not found in catalog (main)

CMakeLists.txt
Addresses #6192 and friends for this repo.
=> [#6192] Ignore python byte compilaiton failures when packaging RPMs (4-2-stable)

scripts/irods/test/test_prep_genquery_iterator.py
With this commit, in addition to the following one in
https://github.com/irods/irods_rule_engine_plugin_python/pull/114:
fix Query.copy: in python3, dict.items() no longer produces a list  79f471c
all tests in test_prep_genquery_iterator now pass on Py3 / iRODS 4.3
=> correct 'offset_limit_' subtest in test_query_objects

scripts/irods/test/resource_suite.py, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_iqmod.py, scripts/irods/test/test_misc.py, scripts/irods/test/test_rulebase.py
related to #5927 within class `irods.test.test_all_rules.Test_msiDataObjRepl_checksum_keywords`.
These tests are related to issue #5927 and are apparently failing for main branch whereas they are not failing for 4-2-stable (@alanking)
=> [#6320] for PREP, adapt test user for 6 tests, skip others ... (main)

scripts/irods/test/test_all_rules.py, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_isysmeta.py
lack of Python2 compatibility (for metaclass and print function) were causing RPM bytecompiling to trip over some test related scripts.
=> [#6334] Python2-syntax compat. for RPM byte-compile on centos7

lib/core/include/irods/authentication_plugin_framework.hpp, lib/core/src/clientLogin.cpp, lib/core/src/obf.cpp, plugins/api/src/authenticate.cpp, plugins/auth/CMakeLists.txt, plugins/auth/src/native.cpp, plugins/auth/src/pam.cpp
I'm going to leave this in draft for now as this is still being tested.
Currently, the name of this plugin is "pam". We have discussed using "pam_password" for this as the "interactive" PAM plugin being developed in the Authentication Working Group will completely replace this later, and the existing implementation is a simple password verification.
Also up for discussion: Should this be a separate plugin which exists outside of the main server?
=> Add legacy PAM plugin with new authentication plugin framework (main)

lib/core/include/irods/authentication_plugin_framework.hpp, lib/core/src/clientLogin.cpp, lib/core/src/getRodsEnv.cpp, lib/core/src/irods_server_properties.cpp, plugins/auth/src/native.cpp, plugins/auth/src/pam.cpp, scripts/core_tests_list.json, scripts/irods/test/resource_suite.py, scripts/irods/test/session.py, scripts/irods/test/test_auth.py
Companion PR: https://github.com/irods/irods_client_icommands/pull/300
Two commits in the middle seem contradictory because they are. I wasn't sure if we wanted to support the password keyword in the pam_password plugin or not. I think this is only being used by `iinit` and that support is being removed in the referenced issue, #6382... but just in case I left support for it there.
Should we support the password key in the request message to the PAM plugin? If so, I will squash the two commits referencing #6382. If not, I will delete the second commit.
Still need to run through tests, but works when tested by hand
=> Various authentication plugin fixes (main)

plugins/database/src/db_plugin.cpp, scripts/irods/lib.py, scripts/irods/test/test_ichmod.py
This will allow all access permissions from icatDefines.h to be used when setting permissions. Since 'write' and 'read' are still valid as permission, this will be fully backward compatible.
I had some doubt about the spaces in access permission names, but it feels a bit silly to translate them all to new names without spaces. So I left them as they are.
This will work with all clients that depend on the irods api to check if a specified access permission is valid. Tested with ichmod, msiSetAcl, and the python-irodsclient.
Example usage: `ichmod "modify metadata" 'user1' /tempZone/data`
Resolves irods/irods#844
=> allow all access levels from icatDefines.h

scripts/irods/test/test_iadmin.py, scripts/irods/test/test_misc.py
Confirmed that killing delay server and killing agent factory do not result in killing the main server or leaked processes, respectively. Confirmed that modified test passes in testing environment, but I'm running it through the whole gauntlet just in case it raises issues in the run up to release.
=> [#6116][#6117] Fortify process spawner test (main)

.gitignore, lib/core/CMakeLists.txt, lib/core/include/irods/irods_server_properties.hpp, lib/core/include/irods/json_events.hpp, lib/core/src/irods_server_properties.cpp, lib/core/src/json_events.cpp, plugins/microservices/CMakeLists.txt, plugins/microservices/src/get_server_property.cpp, scripts/core_tests_list.json, scripts/irods/controller.py, scripts/irods/test/test_configuration_reload.py, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_icommands_file_operations.py, server/delay_server/src/irodsDelayServer.cpp, server/main_server/src/main_server_control_plane.cpp, server/main_server/src/rodsServer.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_json_events.cmake, unit_tests/src/test_json_events.cpp, unit_tests/src/test_server_properties.cpp, unit_tests/unit_tests_list.json
This is meant to address the need for a configuration reload facility in iRODS. 
It seems like this will lead to ongoing projects to bring its capabilities up to expected:
* handling auth changes
* making the delay server able to adjust the number of workers
Then there are fun questions here that need testing, such as changing delay server executors(the remote ones) which may or may not need additional changes to work properly.
There's probably more I'm not thinking about of course, and there is of course the positively terrifying possibility of adding an `msi_set_server_property()` microservice.
But primarily, this introduces the configuration reloading to the code and attempts to provide a facility that permits it to notify structures of settings changing in a relatively extensible …
=> Configuration reload [#5821] 

lib/core/include/irods/rodsErrorTable.h, server/core/src/miscServerFunct.cpp
This replaces the old popen code with the much more concise and modern feeling boost::process. This addresses #6273
=> Reimplement get_script_output_single_line with boost::process

cmake/Modules/UseLibCXX.cmake
=> [#6511] UseLibCXX: Fix LINK_LANGUAGE version guard (4-2-stable)

lib/core/src/irods_server_properties.cpp, scripts/irods/test/test_configuration_reload.py, server/control_plane/include/irods/irods_server_control_plane.hpp, server/irods_grid/src/irods-grid.cpp, server/main_server/src/main_server_control_plane.cpp
Adding support to trigging the configuration reload to
the control plane enables easier use in clusters or
multiple instance setups.
The current command doesn't support any options other than
the standard ones, and thus is invoked like
"irods-grid reload"
=> [6529] Remote configuration reload

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/functions.cpp, scripts/irods/test/test_rule_engine_plugin_framework.py
Includes tests, which are written for the Python RE plugin suite
and append the NREP to test behavior with multiple rule engine plugins
loaded.
=> [_6465] allow NREP remote execution hints to target INST_NAME (4-2-stable)

lib/core/include/irods/irods_error.hpp
=> [#6580] Silence clang-tidy array decay checks for error macros (main)

lib/core/include/irods/irods_error.hpp
Addresses #6580 for 4-3-stable
=> [#6580] Silence clang-tidy array decay checks for error macros (4-3-stable)

lib/core/include/irods_at_scope_exit.hpp
=> [#6477] Adjusted at_scope_exit implementation and provided unsafe version as an opt-in (4-2-stable)

plugins/resources/CMakeLists.txt, plugins/resources/unixfilesystem/CMakeLists.txt, plugins/resources/unixfilesystem/include/irods/private/irods_is_in_host_list.hpp, plugins/resources/unixfilesystem/src/irods_is_in_host_list.cpp, plugins/resources/unixfilesystem/src/unixfilesystem.cpp, scripts/irods/paths.py, scripts/irods/test/test_resource_types.py, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_host_list_context_string.cmake, unit_tests/src/test_host_list_context_string.cpp
Adding detached mode for unixfilesystem resources.
Notes:
1. Right now, all servers in the zone would have to have a mount at the same location, as the location of the vault path is not server dependent.
2. If we wanted to limit the servers which can serve the request, we could add some type of list in the context string meaning only the servers in the list can serve it.
3. If we really wanted to make it configurable, the list from 2 could have two parts - the server name and the vault path.
For 3 we could do something like:
```"HOST_MODE=detached;SERVER_LIST=server1.irods.org:/lustre_mount/resource1,server2.irods.org:/mounts/lustre_mount/resource1"```
in the context string.
I haven't researched this fully to determine if it is possible or could be done efficiently.  Just throwing it out …
=> [4421] Added detached mode for unixfilesystem resource (main)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_ichmod.py, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_native_rule_engine_plugin.py
User should now _not_ be able to `ichmod` data objects and collections back to `own`, after setting to a lower permission.
=> [6579] Fix `ichmod` permission bypass (main)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_ichmod.py, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_native_rule_engine_plugin.py
User should now not be able to `ichmod` data objects and collections back to `own`, after setting to a lower permission.
=> [#6579] Fix `ichmod` permission bypass (4-3-stable)

unit_tests/src/test_delay_hints_parser.cpp
It seems that for some `DOUBLE` directive tests, we were using the same string object passed to string views. This meant that when we set the expected results string, we also modified the input string. This may have been causing the non-deterministic results.
=> [#5964] Correct `DOUBLE` directive tests (main)

unit_tests/src/filesystem/test_filesystem.cpp
Fix unit test relying on previous `ichmod` behavior by adding admin command where old behavior is expected.
=> [#6579] Mimic old `ichmod` behavior in filesystem unit test (main)

unit_tests/src/test_delay_hints_parser.cpp
It seems that for some DOUBLE directive tests, we were using the same string object passed to string views. This meant that when we set the expected results string, we also modified the input string. This may have been causing the non-deterministic results.
=> [5964] Correct DOUBLE directive unit tests (4-3-stable)

unit_tests/src/filesystem/test_filesystem.cpp
Fix unit test relying on previous ichmod behavior by adding admin command where old behavior is expected.
=> [#6579] Mimic old ichmod behavior in filesystem unit test (4-3-stable)

unit_tests/src/test_packstruct.cpp
=> [#6645] Fixed memory leak in PackStruct unit test (4-2-stable)

lib/api/include/irods/apiTable.hpp, lib/api/include/irods/simpleQuery.h, lib/api/src/rcSimpleQuery.cpp, lib/core/include/irods/rodsErrorTable.h, server/api/include/irods/rsSimpleQuery.hpp, server/api/src/rsSimpleQuery.cpp
This change deprecates the use of SimpleQuery as well as its client API endpoint and server-side shortcut API.
---
The deprecated functions are no longer being used, so I didn't run the test suite.
=> [#6638] Deprecate SimpleQuery (main)

server/core/src/objDesc.cpp
closeAllL1desc is (only) called from a forked process which is preparing to execute an external program.  It should not do anything other than close the open resources. See issue #6622.
Applies to main, 4-3-stable, 4-2-stable.
=> [#6622]  closeAllL1desc should not call PEPs

plugins/database/src/mysql_functions.sql.in
The mysql function R_ObjectId_nextval() is not safe for parallel database updates, that some of our users can trigger by opening a large number of parallel connections. This can be simulated by
```
(for i in $(seq 0 10); do echo 'echo "SELECT R_ObjectID_nextval();" |
mysql -h (...) -u(...) -p(...) irods'; done) | parallel -j 10
```
This results in "Deadlock found when trying to get lock; try restarting transaction". After restricting the delete to only remove the row that that instance of the function has inserted, the deadlock is avoided.
Signed-off-by: Peter Verraedt <peter.verraedt@kuleuven.be>
=> Add where clause in delete from R_ObjectId_seq_tbl (main)

lib/api/include/irods/apiNumberData.h, lib/api/include/irods/apiTable.hpp, lib/api/include/irods/simpleQuery.h, plugins/database/src/db_plugin.cpp, server/api/src/rsSimpleQuery.cpp, server/core/include/irods/irods_api_calling_functions.hpp, server/core/include/irods/irods_database_constants.hpp, server/core/src/irods_api_calling_functions.cpp, server/icat/include/irods/icatHighLevelRoutines.hpp
Addresses #6638 (the rest of it)
Follow-up to #6657 
Just left a comment for the API number, but the rest has now received a deprecation attribute. Had to wrap some bits to ignore the deprecated declarations warnings that are now generated.
=> [#6638] SimpleQuery: Deprecate types, constants, and functions (main)

scripts/irods/test/test_misc.py, server/core/src/irods_server_negotiation.cpp
Populate rule execution information object with additional information from rsComm for use in acPreConnect.
=> [#5985] Provide client info in acPreConnect (4-3-stable)

lib/administration/resource/include/irods/resource_administration.hpp, lib/administration/resource/src/resource_administration.cpp, unit_tests/cmake/test_config/irods_filesystem.cmake, unit_tests/cmake/test_config/irods_resource_administration.cmake, unit_tests/cmake/test_config/irods_zone_report.cmake, unit_tests/src/filesystem/test_filesystem.cpp, unit_tests/src/test_data_object_finalize.cpp, unit_tests/src/test_logical_locking.cpp, unit_tests/src/test_parallel_transfer_engine.cpp, unit_tests/src/test_replica.cpp, unit_tests/src/test_resource_administration.cpp, unit_tests/src/test_zone_report.cpp, unit_tests/src/unit_test_utils.hpp
All unit tests passed.
~Running core tests.~
We can skip running the core tests because nothing in the server outside of unit tests use the resource administration library.
=> [#6619] Refactored resource administration lib to prefer exceptions (main)

scripts/irods/test/test_auth.py
Addresses #6693 
Requires irods/irods_testing_environment#132 in order for tests to pass
=> [#6693] test_auth: Newer OpenSSL requires 2048 numbits (main)

lib/administration/user/CMakeLists.txt, lib/administration/user/include/irods/user_administration.hpp, lib/administration/user/src/detail.cpp, lib/administration/user/src/user_administration.cpp, lib/administration/user/src/utilities.cpp, lib/api/include/irods/generalAdmin.h, unit_tests/cmake/test_config/irods_atomic_apply_acl_operations.cmake, unit_tests/cmake/test_config/irods_user_administration.cmake, unit_tests/src/test_rc_switch_user.cpp, unit_tests/src/test_ticket_administration.cpp, unit_tests/src/test_user_administration.cpp
All unit tests pass.
Nothing other than the unit tests and the switch user api plugin uses this library so I don't think core tests need to be run for this.
I'm considering changing more components of the library as well.
TODOs:
=> Refactored user administration library to throw exceptions (main)

server/core/src/client_api_whitelist.cpp, unit_tests/src/test_resource_administration.cpp, unit_tests/src/test_zone_report.cpp
These changes are trivial and don't require a full run of the test suites. I
I think compiling and executing an icommand to verify things work is acceptable. On top of that, I'll run the unit tests to make sure things are in order.
=> gethostname and client_api_whitelist (4-2-stable)

scripts/irods/test/test_auth.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_native_rule_engine_plugin.py, scripts/irods/test/test_quotas.py, scripts/irods/test/test_resource_types.py, scripts/irods/test/test_rule_engine_plugin_framework.py, scripts/irods/test/test_rulebase.py
The `time.sleep(...)` calls are safe to remove, however, the `import time`s are still used by other functions, so imports will remain.
Comments on removing `import time` are removed to avoid confusion in the future.
=> [2279] Remove unneeded sleep calls, leave imports for other functions (main)

lib/api/include/atomic_apply_acl_operations.h, plugins/api/src/atomic_apply_acl_operations.cpp, server/api/include/rs_atomic_apply_acl_operations.hpp, unit_tests/src/test_atomic_apply_acl_operations.cpp
Unit tests for this API plugin passed.
Nothing in the server uses this API plugin so it's safe to merge based on unit test results alone.
=> [#6198] Added admin_mode option to rx_atomic_apply_acl_operations() (4-2-stable)

lib/api/include/irods/atomic_apply_acl_operations.h, plugins/api/src/atomic_apply_acl_operations.cpp, server/api/include/irods/rs_atomic_apply_acl_operations.hpp, unit_tests/src/test_atomic_apply_acl_operations.cpp
Ported from #6779.
All unit tests for this API plugin passed.
Nothing in the server uses this API plugin so it's safe to merge based on unit test results alone.
=> [#6198] Added admin_mode option to rx_atomic_apply_acl_operations() (main)

lib/api/include/irods/atomic_apply_acl_operations.h, plugins/api/src/atomic_apply_acl_operations.cpp, server/api/include/irods/rs_atomic_apply_acl_operations.hpp, unit_tests/src/test_atomic_apply_acl_operations.cpp
Ported from #6779.
Cherry-picked from #6788.
All unit tests for this API plugin passed.
Nothing in the server uses this API plugin so it's safe to merge based on unit test results alone.
=> [#6198] Added admin_mode option to rx_atomic_apply_acl_operations() (4-3-stable)

plugins/api/src/get_file_descriptor_info.cpp, server/core/include/objDesc.hpp, server/core/src/finalize_utilities.cpp, server/core/src/objDesc.cpp
All unit tests passed.
Will run the core tests soon.
=> [#6754] Deprecated member variables of the `l1desc` data type (4-2-stable)

plugins/api/src/get_file_descriptor_info.cpp, server/core/include/irods/objDesc.hpp, server/core/src/finalize_utilities.cpp, server/core/src/objDesc.cpp
Ported from #6793.
Will run unit tests and core tests soon.
=> [#6754] Deprecated member variables of the l1desc data type (main)

plugins/api/src/get_file_descriptor_info.cpp, server/core/include/irods/objDesc.hpp, server/core/src/finalize_utilities.cpp, server/core/src/objDesc.cpp
Cherry-picked from #6797.
Will run unit tests before adding the pound.
=> [#6754] Deprecated member variables of the l1desc data type (4-3-stable)

plugins/database/src/mid_level_routines.cpp, scripts/irods/test/test_iticket.py
Ported from #6798.
Will run unit tests and core tests soon.
=> [#5913] Restored ability to create data objects using write tickets (4-2-stable)

server/main_server/src/rodsServer.cpp
=> [#6820] Removed preprocessor logic around signal handler (4-3-stable)

CMakeLists.txt, cmake/development_library.cmake, lib/api/include/get_delay_rule_info.h, lib/api/include/ruleExecDel.h, lib/api/src/rc_get_delay_rule_info.cpp, plugins/api/CMakeLists.txt, plugins/api/include/api_plugin_number_data.h, plugins/api/src/get_delay_rule_info.cpp, plugins/api/src/touch.cpp, plugins/database/CMakeLists.txt, plugins/database/src/db_plugin.cpp, scripts/irods/lib.py, scripts/irods/test/session.py, scripts/irods/test/test_federation.py, scripts/manual_cleanup.py, server/api/include/rsRuleExecDel.hpp, server/api/include/rs_get_delay_rule_info.hpp, server/api/src/rsRuleExecDel.cpp, server/api/src/rs_get_delay_rule_info.cpp, server/core/include/irods_database_constants.hpp, server/core/src/irodsReServer.cpp, server/icat/include/icatHighLevelRoutines.hpp, server/icat/src/icatHighLevelRoutines.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_get_delay_rule_info.cmake, unit_tests/src/test_get_delay_rule_info.cpp, unit_tests/unit_tests_list.json
This has not been tested and is still a work in progress.
=> [#6482] Deleting a delay rule now verifies zone of the connected client (4-2-stable)

.clang-tidy, .github/workflows/linter-irods-clang-tidy.yml, server/api/src/rsDataObjCopy.cpp, server/api/src/rsModColl.cpp, server/core/include/irods/catalog_utilities.hpp, server/core/src/catalog_utilities.cpp
Addresses https://github.com/irods/irods/issues/6842
In service of https://github.com/irods/irods/issues/6527
Related to https://github.com/irods/irods/pull/6840
Cherry-picked from #6844 
clang-tidy complaint is invalid. See https://github.com/irods/irods/pull/6844#discussion_r1081727761
=> Fix federation test failure, avoid collection mtime update in copy, adjust clang-tidy (4-3-stable)

scripts/irods/test/test_irm.py
Fixes timing issue in #6428
Cherry-picked from #6840
=> [#6428] Add sleep to irm test for collection mtime update (main)

scripts/irods/test/test_irm.py
Fixes timing issue in https://github.com/irods/irods/issues/6428
Cherry-picked from https://github.com/irods/irods/pull/6840
=> [#6428] Add sleep to irm test for collection mtime update (4-3-stable)

lib/core/include/irods/irods_server_properties.hpp, plugins/microservices/src/get_server_property.cpp, server/core/src/catalog.cpp, server/core/src/client_api_allowlist.cpp, server/delay_server/src/irodsDelayServer.cpp, server/harness/src/irods_configuration_test_harness.cpp, server/main_server/src/main_server_control_plane.cpp, server/main_server/src/rodsServer.cpp, unit_tests/src/test_server_properties.cpp
Make `server_properties::map()` thread-safe and read-only, allowing for safe access to internal JSON object.
=> [6726] Make `server_properties::map()` thread-safe and read-only

lib/core/include/irods/irods_server_properties.hpp, plugins/microservices/src/get_server_property.cpp, server/core/src/catalog.cpp, server/core/src/client_api_allowlist.cpp, server/delay_server/src/irodsDelayServer.cpp, server/harness/src/irods_configuration_test_harness.cpp, server/main_server/src/main_server_control_plane.cpp, server/main_server/src/rodsServer.cpp, unit_tests/src/test_server_properties.cpp
Cherry-pick from main to 4-3-stable.
=> [6726] Make server_properties::map() thread-safe and read-only (4-3-stable)

lib/core/include/irods/key_value_proxy.hpp, plugins/api/src/replica_close.cpp, plugins/resources/src/compound.cpp, scripts/irods/test/test_resource_types.py, server/api/src/rsDataObjPut.cpp, server/core/src/initServer.cpp, server/core/src/rodsAgent.cpp, unit_tests/cmake/test_config/irods_key_value_proxy.cmake, unit_tests/src/test_replica_access_table.cpp
Addresses #6154
Addresses #6378
Addresses #6479
Addresses #6880
Addresses #6882
Companion PR: https://github.com/irods/irods_resource_plugin_s3/pull/2094
The issues being addressed here are difficult to reproduce in the automated tests. I have some machinery for this in a separate branch which we can consider merging at another time. Tests for these things are in the companion PR.
Will run core tests soon, hence the draft PR.
=> Ensure that data objects cannot get stuck in locked status (main)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_imeta_set.py
Separate collections with similar AVUs should be able to be set their AVUs without errors.
=> [4063] Ensure AVUs set properly (4-2-stable)

lib/core/include/key_value_proxy.hpp, plugins/api/src/replica_close.cpp, plugins/resources/compound/libcompound.cpp, scripts/irods/test/test_resource_types.py, server/api/src/rsDataObjPut.cpp, server/core/src/initServer.cpp, server/core/src/rodsAgent.cpp, unit_tests/cmake/test_config/irods_key_value_proxy.cmake, unit_tests/cmake/test_config/irods_re_serialization.cmake, unit_tests/src/test_replica_access_table.cpp
Addresses https://github.com/irods/irods/issues/6154
Addresses https://github.com/irods/irods/issues/6378
Addresses https://github.com/irods/irods/issues/6479
Addresses https://github.com/irods/irods/issues/6880
Addresses https://github.com/irods/irods/issues/6882
Addresses https://github.com/irods/irods/issues/6886
Companion PR: https://github.com/irods/irods_resource_plugin_s3/pull/2097
Cherry-picked from https://github.com/irods/irods/pull/6884
Core tests are running now. Need to make sure S3 plugin tests pass before merging
There are some differences between this branch and main/4-3-stable. Specifically, the agent cleanup logic is in a completely different file, so the cherry-pick was rather manual in that part. Please review the first (that is, earliest/base) commit carefully.
=> Ensure that data objects cannot get stuck in locked status (4-2-stable)

plugins/rule_engines/irods_rule_language/src/nre.reLib1.cpp
=> [6743] nre.reLib1.cpp:extractVarNames: do not write past the end of varNames (main)

plugins/rule_engines/irods_rule_language/src/nre.reLib1.cpp
Addresses #6743 for 4-2-stable
=> [6743] nre.reLib1.cpp:extractVarNames: do not write past the end of varNames (4-3-stable)

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/nre.reLib1.cpp
Addresses #6743 for 4-2-stable
=> [6743] nre.reLib1.cpp:extractVarNames: do not write past the end of varNames (4-2-stable)

scripts/core_tests_list.json, scripts/irods/database_upgrade.py, scripts/irods/test/test_specific_queries.py, version.json.dist.in
This PR has not been tested.
Notice the bump to the database schema version and the importing of the unittest python module.
=> [#6900] Restored specific query, DataObjInCollReCur, for MySQL 8 (main)

scripts/core_tests_list.json
This was my oversight, which luckily @alanking [caught](https://github.com/irods/irods/pull/6941#pullrequestreview-1317718866), but - as it's after the merge of the [PR](https://github.com/irods/irods/pull/6859) containing the test itself ,  here it is now, as a supplemental PR.  There will be no corresponding pull request for `main` and `4-3-stable`, as the commit contained here will be immediately cherry picked to those branches.
=> add test_iqstat to list of core tests (4-2-stable)

scripts/irods/test/test_quotas.py
`istream` attempts to write bytes to a data object using `rcDataObjWrite`.
Given that the PRC uses the stream operations, this update to the quota test should be enough to make sure we don't introduce any regressions around quotas and writing bytes.
=> [#3513] Added use of istream to quota test case (main)

scripts/irods/test/test_quotas.py
Thinking about this more, I wonder if the call to `rxDataObjOpen` is failing rather than the call to `rxDataObjWrite`.
I'm not sure we can do more for the issue without jumping through hoops because the quota isn't updated as the bytes are written.
To verify if the write operation respects the quota, we'd need to open the data object and then wait for the quota to be exceeded before executing the write operation. Doing that is difficult to do from within the python tests. Doing that from C++ is also difficult due to the lack of tools which allow modifying the server's configuration.
At the very least, we know that this test change increases coverage around quota enforcement.
=> [#3513] Added use of istream to quota test case (4-2-stable)

scripts/irods/test/test_iquest.py, server/api/src/rsGenQuery.cpp
Addresses #6912 
Unit tests and core tests are passing
Please view this with an eye for optimization. I couldn't come up with any way to avoid some of these copies in a timely fashion :)
=> [#6912] GenQuery: Add support for || with DATA_RESC_HIER (main)

scripts/irods/test/test_iquest.py, server/api/src/rsGenQuery.cpp
Addresses #6912
Cherry-picked from https://github.com/irods/irods/pull/6955
=> [#6912] GenQuery: Add support for || with DATA_RESC_HIER (4-3-stable)

packaging/core.re.template, plugins/resources/compound/libcompound.cpp, plugins/resources/mockarchive/libmockarchive.cpp, scripts/irods/lib.py, scripts/irods/test/test_resource_types.py
Changed the compound behavior as follows:
If the policy is set to prefer the cache and the cache votes .25 (irc::vote::low) or less, get the vote from the archive.  If its vote is higher, repave the cache with the archive and return this.
If the cache votes > .25 then return the file from the cache.
Some situations where the vote is <= .25:
1. The replica does not exist in the cache.  (vote=0.0)
2. The replica exists but it stale.  (vote=.25)
3. The user requested a specific replica.  (vote=.25)
I have a test in the S3 plugin which covers this scenario with the archive file being in Glacier.
=> [6502] mark replica stale if staging to cache fails (4-2-stable)

plugins/database/src/db_plugin.cpp
Improve `imkdir` performance in the case of inheritance by using a subquery in an `UPDATE` statement.
By using a subquery, the planner utilizes an index scan (when optimal) compared to a sequence scan.
The following snippet was produced by creating 10k collections, which has a parent collection with inheritance enabled, before using `EXPLAIN` to estimate the costs of the statements. The first statement is the original, with the second being the new version.
```
ICAT=# EXPLAIN update R_COLL_MAIN set coll_inheritance=12, modify_ts=12 where coll_id=currval('R_ObjectID');
QUERY PLAN                              
---------------------------------------------------------------------
Update on r_coll_main  (cost=0.00..364.79 rows=1 width=713)
->  Seq Scan on r_coll_main  (cost=0.00..364.79 …
```
=> [6495] Improve imkdir inheritance performance (4-2-stable)

CMakeLists.txt, cmake/development_library.cmake, lib/core/include/irods_service_account.hpp, lib/core/src/irods_service_account.cpp
Backport of #6969 to 4-2-stable.
Prerequisite for irods/irods_client_icommands#381
=> [#6136] add irods::is_service_account function (4-2-stable)

scripts/irods/test/test_all_rules.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_native_rule_engine_plugin.py, scripts/irods/test/test_rulebase.py
Addresses #6976 
Running tests:
NB: This change is not based on the tip of 4-2-stable at time of writing. My understanding is that tests are failing there, so this change will not be fixing those failing tests (unless I'm instructed otherwise).
=> [#6976] Fix tests for running in topology (4-2-stable)

unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_process_stash.cmake, unit_tests/src/test_process_stash.cpp, unit_tests/unit_tests_list.json
Ported from #7006.
Tweaked the following:
- Header includes for the unit test
- Added clang-tidy NOLINT directive
- Placed files in the correct location
- Applied clang-format
The unit test passed in the testing environment.
=> [#6999] Added unit test for irods::process_stash library (main)

lib/api/include/irods/apiTable.hpp
Addresses #6931 
Leaving in draft for now because I haven't fully investigated the ramifications of this change. I know that it fixes setting up catalog consumers and I've even been able to run topology tests (somewhat) successfully.
=> [#6931] Use clearDataObjInfo for reg data obj output struct cleanup (main)

lib/api/include/irods/apiTable.hpp
Addresses #6931 
Cherry-picked from #6973
=> [#6931] Use clearDataObjInfo for reg data obj output struct cleanup (4-3-stable)

plugins/api/src/data_object_finalize.cpp, plugins/database/src/db_plugin.cpp, scripts/irods/test/test_dynamic_peps.py, server/core/include/irods_database_constants.hpp, server/icat/include/icatHighLevelRoutines.hpp, server/icat/src/icatHighLevelRoutines.cpp
Addresses #6385 
Adapted from and supersedes https://github.com/irods/irods/pull/5664
Still need to do some stuff for this, but putting it up now for discussion purposes. Core tests passed.
=> [#6385] Add DB plugin op for data_object_finalize (4-2-stable)

lib/core/src/fsckUtil.cpp, scripts/irods/test/test_ifsck.py
All tests (CI and unit) passed.
=> Create specific error message on ifsck when file encountered that is not registered. (4-2-stable)

plugins/api/src/data_object_finalize.cpp, plugins/database/src/db_plugin.cpp, scripts/irods/test/test_dynamic_peps.py, server/core/include/irods/irods_database_constants.hpp, server/icat/include/irods/icatHighLevelRoutines.hpp, server/icat/src/icatHighLevelRoutines.cpp
Addresses #6385
Cherry-picked from #7012 
Supersedes #5665
Major difference from 4-2-stable is a hefty application of `NOLINTNEXTLINE` to placate clang-tidy and clang-format had some opinions which were addressed. There is one issue clang-tidy is still upset about that I am not going to address since it has to do with a static constant string in a long list of others like it which have the same issue.
Core tests are running
=> [#6385] Add DB plugin op for data_object_finalize (main)

lib/core/src/msParam.cpp, scripts/irods/test/test_all_rules.py, server/re/src/reDataObjOpr.cpp
`msiAddKeyValToMspStr()` now can handle empty strings/key-value pairs properly.
=> [6918] Correct msiAddKeyVal behavior (4-2-stable)

plugins/resources/compound/libcompound.cpp, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRepl.cpp, server/core/include/finalize_utilities.hpp, server/core/src/finalize_utilities.cpp, server/re/src/reDataObjOpr.cpp
Once again, and perhaps finally, addresses #6997 
Tests exist in companion PR: https://github.com/irods/irods_resource_plugin_s3/pull/2106
One thing you may notice is that `purge_cache` is a bit of a misnomer... The function actually just trims whatever replica you specify with the passed in `DataObjInfo&`. This makes it a pretty handy replacement to calling trim API directly. I renamed it to `trim_replica` since it's a server-only function. I left this in a separate commit so it can be easily reverted.
Unit tests passed. Running regular test suite to make sure nothing fell over. Working with @JustinKyleJames to check the Glacier tests.
=> [#6997] Add admin keyword support to purge_cache (4-2-stable)

plugins/resources/src/compound.cpp, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRepl.cpp, server/core/include/irods/finalize_utilities.hpp, server/core/src/finalize_utilities.cpp
Addresses #6997 
Cherry-picked from #7072
Tests are in Companion PR: https://github.com/irods/irods_resource_plugin_s3/pull/2108
There were no differences between this and #7072 except the clang-format changes already exist in this branch, so that commit has been dropped.
Running core tests now
=> [#6997] Add admin keyword support to purge_cache (main)

lib/core/src/rcMisc.cpp, plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iadmin.py
Addresses #6675 for 4-3-stable.
Backport of #7005.
=> [#6675] db_[mod|reg]_zone_op: validate well-formed connection strings (4-3-stable)

lib/core/src/rcMisc.cpp, plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iadmin.py
Addresses #6675 for 4-2-stable.
Backport of #7005.
Will mark as ready for review when tests are complete
=> [#6675] db_[mod|reg]_zone_op: validate well-formed connection strings (4-2-stable)

plugins/database/src/db_plugin.cpp
Change log level for errors in `validate_zone_connection_string` introduced for #6675
=> [#6675] validate_zone_connection_string: log errors as errors (main)

plugins/database/src/db_plugin.cpp
Change log level for errors in `validate_zone_connection_string` introduced for #6675
=> [#6675] validate_zone_connection_string: log errors as errors (4-3-stable)

plugins/database/src/db_plugin.cpp
Change log level for errors in `validate_zone_connection_string` introduced for #6675
=> [#6675] validate_zone_connection_string: log errors as errors (4-2-stable)

scripts/irods/test/test_all_rules.py, server/core/src/objMetaOpr.cpp
A fix for the statement leak in `checkPermissionByObjType`. This also solves the memory leak which I erroneously reported as a statement leak, before.
=> [#7050] Fix statement leak in checkPermissionByObjType (4-2-stable)

scripts/irods/test/test_misc.py
Addresses #5411 
Found while running tests in topology on consumer with SSL enabled
=> [#5411] Skip iinit test when SSL is enabled (4-2-stable)

lib/core/include/irods/irods_configuration_keywords.hpp, lib/core/src/irods_configuration_keywords.cpp, packaging/server_config.json.template, schemas/configuration/v4/server_config.json.in, server/main_server/src/rodsServer.cpp
Addresses #6342 
Addresses #6370 
Core tests passed on ubuntu:20.04.
Couple of notes:
1. Open to changing any and all names and default values for the configurations as well as their affiliated variables in the code.
2. I thought about making `get_advanced_setting` a template function based on the type of the configuration value, but this seemed a little overboard considering everything is just `int`s (for now) and the function is only available in the one file so it doesn't need to be so general. Any thoughts on this would be appreciated.
3. I'm happy to hold on merging this to yield to #6673 due to impending conflicts.
4. Ignoring the clang-tidy issue because it's just getting confused by the generated header file for the control plane commands.
=> Expose some new configuration values (CRON tasks, socket timeouts) (main)

.clang-tidy, lib/core/CMakeLists.txt, lib/core/include/irods/client_connection.hpp, lib/core/include/irods/connection_pool.hpp, lib/core/include/irods/fully_qualified_username.hpp, lib/core/include/irods/library_features.h, lib/core/include/irods/rodsErrorTable.h, lib/core/src/client_connection.cpp, lib/core/src/connection_pool.cpp, plugins/microservices/src/test_issue_6829.cpp, server/api/src/rsModAccessControl.cpp, server/api/src/rsModColl.cpp, server/delay_server/src/irodsDelayServer.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_client_connection.cmake, unit_tests/cmake/test_config/irods_connection_pool.cmake, unit_tests/cmake/test_config/irods_fully_qualified_username.cmake, unit_tests/src/test_atomic_apply_acl_operations.cpp, unit_tests/src/test_client_connection.cpp, unit_tests/src/test_connection_pool.cpp, unit_tests/src/test_fully_qualified_username.cpp, unit_tests/src/test_get_delay_rule_info.cpp, unit_tests/src/test_json_apis_from_client.cpp, unit_tests/src/test_metadata.cpp, unit_tests/src/test_query_builder.cpp, unit_tests/unit_tests_list.json
This is in support of the C++ REST/HTTP API rewrite.
This is still a WIP, but it is mostly complete. The primary goal is to support proxy connections and allow client-side C++ implementations to choose how they authenticate. For example, the C++ REST/HTTP API rewrite needs to support login using usernames and passwords.
The unit tests pass. I still need to document things and figure out why `CAT_INVALID_AUTHENTICATION` is thrown from the lambdas instead of the the exception I defined.
Feel free to review or ask questions.
=> Client connection libraries allow deferring/changing the auth logic (main)

.clang-tidy, lib/core/CMakeLists.txt, lib/core/include/irods/client_connection.hpp, lib/core/include/irods/connection_pool.hpp, lib/core/include/irods/fully_qualified_username.hpp, lib/core/include/irods/library_features.h, lib/core/include/irods/rodsErrorTable.h, lib/core/src/client_connection.cpp, lib/core/src/connection_pool.cpp, plugins/microservices/src/test_issue_6829.cpp, server/api/src/rsModAccessControl.cpp, server/api/src/rsModColl.cpp, server/delay_server/src/irodsDelayServer.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_client_connection.cmake, unit_tests/cmake/test_config/irods_connection_pool.cmake, unit_tests/cmake/test_config/irods_fully_qualified_username.cmake, unit_tests/src/test_atomic_apply_acl_operations.cpp, unit_tests/src/test_client_connection.cpp, unit_tests/src/test_connection_pool.cpp, unit_tests/src/test_fully_qualified_username.cpp, unit_tests/src/test_get_delay_rule_info.cpp, unit_tests/src/test_json_apis_from_client.cpp, unit_tests/src/test_metadata.cpp, unit_tests/src/test_query_builder.cpp, unit_tests/unit_tests_list.json
=> Client connection libraries allow deferring/changing the auth logic (4-3-stable)

lib/core/include/irods/guiProgressCallback.h
Include missing headers that define rodsLong_t and MAX_NAME_LEN
=> [7101] Include missing headers for guiProgressCallback.h (main)

lib/core/include/irods/guiProgressCallback.h
Include missing headers that define rodsLong_t and MAX_NAME_LEN
=> [7101] Include missing headers (4-3-stable)

scripts/irods/test/test_auth.py, scripts/irods/test/test_misc.py
In service of #6398 
Companion PR: irods/irods_client_icommands#338
All core tests passed
I tried to cover the basic cases, but I can add some cases for more busted inputs. Also willing to squash to one commit. Wanted to keep the older test changes separate from the newer tests just in case
=> [#6398] Add iinit tests (main)

lib/core/include/irods/transport/default_transport.hpp
Cherry picked from https://github.com/irods/irods/pull/7199
=> [7160] Change default data size to -1 for dstream (4-3-stable)

lib/core/include/irods/getRodsEnv.h, lib/core/src/getRodsEnv.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_environment_variables.cmake, unit_tests/src/test_environment_variables.cpp, unit_tests/unit_tests_list.json
Use snprintf in capture_string_property and add size of string information
=> [6866] Add bound checks for environment variables (main)

scripts/irods/test/test_auth.py, scripts/irods/test/test_misc.py
In service of #3164 
In service of #6398 
Cherry-picked from #7198
Companion PR: https://github.com/irods/irods_client_icommands/pull/400
=> [#3164][#6398] Add iinit tests for scheme/SSL prompts (4-3-stable)

lib/administration/ticket/include/irods/ticket_administration.hpp, server/core/src/rodsAgent.cpp
Cherry-pick of #7218
We are not (currently?) planning on building 4.3.1 against libstdc++, but these changes are trivial enough that I think it's worth it to cherry-pick them into the stable branch.
=> A couple of small fixes for libstdc++ (4-3-stable)

lib/core/include/irods/getRodsEnv.h, lib/core/include/irods/irods_configuration_keywords.hpp, lib/core/include/irods/rodsErrorTable.h, lib/core/include/irods/sockComm.h, lib/core/src/getRodsEnv.cpp, lib/core/src/irods_configuration_keywords.cpp, lib/core/src/sockComm.cpp, schemas/configuration/v4/service_account_environment.json.in, scripts/irods/test/test_misc.py, server/core/src/miscServerFunct.cpp
Addresses #2533, #3824
Unit tests passed, running core tests.
I will be playing with `tc` tomorrow to see if I can demonstrate any effect from changing these values. I have demonstrated that setting `tcp_keepalive_time` to 0 results in an `errno` of 22, which is "Invalid argument". Not very useful. :)
=> [#2533,#3824] Add TCP keepalive option configs (main)

lib/core/include/irods/rodsError.h, lib/core/src/clientLogin.cpp, lib/core/src/rcConnect.cpp, lib/core/src/rcMisc.cpp, lib/core/src/rodsError.cpp, scripts/irods/test/test_ipasswd.py
Removed calls to printError in clientLogin.cpp
Moved printError function to rcMisc.cpp
Addresses https://github.com/irods/irods/issues/7048
=> [7048, 7161] Use error stack for `clientLogin` (main)

scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_iput.py, scripts/irods/test/test_iput_options.py, server/api/src/rsBulkDataObjPut.cpp
There are two and a half solutions presented here, as discussed in #7110. The "half" is whether to use `SYS_NOT_ALLOWED` or `USER_INCOMPATIBLE_PARAMS` in the case where we do not allow overwrites with bulk puts.
Please provide input on which solution seems more palatable.
=> Overwrites for bulk puts (main)

plugins/auth/src/pam_password.cpp, plugins/auth_legacy/src/pam.cpp, plugins/database/src/db_plugin.cpp, server/api/src/rsPamAuthRequest.cpp, server/icat/include/irods/icatHighLevelRoutines.hpp, server/icat/src/icatHighLevelRoutines.cpp
This presents two solutions to the pam_password length enforcement problem presented in #7098.
In one, the length restriction is increased from 50 (`MAX_PASSWORD_LEN`) to `PAM_MAX_RESP_SIZE` (on my system, this value is 512). This is the solution discussed in https://github.com/linux-pam/linux-pam/issues/118.
In the other, the length restriction is removed entirely on the client side and the entire password entered by the user is copied into the JSON input and passed to the server. I have tested a password of length 6000 and experienced no problems with this solution.
The question is... which of these is what we want, if either?
Bonus question: Should the `password_length` be signed or unsigned?
A test has been added to ensure that the configured `password_length` is being enforced by the …
=> Remove password_length configuration (main)

plugins/database/src/db_plugin.cpp, unit_tests/src/test_irods_lifetime_manager.cpp
The unit tests which failed before these changes now pass.
These changes do not require a full run of the test suite.
=> Trivial bug fixes (main)

scripts/irods/lib.py, scripts/setup_irods.py
I will clean it up a bit but the three ideas are included / commented out.
The problem/limitation of default_prompt is that we overloaded the 'default' kwarg to be more than a single value (a list, used as the numbered options), and then always selected the first list value as the actual default from that set of options.
I created a newly named 'previous' kwarg, populated it with any detected value, and then set the default value based on 'previous'.   I preserved the earlier behavior when not passing a previous value.
I think this is sufficient - we can refactor again later to not use a 'list of defaults' at all... later.
This current PR presents the list of options, in the same order across multiple runs, and remembers a previous selection.   I think those are the full list of criteria …
=> [7023] fix swapping of provider/consumer in setup_irods.py (main)

lib/core/include/irods/process_stash.hpp, lib/core/src/process_stash.cpp, unit_tests/src/test_process_stash.cpp
Cherrypick of #7301. Ran unit-tests, all except `irods_parallel_transfer_engine` passed.
=> [#7296] Make erase_if and erase return indication of change (4-3-stable)

lib/core/src/rcMisc.cpp
Will run against test suites soon.
=> [#7321] clearExecCmdOut frees contents of internal byte buffers (main)

lib/filesystem/src/filesystem.cpp
=> [#7327] Filesystem library now understands 4.2 permission strings (4-3-stable)

lib/core/src/rcMisc.cpp
=> [#7321] clearExecCmdOut frees contents of internal byte buffers (4-3-stable)

lib/core/src/connection_pool.cpp
This is a trivial fix. Running tests aren't necessary.
=> Fixed init bug in connection pool constructor (main)

lib/core/src/clientLogin.cpp, plugins/database/src/db_plugin.cpp, scripts/core_tests_list.json, scripts/irods/database_upgrade.py, scripts/irods/test/test_iadmin_set_grid_configuration.py, scripts/irods/test/test_native_authentication.py, scripts/irods/test/test_pam_password_authentication.py
Addresses #7274 (finally)
Unit tests pass and all the new auth tests pass. Running the rest of the core tests now.
=> Make auth config namespace more general, fix native auth config, and add more tests (main)

CMakeLists.txt
Addresses #7364 for main
With this change, `find_pacakge` can be used with a minimum version of iRODS.
`SameMinorVersion` is used over `AnyNewerVersion` so that a project looking for iRODS 4.2 won't match an installation of 4.3.
=> [#7364] Relax version matching for find_package (main)

scripts/irods/test/test_prep_genquery_iterator.py, scripts/irods/test/test_resource_types.py, scripts/irods/test/test_rulebase.py
In service of irods/irods_rule_engine_plugin_python#183
Companion to irods/irods_rule_engine_plugin_python#185
=> [irods/irods_rule_engine_plugin_python#183] PREP tests: update references to global_vars (4-3-stable)

plugins/resources/replication/src/irods_create_write_replicator.cpp, scripts/irods/test/replica_status_test.py, scripts/irods/test/resource_suite.py, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_irepl.py, scripts/irods/test/test_resource_types.py, scripts/run_tests.py, server/api/src/rsDataObjRepl.cpp, server/core/src/voting.cpp
Addresses #7476
Workaround for #6954 
Sibling PR: irods/irods_docs#241
---
Unit tests and core tests pass except for `test_delay_queue.Test_Delay_Queue`. Will investigate that, but it does not seem related to these changes.
Important changes occurred in `rsDataObjRepl.cpp` and I tried to leave explanatory comments/log messages where I could. The rest is mostly changes to the tests.
I kept the self-targeting commits separated in case we change our minds about that.
=> Change voting for write operations + associated replication fallout (main)

lib/core/src/irods_parse_command_line_options.cpp, lib/core/src/parseCommandLine.cpp, scripts/irods/test/test_iput.py, scripts/irods/test/test_irsync.py
=> [#7537] Add `--ignore-symlinks` alias for `--link` option (4-3-stable)

lib/filesystem/include/irods/filesystem/copy_options.hpp, lib/filesystem/src/filesystem.cpp, unit_tests/src/filesystem/test_filesystem.cpp
=> [#7443] Make `copy_data_object()` honor `copy_options::none` correctly (main)

scripts/irods/test/test_iadmin.py, server/api/src/rsGeneralAdmin.cpp
For #7380.
One issue is that this breaks any client currently using the original `rmgroup`, since every client has sent it with the `user` arg1. Taking suggestions on how to resolve that.
Haven't run tests.
=> Server-side code to only allow removal of appropriate entity (main)

lib/filesystem/include/irods/filesystem/copy_options.hpp, lib/filesystem/src/filesystem.cpp, unit_tests/src/filesystem/test_filesystem.cpp
=> [#7443] Make `copy_data_object()` honor `copy_options::none` correctly (4-3-stable)

lib/administration/user/src/user_administration.cpp
user_administration is also a rsGeneralAdmin client (d'oh!) and I didn't update it for the new [changes](https://github.com/irods/irods/pull/7587).
This fixes that. 
Question: does this also need to server sniff, maybe?
Unit tests pass; haven't tried the whole suite yet.
=> Fix user_administration library to account for new API changes (main)

lib/api/include/irods/dataObjRepl.h, lib/api/src/rcDataObjRepl.cpp, lib/core/include/irods/msParam.h, lib/core/include/irods/objInfo.h, lib/core/include/irods/parseCommandLine.h, lib/core/include/irods/rodsKeyWdDef.h, lib/core/src/replUtil.cpp, packaging/core.dvm.template, plugins/rule_engines/irods_rule_language/src/reVariableMap.gen.cpp, server/api/src/rsChkObjPermAndStat.cpp, server/core/src/irods_resource_backport.cpp, server/core/src/irods_resource_redirect.cpp, server/re/src/reDataObjOpr.cpp
Addresses #6953 
Companion PR: https://github.com/irods/irods_client_icommands/pull/456
I have not run any tests because this test is almost exclusively comments and documentation changes. The one code change is separating the deprecated `BACKUP_RESC_NAME_FLAG` from the other flags in a couple of microservices so that it can be singled out as deprecated in a comment, but it is still available for use.
=> [#6953] Deprecate BACKUP_RESC_NAME_KW (main)

lib/api/include/irods/apiNumberData.h, lib/api/include/irods/apiTable.hpp, lib/api/include/irods/generalUpdate.h, lib/core/include/irods/rodsGeneralUpdate.h, plugins/database/src/db_plugin.cpp, plugins/database/src/general_update.cpp, server/api/include/irods/rsGeneralUpdate.hpp, server/api/src/rsGeneralUpdate.cpp, server/core/include/irods/irods_api_calling_functions.hpp, server/core/include/irods/irods_database_constants.hpp, server/core/src/irods_api_calling_functions.cpp, server/icat/include/irods/icatHighLevelRoutines.hpp
Not yet tested.
Depending on how things go, I may expand this to `rxGeneralRowInsert` and `rxGeneralRowPurge`.
=> [#7554] Deprecate `rxGeneralUpdate` API endpoint (main)

scripts/irods/test/test_native_authentication.py, scripts/irods/test/test_pam_password_authentication.py
Addresses https://github.com/irods/irods/issues/7390
Just ran the updated pam_password test and it passed like 20 times in a row, so probably okay. The native auth version was updated but the test is being skipped right now as the feature in question is not supported for that auth scheme.
=> [#7390] Auth tests: Loosen error message assertions (main)

scripts/irods/test/test_native_authentication.py, scripts/irods/test/test_pam_password_authentication.py
Addresses #7390 
Cherry-picked from #7609
=> [#7390] Auth tests: Loosen error message assertions (4-3-stable)

scripts/irods/test/test_native_rule_engine_plugin.py, server/re/src/icatGeneralMS.cpp
This provides a simple fix to `msiSetResource(...)` by adding a null check before dereference.
=> [#7319] Make `msiSetResource` not crash agent

README.md, SECURITY.md
This results in a **Security tab** appearing on the front page.
The README also includes a link to the new markdown file for easier access.
This can be applied to the organization as well, but I need to investigate that more. Also, can happen later.
The idea to handle this via a SECURITY.md file was proposed by @MartinFlores751 _(good stuff)_.
Visit the branch to see how it looks live.
=> [#7618] Document process for reporting security vulnerabilities (main)

server/api/src/rsCollRepl.cpp
Funny-looking PR. Debugged with asan.
`rsCloseCollection` calls `freeCollHandle` calls `clearCollHandle` calls `clearCollSqlResult`, which frees the `collSqlResult_t`'s members. 
However, `rsReadCollection` calls `readCollection` calls `getNextCollMetaInfo`/`getNextDataObjMetaInfo`, and pointers from the `collSqlResult_t` are assigned to the `collEnt_t`'s members (no copying!), so freeing the members of the `collEnt_t` results in a double-free (since `clearCollSqlResult` should have already freed it).
The only reason this worked before (but not in error cases) was because the double-free was evaded by `collEnt` being set to `NULL` a few lines above (as the final operation of the `while` loop). This means `freeCollEnt` effectively becomes a no-op, since it instantly returns if `NULL` (and …
=> [7540] Fix double-free in rsCollRepl (main)

lib/api/src/rcDataObjCopy.cpp, lib/api/src/rcDataObjGet.cpp, lib/api/src/rcDataObjPut.cpp, lib/api/src/rcDataObjRepl.cpp, lib/core/include/irods/rodsKeyWdDef.h, lib/core/src/irods_parse_command_line_options.cpp, lib/core/src/rcPortalOpr.cpp, server/core/include/irods/miscServerFunct.hpp, server/core/src/miscServerFunct.cpp
I am opening this so that everyone can take a look.  I am not sure if I did this correctly or not.  When someone calls the various -Q options via icommands (iput, iget, icp, irepl), they will get a warning message that states the following:
```
Warning: RBUDP (-Q) is deprecated. Its use should be avoided.
```
The following will show up in the server log:
```
Warning: RBUDP transfer option was called.  This has been deprecated.
```
I am not sure I implemented the client side the correct way.  Furthermore, I am not sure that this code has any effect.
```
const irods::at_scope_exit add_deprecated_api_warning_message{[&] {
addRErrorMsg(&rsComm->rError, DEPRECATED_API, "RBUDP has been deprecated.");
}};
```
I was hoping this would make it back to the client so that this warning could be seen …
=> [6610] Deprecated RBUDP (4-3-stable)

scripts/irods/controller.py, scripts/irods/test/test_irodsctl.py
Addresses #7619
I've confirmed the fix and test validity on Ubuntu 22.04. I would like to test on Centos 7, too, because we will be releasing for that platform for 4.3.2 and it uses python2 by default.
Need to run core tests as well.
=> [#7619] irodsctl stop: Fix orphan agent cleanup (main)

scripts/irods/test/test_native_rule_engine_plugin.py, server/re/src/reSysDataObjOpr.cpp
This PR fixes a bug in `msiSetDefaultResc(...)` where a `nullptr` may be dereferenced, causing the agent to crash.
=> [_7319] Correct nullptr dereference in `msiSetDefaultResc(...)` (main)

scripts/irods/test/test_native_rule_engine_plugin.py, server/re/src/reSysDataObjOpr.cpp
=> [#7319] Correct nullptr dereference in `msiSetDefaultResc(...)` (4-3-stable)

doxygen/microservices.cpp, plugins/rule_engines/irods_rule_language/src/functions.cpp
This is to document writeLine().  I am not 100% sure if this is done as expected.
1. Will the link in doxygen/microservices.cpp be tied to the doxygen comments in plugins/rule_engines/irods_rule_language/src/functions.cpp?
2. Is this how we want this done where documentation for writeLine() is preceding the implementation for smsi_writeLine()?
=> [7388] Documenting the writeLine() function/microservice (4-3-stable)

doxygen/microservices.cpp, lib/api/include/irods/replica_truncate.h, scripts/core_tests_list.json, scripts/irods/test/test_all_rules.py, server/api/include/irods/rs_replica_truncate.hpp, server/re/include/irods/reAction.hpp, server/re/include/irods/reDataObjOpr.hpp, server/re/src/reDataObjOpr.cpp
Addresses #7577 
Addresses #7650
A few notes...
1. The only code changes are for the new microservice, which is not used by anything else. Therefore, I did not run the whole test suite as I do not see it as necessary.
2. I put the tests for the new microservice in the same commit as the microservice implementation itself this time because there is no benefit to separating them in this instance. It is testing a microservice that did not exist before, so of course the test will fail. That being said, make sure the returned error codes make sense and are expected. I think they are fine.
3. As noted in the docstring, the new tests are not meant to be comprehensive tests for truncate but just the various inputs for the microservice itself. The inputs for the API have been fleshed out in the …
=> Add replica_truncate microservice, fix Doxygen (main)

scripts/irods/test/test_all_rules.py, server/re/src/extractAvuMS.cpp
Potentially related to the issue? Not sure if this is exactly what Alan saw. Reproducible via:
`irule "msiSetKeyValuePairsToObj(*x,'$(ipwd)/afile.txt','-d')" null null` (note the nonexistence of `*x`)
Just checking the pointers themselves is not enough-- in testing, I found that the above call actually passes valid pointers into `msiSetKeyValuePairsToObj`, but their contents are empty, so the proceeding `strcmp` calls appear to segfault.
=> [7027] Add null checks to msiSetKeyValuePairsToObj (main)

scripts/irods/test/test_dynamic_peps.py, server/re/src/irods_re_serialization.cpp
Still feels drafty. Tried my hand at making something that could avoid having to unpack stuff element-by-element. Instead, it'll just try calling whatever's defined in `the_map` for each sub-type, and merging all of them back into the output `std::map` with a prefix. Potentially magical.
Tested by hand, and seems to behave mostly as expected.
Broken:
Trying to write the following into core.re:
```
*w = *STRUCTINP.collection;
msiModAVUMetadata('-C', '{self.user.session_collection}', 'add', '{avu_prefix}_1', *w, '');
```
...gives me an unsolvable typing error (`unit < (PATH)`, whatever that means), which is pretty baffling to me. The line it gets mad on is the first line.
I'm not sure if the NREP type solver is trying to automagically parse out a type, but then gets mad at something? Or …
=> [7413] Serialize function for structFileExtAndReg

scripts/irods/test/test_all_rules.py, server/re/src/extractAvuMS.cpp
Cherry-pick of https://github.com/irods/irods/pull/7694
=> [7027] Add null checks to msiSetKeyValuePairsToObj (4-3-stable)

lib/administration/user/include/irods/user_administration.hpp, lib/administration/user/src/user_administration.cpp, unit_tests/src/test_user_administration.cpp
This PR should allow groupadmins to make groups as a proxied user.
When discussing with @korydraughn yesterday, there may be some merit, either in this PR or a separate, to testing all the groupadmin features as a proxied user to ensure we are using the appropriate endpoints.
=> [#7576] Allow proxied groupadmin to make groups (main)

lib/core/src/system_error.cpp
=> [#7808] Remove `constexpr` from `is_irods_error_category` (main)

lib/core/src/system_error.cpp
=> [#7808] Remove `constexpr` from `is_irods_error_category` (4-3-stable)

lib/core/include/irods/rcMisc.h, scripts/irods/test/test_irule.py
Minimal patch to fix going past the end of the string.
Can't switch to using `std::isspace(...)` or others, as they would expand what this function originally did, I believe.
Table for reference:
https://en.cppreference.com/w/cpp/string/byte/isspace
=> [#7704] Ensure `trimPrefix(...)` doesn't go past end of string (main)

scripts/irods/test/test_all_rules.py, server/re/src/reDataObjOpr.cpp
Tested manually at the bench.
Just need to confirm the test is good and run the full test suite.
=> [#7859] Convert null pointer to empty string for checksum output parameter of msiDataObjChksum (4-3-stable)

scripts/irods/test/test_all_rules.py, server/re/src/reDataObjOpr.cpp
=> [#7859] Convert null pointer to empty string for checksum output parameter of msiDataObjChksum (main)

plugins/rule_engines/irods_rule_language/include/irods/private/re/configuration.hpp, plugins/rule_engines/irods_rule_language/include/irods/private/re/rules.hpp, plugins/rule_engines/irods_rule_language/src/configuration.cpp, plugins/rule_engines/irods_rule_language/src/rules.cpp
Instead of what `make_copy` used to do, it stores copies of rule files in-memory with an `unordered_map` mapping `irb` to the content.
`make_copy`'s copies seem to be accessed in two ways:
1. `readRuleSetFromLocalFile` uses `fopen` and friends. Copied the function, except with `fmemopen` for the new version.
2. `hash_rules` uses `std::ifstream` and friends. Copied the function, except with a `std::stringstream`
Seems to work ok at first blush. Taking suggestions on anything.
=> [5210] Rewrite make_copy so it stores rule files in memory

lib/core/src/client_connection.cpp, unit_tests/src/test_client_connection.cpp
=> [#7155] client_connection.cpp: Use error information in THROW expressions (main)

packaging/server_config.json.template, scripts/irods/test/test_ichksum.py, scripts/irods/test/test_iput.py, scripts/irods/test/test_irepl.py, server/api/src/rsFileChksum.cpp
This is a change to allow the setting of the read buffer size for checksum in server_config.json.
- The test case simply puts a file in iRODS, reads the checksum, removed the data object, updates the buffer size in the configuration, restarts the server, puts the same file, reads the checksum, compares the two, then cleans up.  I don't know of any way to verify that the buffer size is actually updated at runtime although I have manually tested and verified this with extra logging.
-  I updated the configuration template to add `checksum_read_buffer_size_in_bytes` with the same default that was originally hardcoded.  I started up a server to verify that a new installation has this configuration.  I also verified that during the execution of the test the configuration was in fact updated.
=> [7947] make checksum buffer size configurable (4-3-stable)

packaging/server_config.json.template, scripts/irods/test/test_ichksum.py, scripts/irods/test/test_iput.py, scripts/irods/test/test_irepl.py, server/api/src/rsFileChksum.cpp
This is a cherry-pick from the 4-3-stable commit.
- Added test case for checksum buffer size update
- Updated server_config.json template to include checksum_read_buffer_size_in_bytes
=> [7947] make checksum buffer size configurable (main)

cmake/InstallDirs.cmake
With this PR, `InstallDirs.cmake` no longer overrides the default value for `CMAKE_INSTALL_LIBDIR`, which means the by default, our libraries and plugins will now be installed in the proper locations depending on distribution directory structure.
Since `CMAKE_INSTALL_LIBDIR` is a cache variable on which other variables depend, a clean cmake build directory is recommended.
So far testing hasn't revealed anything surprising, but I've got more tests to run, so I'm leaving this in draft mode for now.
=> [#7410] Use default value for `CMAKE_INSTALL_LIBDIR` (main)

plugins/database/src/low_level_odbc.cpp, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_imeta_error_handling.py, scripts/irods/test/test_resource_types.py
In the "moving existing code around" stage. 
Works for all the test cases listed in the issue. 
Still needs new test(s) to box in the behavior, as well as running of all the other tests.
=> [7599] Rework logic in _cllExecSqlNoResult to return proper error codes (main)

plugins/database/src/low_level_odbc.cpp, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_imeta_error_handling.py, scripts/irods/test/test_resource_types.py
Cherry-pick of https://github.com/irods/irods/pull/7987
=>  [7599,7440] Rework logic in _cllExecSqlNoResult to return proper error codes (4-3-stable)

scripts/irods/test/test_iadmin.py
Depends on https://github.com/irods/irods_client_icommands/pull/506 
Works for what it tests. 
Still needs a full test run.
=> [7734] Add tests for new iadmin behavior (main)

scripts/irods/test/test_iadmin.py
Cherry-pick of https://github.com/irods/irods/pull/8030
Depends on https://github.com/irods/irods_client_icommands/pull/507
=> [7734] Add tests to ensure iadmin failures exit nonzero (4-3-stable)

CMakeLists.txt, cmake/InstallDirs.cmake
Despite what CMake's documentation might say, getting `find_package` to look in `lib64` for CMake package configuration files is a very ugly business that we would rather try to avoid. This PR puts our CMake package configuration back in `lib` for EL and provides a cache variable `IRODS_INSTALL_CMAKEDIR` should the builder need to tweak things.
Part of #7410, as this work should've been in the PR for changing where our libraries end up.
Still testing, so draft for now.
=> [#7410] Provide CMake cache variable for package configuration directory

server/core/include/irods/irods_resource_manager.hpp
Will compile server and icommands shortly.
=> [#8042] Deprecate unused global variables in resource manager implementation (4-3-stable)

unit_tests/src/test_rc_switch_user.cpp
Small tweak to make unit test match changes in #8060.
=> [#8047] Guarantee test users are removed if rc_switch_user test fails (main)

server/core/src/procLog.cpp
I'll confirm at the bench whether this works.
This doesn't require running the full suite since the same data is being presented, just in a different order.
=> [#8001] Write client and proxy user info to ips data file in correct order (4-3-stable)

.github/workflows/linter-irods-clang-format.yml, .github/workflows/linter-irods-clang-tidy.yml
In service of #7823
Also adds [.h,.c.,.hpp,.cpp].in files to clang-format extension list
=> [#7823] Update GitHub workflows for Ubuntu 24.04 (4-3-stable)

server/core/include/irods/miscServerFunct.hpp
Builds without warnings. No tests ran, as the issues should come up at build time.
=> [#8109] Deprecate `forkAndExec(...)` (4-3-stable)

lib/api/include/irods/replica_open.h
In service of #2600
Noticed that `replica_close` had documentation but not `replica_open`.
=> [#2600] Doxygen: Add replica_open.h (4-3-stable)

CMakeLists.txt, lib/core/src/msParam.cpp, lib/filesystem/src/path.cpp, server/delay_server/src/irodsDelayServer.cpp, server/main_server/src/rodsServer.cpp, server/re/src/printMS.cpp, ub-sanitizer-ignorelist.txt
Still need to improve the ignore list (e.g. hashing functions have expected overflow behavior.)
Found some issues, planning to address easy fixes in this PR too.
I do have a question. Based on the current configuration, files like ssl.cpp, sockComm.cpp, and packStruct.cpp produce a lot of errors on implicit conversions. These conversions are not undefined behavior, but a reminder to check "is this is what you really want".
Do we want to make these conversions explicit? If we don't, do we make an ignore for these?
=> [#8090] Add Undefined Behavior Sanitizer to Build Options (4-3-stable)

lib/core/src/rcConnect.cpp, unit_tests/src/test_rcConnect.cpp
Running tests. Ideally, nothing calls this twice, but this should avoid segfault if it is done so by accident.
=> [8120] Avoid segfault in rcDisconnect (main)

lib/core/include/irods/irods_lexical_cast.hpp
=> [#5800] catch `boost::bad_lexical_cast` by reference (main)

lib/core/include/irods/irods_lexical_cast.hpp
Addresses #5800 for 4-3-stable
=> [#5800] catch `boost::bad_lexical_cast` by reference (4-3-stable)

scripts/irods/test/test_ils.py
Rebased on tip of main.
Ran test in isolation as this doesn't change the behavior of the server.
```
--- IrodsSession: icommand executed by [otherrods#tempZone] [ils -A just testin'] ---         
Assert Command: ils -A just testin'                                                  
Expecting STDOUT: ['ACL - otherrods#tempZone:own']                 
stdout:            
|   /tempZone/home/otherrods/2025-02-05Z22:09:43--irods-testing-3w9c7ypy/just testin'      
|         ACL - otherrods#tempZone:own                                        
stderr:                                                                                      
|                                                                                      
Output found                                
```
I think we're all good …
=> [#7164] Add test showing "ils -A" handling embedded single quotes (main)

lib/core/include/irods/rodsGenQuery.h
This doesn't require testing since the macro is already defined once. The removal of the second definition does not change existing behavior.
=> [#8133] Remove duplicate macro definition for GenQuery1 (4-3-stable)

lib/core/include/irods/rodsGenQuery.h
=> [#8133] Remove duplicate macro definition for GenQuery1 (main)

scripts/irods/test/test_iquery.py, server/genquery2/include/irods/private/genquery2_table_column_mappings.hpp, server/genquery2/src/genquery2_sql.cpp
Cherry-pick of #8171.
Will verify the changes pass at the bench.
=> [#8134,#8135] GenQuery2: Fix column mappings and table aliasing for permissions (main)

scripts/irods/lib.py, scripts/irods/test/test_istream.py
Companion PR for irods/irods_client_icommands#530.
All unit/core tests pass.
=> [#8166] Add test for `istream read --count` (4-3-stable)

scripts/irods/lib.py, scripts/irods/test/test_istream.py
Cherry-pick of #8180.
Companion PR for irods/irods_client_icommands#531.
=> [#8166] Add test for `istream read --count` (main)

server/genquery2/dsl/lexer.l, unit_tests/src/test_rc_genquery2.cpp
=> [#7685] Fix flex warning for GenQuery2 lexer rules (4-3-stable)

lib/genquery1/dsl/lexer.l, server/genquery2/dsl/lexer.l, unit_tests/src/test_genquery1_flex_bison_parser.cpp, unit_tests/src/test_rc_genquery2.cpp
Cherry-pick of #8179.
This PR fixes the same issue for the GenQuery1 flex/bison parser.
Unit tests pass. Will run the core tests soon.
=> [#7685] Fix flex warning for GenQuery2 lexer rules (main)

CMakeLists.txt, lib/core/src/msParam.cpp, lib/filesystem/src/path.cpp, server/delay_server/src/irodsDelayServer.cpp, server/main_server/src/agent_main.cpp, server/main_server/src/main.cpp, server/re/src/printMS.cpp, ub-sanitizer-ignorelist.txt
These commits are a cherry-pick of PR #8138.
Since some files have changed in main, the UBSAN commit is different. The additional change is to have the `__ubsan_default_options()` functions to be co-located where the `__asan_default_options()` functions are.
=> [#8090,#8153] Cherry-pick: Add Undefined Behavior Sanitizer and fix undefined behavior discovered by UBSAN (main)

scripts/irods/test/test_irule.py, server/re/src/irods_re_structs.cpp
Cherry-pick of https://github.com/irods/irods/pull/8193
=> [8095] NREP: write functions return error on nonexistent target (4-3-stable)

scripts/irods/test/test_federation.py, scripts/irods/test/test_iquery.py, server/api/include/irods/rsDataGet.hpp, server/api/include/irods/rsDataPut.hpp, server/api/src/rsDataGet.cpp, server/api/src/rsDataPut.cpp, server/core/src/miscServerFunct.cpp
Addresses #4984 
In service of #6421
In service of #7795
Unit tests and federation tests passed. Core tests are running now.
There's no way to automatically test the scenario described in #4984 with our existing test infrastructure. As such, there are no new tests for that scenario, and I confirmed manually that things are working for Puts and Gets.
=> Fix unencrypted parallel transfer with server encryption enabled, test iget over federation (4-3-stable)

plugins/rule_engines/irods_rule_language/include/irods/private/re/configuration.hpp, plugins/rule_engines/irods_rule_language/src/configuration.cpp
Previously, `Cache` was not a trivial class, meaning that it should not be `memset(...)`.
This PR removes the constructor, allowing the structure to be `memset(...)`.
=> [#8111] Fix: Remove constructor from `Cache` in NREP to allow `Cache` to be memset (4-3-stable)

lib/core/include/irods/rodsPath.h, lib/core/src/chksumUtil.cpp, lib/core/src/irods_parse_command_line_options.cpp, lib/core/src/miscUtil.cpp, lib/core/src/msParam.cpp, lib/core/src/rodsPath.cpp, lib/core/src/rsyncUtil.cpp, server/api/src/rsDataObjChksum.cpp
This PR has a companion fix in icommands. The icommands fix are optional, as in there is no real growing memory leak, but it does address ASAN comments.
=> [#8106] Fix memory leaks found in irsync tests (4-3-stable)

lib/core/include/irods/rodsPath.h, lib/core/src/chksumUtil.cpp, lib/core/src/irods_parse_command_line_options.cpp, lib/core/src/miscUtil.cpp, lib/core/src/msParam.cpp, lib/core/src/rodsPath.cpp, lib/core/src/rsyncUtil.cpp, server/api/src/rsDataObjChksum.cpp
=> [#8106] Cherry-pick: Clean up memory in rsDataObjChksum and various endpoints (main)

plugins/rule_engines/irods_rule_language/src/conversion.cpp
Running unit and core tests.
No test for this since it would require reading the log file. I did verify at the bench that the agent no longer exits with signal 6.
=> [#3581] Avoid SIGABRT by setting pointers to null after deallocation (4-3-stable)

plugins/rule_engines/irods_rule_language/src/conversion.cpp
=> [#3581] Avoid SIGABRT by setting pointers to null after deallocation (main)

server/api/src/rsDataGet.cpp, server/api/src/rsDataPut.cpp, server/core/src/miscServerFunct.cpp
In service of #4984 
Partially reverts #8195
`SYS_SOCK_READ_ERR` is the closest thing I could find to what I wanted from an existing error code; open to other suggestions. Couldn't find anything related to SSL/TLS that came close. Maybe we need a new error code.
Unit tests passed. Core tests running. Will mark Ready for Review once they're passing.
=> Revert #8195, add error handling to legacy parallel transfer (4-3-stable)

scripts/irods/test/test_federation.py, scripts/irods/test/test_iquery.py, server/api/include/irods/rsDataGet.hpp, server/api/include/irods/rsDataPut.hpp, server/api/src/rsDataGet.cpp, server/api/src/rsDataPut.cpp, server/core/src/miscServerFunct.cpp
In service of https://github.com/irods/irods/issues/4984
In service of https://github.com/irods/irods/issues/6421
In service of https://github.com/irods/irods/issues/7795
Cherry-pick of #8195 
Cherry-pick of #8211 
Supersedes https://github.com/irods/irods/pull/8197
Please note that the cherry-pick has been squashed into a single commit to avoid the revert commit in the main branch. I've noted the cherry-picked SHAs in the commit message for posterity. I've also left changes to the cherry-picked test in this branch as a separate commit to be squashed closer to merge time.
Unit tests passed. Core tests running now.
=> Add error handling to legacy parallel transfer, test iget over federation and iquery with tabs (main)

lib/core/include/irods/irods_plugin_base.hpp
Issue quick link: #8010
This commit removes a duplicate declaration of the function `add_global_re_params_to_kvp_for_dynpep(...)`.
=> [#8010] Fix: Remove duplicate function declaration (4-3-stable)

lib/core/include/irods/irods_plugin_base.hpp
Cherry-pick of #8226.
---
This commit removes a duplicate declaration of the function `add_global_re_params_to_kvp_for_dynpep(...)`.
=> [#8010] Cherry-pick: Remove duplicate function declaration (main)

lib/core/src/irods_client_negotiation.cpp
Addresses #6684 
Cherry-picked from 5eb7401d2709576d42acda2d571a649088019d5f (see #7988).
As noted in the issue, we have no way to test this in an automated fashion (see https://github.com/irods/irods/issues/6684#issuecomment-2672575054). I'm still going to run unit, core, and federation tests. Will mark ready for review once done.
=> [#6684] Use ProcessType to detect server vs pure client. (4-3-stable)

server/api/src/rsDataObjUnlink.cpp
I've confirmed at the bench that the code change works as intended. No test necessary since it's just logging.
The message is logged if the oprType is actually changed (i.e. `irm` vs `iunreg`).
=> [#7953] Do not log message unless oprType is changed to UNREG_OPR (4-3-stable)

scripts/irods/json_validation.py
Issue quick link: #7752.
---
`name` is not in scope at the point the exception is created.
=> [#7752] Remove `name` from exception (4-3-stable)

packaging/core.re.template, server/re/src/icatAdminMS.cpp
The presented implementation logs a warning about setting the ACL policy to something other than STRICT. The problem is that it happens on every fork of an agent due to how 4.3 works. That makes the log file very noisy, especially with the delay server migration check happening every 5 seconds.
As of right now, it seems the solution for the noisy log is to use more IPC. I'd really like to avoid that, but I'm not sure that I can. So, here's some ideas I'm thinking about:
- Use a boost interprocess mutex as a flag
- Or, use a file as a flag
The more I think about this, the more I'm leaning towards removing the edits to the C++ and letting this be purely a job for core.re.template and the release notes.
Thoughts?
=> [#6843] Deprecate modification of ACL policy (4-3-stable)

lib/core/src/irods_parse_command_line_options.cpp
The test referenced in the issue passed at the bench using a debug build. I only tested the one test case reported in the issue.
Running unit/core tests.
@MartinFlores751 Do you remember if this change was important in the memory leak fix which introduced `freeRodsPathInpMembers`?
=> [#8221] Clear rodsPathInp_t instead of freeing memory (4-3-stable)

lib/core/src/irods_parse_command_line_options.cpp
=> [#8221] Clear rodsPathInp_t instead of freeing memory (main)

scripts/irods/test/resource_suite.py, server/core/src/rodsAgent.cpp
Preparing to run unit/core tests.
=> [#7934] Ignore SIGPIPE so agents do not terminate immediately (4-3-stable)

lib/core/src/rcMisc.cpp, scripts/irods/test/test_prep_genquery_iterator.py
The test which triggered this fix passed for the PREP.
=> [#8249] Add support for `order_asc` to GenQuery1 string parser (4-3-stable)

lib/genquery1/dsl/parser.y, scripts/irods/test/test_prep_genquery_iterator.py
Port of #8250.
Will confirm this works at the bench soonish.
=> [#8249] Add support for `order_asc` to GenQuery1 string parser (main)

server/core/include/irods/miscServerFunct.hpp, server/core/src/miscServerFunct.cpp
Quick link to issue: #8114
This PR removes the deprecated (in 4.3.4) `forkAndExec(...)` in issue #8109.
=> [#8114] Remove `forkAndExec(...)` (main)

doxygen/microservices.cpp, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_native_rule_engine_plugin.py, server/re/include/irods/reAction.hpp, server/re/src/icatGeneralMS.cpp
Issue quick link #7603.
This PR removes `msiSetResource(...)`, which was deprecated in iRODS 4.3.2.
=> [#7603] Remove `msiSetResource` (main)

lib/genquery1/dsl/parser.y, scripts/irods/test/test_iquest.py, unit_tests/src/test_genquery1_flex_bison_parser.cpp
Still need to run unit/core tests.
```bash
$ iquest "select nope(DATA_ID)"
remote addresses: X.X.X.X ERROR: iquest Error: queryAndShowStrCond failed status = -183000 INVALID_GENQUERY_AGGREGATE_FUNCTION
```
=> [#8252] GenQuery1: Return same error as iRODS 4.3.4 on invalid aggregrate function (main)

scripts/irods/controller.py
Searching the repo for calls to `.status()` shows that nothing uses it.
=> [#8008] Remove status function from IrodsController (main)

lib/core/include/irods/irods_configuration_keywords.hpp, lib/core/src/irods_configuration_keywords.cpp, packaging/server_config.json.template.in, schemas/configuration/v5/server_config.json.in, scripts/irods/upgrade_configuration.py
Need to confirm the upgrade path removes the config option.
=> [#8069] Remove unused config option: agent_factory_watcher_sleep_time_in_seconds (main)

lib/core/include/irods/irods_path_recursion.hpp, lib/core/src/irods_parse_command_line_options.cpp, lib/core/src/irods_path_recursion.cpp, lib/core/src/parseCommandLine.cpp, lib/core/src/putUtil.cpp, lib/core/src/rodsPath.cpp, lib/core/src/rsyncUtil.cpp, scripts/irods/test/test_iput.py, scripts/irods/test/test_irsync.py, scripts/irods/test/test_symlink_operations.py
Issue quick link: #7578.
This PR removes all documentation and code on `--link` option, and substitutes with `--ignore-symlinks` when able.
Since there were a lot of `--links` in the tests, a bulk substitution was done there.
Core and unit tests passed (save for `Test_ImetaQu`, which is handled here: https://github.com/irods/irods/pull/8320#issue-2943716157).
=> [#7578] Remove the `--link` option (main)

server/core/include/irods/access_time_queue.hpp
Builds on ub24 break without it.
=> [8260] Add missing header file

scripts/irods/test/test_iquery.py, server/genquery2/dsl/lexer.l, server/genquery2/dsl/parser.y, server/genquery2/include/irods/private/genquery2_ast_types.hpp, server/genquery2/src/genquery2_sql.cpp
Cherry-pick of #8339.
84e6882f2a4cb02d8418399ca941b090cf259bc3 is not included because it is specific to iRODS 5.
=> [#8261] Give control of SQL DISTINCT to caller (4-3-stable)

plugins/database/src/db_plugin.cpp, plugins/database/src/low_level_odbc.cpp, plugins/database/src/mid_level_routines.cpp
Issue Quick Link: #8317
This PR attempts to replace appropriate `rodsLog(...)` calls with `log_db::[LOG LEVEL](...)`.
Potential files for substitution were found using `git grep 'rodsLog' -- '*.[ch]pp' '*.[ch]'`.
The files were combed to find `rodsLog(...)` calls that don't log SQL strings or bind variables.
I considered `rodsLog(...)` calls with status variables ok to update when I did my pass, save for a few exceptions.
Log strings were left as is.
`general_query.cpp` was not updated as it was assumed all logs there are related to GenQuery1.
---
An additional search for `irods::log(...)` calls was done using the following: `git grep 'irods::log' -- '*.[ch]pp' '*.[ch]'`.
=> [#8317] Substitute `rodsLog(...)` with new logger in database plugin (main)

plugins/authentication/src/pam_password.cpp
In service of #8016
Only ran `test_pam_password_authentication` and it passes. Can run the whole test suite if desired.
=> [#8016] Erase AUTH_PASSWORD_KEY from response in pam_password (main)

lib/core/include/irods/rodsErrorTable.h, plugins/auth/src/native.cpp, plugins/auth/src/pam_password.cpp, plugins/microservices/src/test_user_administration.cpp, scripts/irods/test/test_auth.py, unit_tests/src/test_atomic_apply_acl_operations.cpp, unit_tests/src/test_client_connection.cpp, unit_tests/src/test_connection_pool.cpp, unit_tests/src/test_rcTicketAdmin.cpp, unit_tests/src/test_rc_switch_user.cpp, unit_tests/src/test_user_administration.cpp
In service of #7948 
Addresses #8016
Addresses #8391 
Cherry-picked from: #8383
Cherry-picked from: #8393
Companion PR: https://github.com/irods/irods_client_icommands/pull/562
Unit tests passed, auth-based tests are passing. Running the full core test suite now.
=> Enable auth plugins to accept passwords in requests, add 5.0 error code (4-3-stable)

scripts/irods/test/test_rule_engine_plugin_framework.py
Ported from ae9a6af8b0e05fe6c23b0408052646a44642ff40.
Will confirm the test passes in isolation.
=> [#8414] Increase number of delayed assertion checks in test for cpp-default REP (4-3-stable)

plugins/authentication/src/native.cpp, plugins/authentication/src/pam_password.cpp
Addresses #8411
Not sure if this is the ideal spot, but it felt weird to put it in irods_docs. Few developers will be constructing or interacting with these objects directly, but there aren't many other places to put this information. Open to suggestions.
Here's what the pam_password one looks like:
I noticed through this that the auth plugins are in the `irods` namespace but should probably be in the `irods::authentication` namespace. The `authentication_base` class is in `irods::authentication`, so it seems appropriate. I'll look into that.
=> [#8411] Document auth plugin-specific input options (main)

lib/core/src/msParam.cpp, scripts/irods/test/test_python_rule_engine_plugin.py
I've confirmed the change works at the bench.
Still need to run this change against the PREP via the testing environment.
=> [#8265] Restore support for KeyValPair in Python REP (4-3-stable)

plugins/authentication/src/native.cpp, plugins/authentication/src/pam_password.cpp, scripts/irods/test/test_auth.py, scripts/irods/test/test_pam_password_authentication.py
Addresses #8360 
Addresses #8428 
Unit tests and core tests passed, with an exception noted in #8432.
=> Move auth plugins into auth namespace, return error if TLS not enabled for pam_password (main)

scripts/irods/test/test_iquery.py, server/api/src/rs_genquery2.cpp
Confirmed that the test reproduces the bug and that the C++ change fixes it.
=> [#8439] GenQuery2: Do not pass nullptr to logger (main)

scripts/irods/test/test_iquery.py, server/api/src/rs_genquery2.cpp
=> [#8439] GenQuery2: Do not pass nullptr to logger (4-3-stable)

server/main_server/src/agent_main.cpp, server/main_server/src/main.cpp
This has not been tested yet, but feel free to start reviewing it.
One thing that stands out to me is the fact that this implementation allows the service account user to send SIGUSR2 to the main server process, potentially affecting its ability to accurately detect when the agent factory is ready.
Now, this isn't a huge concern because it requires a user to have access to the service account or root access.
I've left a TODO comment in the code to highlight this situation. We could limit communication of SIGUSR2 to just the agent factory, but I'm not sure that's a good idea. One could argue that allowing the admin to send this signal is actually a good thing.
There's also the question of - when is the agent factory (or config reload) considered to be complete? Is it when the agent factory …
=> [#8147] Make agent factory notify main server process of readiness (main)

plugins/database/src/db_plugin.cpp
Added "limit 3" as we are only interested in whether there is 0, 1, or >1 matching AVU's.
Reformatted to reduce the length of lines.
=> [8392] Change query in db_set_avu_metadata_op for efficiency (main)

scripts/irods/controller.py, scripts/irods/database_interface.py, scripts/irods/database_upgrade.py, scripts/setup_irods.py
The `is_upgrade` parameter is false when `setup_irods.py` is executed. `is_upgrade` is true when `upgrade_irods.py` is executed.
Will test this as soon as I work through setting up the testing environment.
=> [#8315] Show access time note on server upgrade only (main)

lib/core/include/irods/irods_configuration_keywords.hpp, lib/core/src/irods_configuration_keywords.cpp, plugins/database/src/db_plugin.cpp, schemas/configuration/v5/database_config.json.in, schemas/configuration/v5/server_config.json.in, scripts/irods/configuration.py, scripts/irods/database_connect.py, scripts/irods/database_interface.py, scripts/irods/upgrade_configuration.py, server/core/src/catalog.cpp, server/icat/src/icatHighLevelRoutines.cpp
Issue quick link: #7975
This PR attempts to update the database plugin stanza in `server_config.json` to 'flatten' the structure. Several other files were modified to add new lines and update existing lines that referenced the old schema.
Testing:
- New install (this covers the provider case)
- Run the topology tests for consumer
- Unit tests do not apply to this case
- Requires you to pass the iRODS 5 packages to the run script
- Launch the run_core_tests.py script with `--leak-containers` and a short-running test
- Manually upgrade packages to iRODS 5
- Rerun run_core_tests.py, adding `--skip-setup`, remove `--tests` so that all core tests are run
- Same steps as the provider case, but with run_topology_tests.py instead of run_core_tests.py
- _This case could be combined with the …
=> [#7975] Update database plugin stanza

lib/api/include/irods/dataObjCopy.h, lib/api/include/irods/dataObjCreate.h, lib/api/include/irods/dataObjCreateAndStat.h, lib/api/include/irods/dataObjOpen.h, lib/api/include/irods/dataObjOpenAndStat.h, lib/api/include/irods/dataObjPut.h, lib/api/src/rcDataObjCopy.cpp, lib/api/src/rcDataObjCreate.cpp, lib/api/src/rcDataObjCreateAndStat.cpp, lib/api/src/rcDataObjPut.cpp, lib/api/src/rcDataObjRepl.cpp, lib/core/src/cpUtil.cpp, lib/core/src/irods_parse_command_line_options.cpp, lib/core/src/miscUtil.cpp, lib/core/src/putUtil.cpp, plugins/api/src/data_object_finalize.cpp, plugins/api/src/register_physical_path.cpp, plugins/authentication/src/native.cpp, scripts/irods/test/resource_suite.py, server/api/src/rsDataObjOpen.cpp, server/core/include/irods/objDesc.hpp, server/core/src/objDesc.cpp, server/delay_server/src/irodsDelayServer.cpp, server/re/src/reDataObjOpr.cpp
In service of #4932
In service of #8334 
After these changes and those in the companion PR for `iput`, the remaining issues reported by ASAN are coming from `irods_user_administration` and `irods_json_apis_from_client`. The rest of the ones reported in #8334 have been addressed.
Unit tests pass. Still need to run core tests, so leaving in draft for now.
=> Fix some memleaks reported by ASAN (main)

scripts/irods/database_upgrade.py, server/api/src/rs_genquery2.cpp
In service of #7975
Addresses #8482
Addresses #8485
Need to run same tests as in https://github.com/irods/irods/pull/8437, I suppose:
- New install (this covers the provider case)
- Run the topology tests for consumer
- Unit tests do not apply to this case
- Requires you to pass the iRODS 5 packages to the run script
- Launch the run_core_tests.py script with `--leak-containers` and a short-running test
- Manually upgrade packages to iRODS 5
- Rerun run_core_tests.py, adding `--skip-setup`, remove `--tests` so that all core tests are run
- Same steps as the provider case, but with run_topology_tests.py instead of run_core_tests.py
- _This case could be combined with the provider case since they run in identical setups_
=> Fix issues around mysql (main)

lib/core/include/irods/irods_logger.hpp
=> [#8498] Replace invalid UTF-8 sequences in log messages (4-3-stable)

server/main_server/src/agent_main.cpp
This is in service of the PREP test failures.
Leaving in draft until I determine why I'm seeing the following message in the log file. _That message only appears when the PREP (first) and NREP (second) are configured._
```
"log_message":"removeSharedMemory: failed to remove shared memory",
```
=> [#7229] Run plugin start operations before REPF interactions (main)

scripts/irods/lib.py, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_irepl.py, scripts/irods/test/test_rulebase.py
blind first attempt, tests have not been run
only touches a few suites
companion to https://github.com/irods/irods_client_icommands/pull/571
=> [8497] replace use of 'iadmin ls' in tests

plugins/database/src/db_plugin.cpp, plugins/microservices/src/test_delay_rule_locking_api.cpp, unit_tests/src/test_delay_rule_locking_api.cpp
I've confirmed the change to the API reports the expected error code, `SYS_INVALID_INPUT_PARAM`.
I've confirmed `irods_delay_rule_locking_api` and `test_misc.py` pass with these changes. Tests were run against PostgreSQL, MySQL, and MariaDB.
Test results for `irods_delay_rule_locking_api`:
```
2025-05-14 13:04:25,444 - [debian-12-mariadb-1011_irods-catalog-provider_1]: running test [irods_delay_rule_locking_api]
2025-05-14 13:04:27,587 - [debian-12-mariadb-1011_irods-catalog-provider_1]: test passed [[   2.1426]s] [irods_delay_rule_locking_api]
2025-05-14 13:04:27,588 - [debian-12-mariadb-1011_irods-catalog-provider_1]: tests completed successfully
2025-05-14 13:04:27,588 - ==== begin test run results ====
-----
results for [debian-12-mariadb-1011_irods-catalog-provider_1]
passed tests: …
```
=> [#8515] rx_delay_rule_unlock: Return error on non-numeric rule IDs (main)

schemas/configuration/v5/server_config.json.in, scripts/irods/test/test_configuration.py, server/api/src/rsDataObjGet.cpp
Addresses #8373
`test_iget` passes. Running other core tests now.
=> [#8373] DataObjGet: Enforce max size for single buffer (main)

schemas/configuration/v4/server_config.json.in, server/api/src/rsDataObjGet.cpp
Addresses #8373 
Cherry-picked from https://github.com/irods/irods/pull/8570
The test was not cherry-picked because `test_configuration` does not exist in 4-3-stable and there is no configuration check feature in the server for 4.3. I can add an equivalent test, but I figured this is probably good enough for 4.3.
That said, running core tests now.
=> [#8373] DataObjGet: Enforce max size for single buffer (4-3-stable)

scripts/irods/controller.py
looking for better warning message / phrasing / instructions for the admin.
something like...
'you need more --init'
or
'go read about init processes'
=> [8588] python controller errors out early if it detects a terminated process is a zombie (main)

scripts/irods/test/test_irsync.py, server/api/src/rsDataObjPut.cpp
A bunch of research for a one-line change...
Works when I test it by  hand on the test case in the original issue. Taking suggestions if this change triggers any red flags for anyone.
Still needs a unit test.
=> [8295] Avoid error in rsDataObjPut when ALL_KW is set (4-3-stable)

lib/core/src/irods_log.cpp
Issue quick link: #8083
This PR simplifies the error produced when using an iRODS environment file that does not exist. Following is an example of the new output:
```console
$ IRODS_ENVIRONMENT_FILE=test1 ils
ERROR: environment_properties::capture: missing environment file. should be at [test1]
ERROR: _rcConnect: setRhostInfo error, IRODS_HOST is probably not set correctly status = -302000 USER_RODS_HOST_EMPTY
```
---
I modified `irods::log(const irods::exception& e)` as it was the lowest level this change can happen at, potentially dealing with other related issues as well of client logging. I used `::ProcessType` to use the appropriate logging since `irods::log` is in the common lib.
Core and unit tests both passed.
=> [#8083] Simplify iRODS error message (4-3-stable)

scripts/setup_irods.py
This code change comes directly from the issue. It skips the prompt when unattended installs are performed. I don't think we need to test this since the change is very obvious.
I'm much more interested in adding support for unattended installation to the testing environment and catching issues during release testing.
=> [#8577] Do not prompt for server host on unattended install (main)

scripts/irods/upgrade_configuration.py, scripts/upgrade_irods.py
When attempting to downgrade from 5.0.90 to 5.0.2, the following is printed.
```
irods:~$ python3 scripts/upgrade_irods.py -v
Downgrade detected. Downgrading is unsupported, please reinstall iRODS version [5.0.90] or newer.
```
=> [#8676] Do not stacktrace on detection of server downgrade (5-0-stable)
