server/api/src/rsDataObjPhymv.cpp
=> [#3558] fix issue

lib/api/src/rcPhyPathReg.cpp
Looks like a minor error in the comment.
=> In usage comment dataObjInp_t is declared as phyPathRegInp then used as dataObjInp.

lib/core/src/miscUtil.cpp, lib/core/src/trimUtil.cpp, scripts/irods/test/resource_suite.py, scripts/irods/test/test_irsync.py
Changes made to fix the above two bugs.
=> bugs 3531 and 3554 on 4-2-stable

iRODS/lib/core/src/miscUtil.cpp, iRODS/lib/core/src/trimUtil.cpp, tests/pydevtest/resource_suite.py, tests/pydevtest/test_chunkydevtest.py, tests/pydevtest/test_iadmin.py, tests/pydevtest/test_ireg.py, tests/pydevtest/test_irsync.py, tests/pydevtest/test_resource_types.py
changes made to fix bugs 3531 and 3554.
=> bugs 3531 and 3554 for 4-1-stable

lib/core/src/miscUtil.cpp, lib/core/src/trimUtil.cpp, scripts/irods/test/resource_suite.py, scripts/irods/test/test_irsync.py
The code changes were made to fix bugs 3531 and 3554.
=> bugs 3531 and 3554

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/cache.cpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/configuration.cpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/include/cache.hpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/include/configuration.hpp, scripts/irods/test/test_rulebase.py, server/re/include/locks.hpp, server/re/src/locks.cpp
ran test suite but test_imeta_help failed,
updated icommands and run single test and it succeeded.
re-running python test suite with updated icommands
=> fix mem error

server/api/src/rsDataObjRename.cpp
This change fixes a situation where the specColl pointer member of srcDataObjInfo can be dereferenced when null because only srcDataObjInfo is null-checked before the dereference.
Slight change in the if-else tree to make it easier to read.
=> [#3679] Fix null pointer dereference in rsDataObjRename

lib/core/src/packStruct.cpp
extendPackedOutput is being used to populate outPtr in two places. If this function fails, outPtr is explicitly set to null. This change adds checks to ensure that extendPackedOuput did not fail (and, therefore, that outPtr is not null) before dereferencing outPtr.
=> [#3679] Fix dereference of null pointers in packStruct.cpp

lib/core/src/packStruct.cpp, server/core/src/physPath.cpp
This fixes a few places where null parameters are being passed into functions which do not accept null parameters for their arguments.
=> [#3678] Fix null parameters going into non-null arguments

plugins/auth/native/libnative.cpp, plugins/resources/deferred/libdeferred.cpp
Fixes the remaining usages of ASSERT_ERROR/ASSERT_PASS which can cause null pointer dereferences in certain code paths.
Note: I can try to tackle breaking up native_auth_agent_response (see comment at top of function) but I thought fixing the potential null pointer dereferences (per scanbuild) would be a better first step.
=> [#3679] Fix null pointer dereferences from ASSERT_ERROR/PASS

lib/core/src/packStruct.cpp, lib/core/src/rcMisc.cpp, plugins/auth/pam/libpam.cpp, plugins/database/src/db_plugin.cpp, plugins/database/src/general_query.cpp, plugins/database/src/low_level_odbc.cpp, plugins/database/src/mid_level_routines.cpp, plugins/resources/nonblocking/libnonblocking.cpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/functions.cpp, server/api/src/rsChkObjPermAndStat.cpp, server/api/src/rsDataObjCopy.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsDataObjUnlink.cpp, server/api/src/rsPhyPathReg.cpp, server/api/src/rsQuerySpecColl.cpp, server/api/src/rsRmColl.cpp, server/api/src/rsRuleExecDel.cpp, server/core/src/collection.cpp, server/core/src/initServer.cpp, server/core/src/irods_server_control_plane.cpp, server/core/src/objMetaOpr.cpp, server/core/src/physPath.cpp, server/core/src/rodsAgent.cpp, server/core/src/rodsConnect.cpp, server/core/src/xmsgLib.cpp, server/re/src/extractAvuMS.cpp, server/re/src/reSysDataObjOpr.cpp
Fixed many places where variables were being initialized and assigned a new value before the initial value was read.
Note: Not to go to 4-2-stable.
=> [#3711] Fix dead initializations and increments

server/api/src/rsGenQuery.cpp, server/core/src/irods_resource_manager.cpp
Added some references, autos, and consts where appropriate surrounding changes made in SHA 2f7b53e25cf8ff51ff7f69ea340234c11e1e2c93
---
Jenkins tests passed except for the one noted in #3689
=> [#3714] Minor fixes in GenQuery and resc manager

lib/core/src/rcPortalOpr.cpp, server/core/src/miscServerFunct.cpp
When returning early, boost::threads were not being rejoined in some places, which could potentially lead to memory leaks. This change switches to using boost::scoped_threads which is an RAII wrapper class for boost::thread. join() is called by default as part of the dtor if the thread is joinable.
---
=> [#3701] Use scoped_threads to avoid mem leaks

scripts/irods/test/test_iquest.py, server/api/src/rsGenQuery.cpp, server/core/src/irods_resource_manager.cpp
Cherry-picked some tweaks from master.
=> [#3714] Tweak behavior of LIKE for DATA_RESC_HIER

CMakeLists.txt, cmake/development_library.cmake, server/core/include/irods_database_factory.hpp, server/core/include/irods_generic_database_object.hpp, server/core/src/irods_database_factory.cpp, server/core/src/irods_generic_database_object.cpp
=> [#3675] add generic db type

scripts/run_tests.py
add skip_until option to test scripts
=> add skip_until option to test scripts

iRODS/server/api/src/rsDataObjChksum.cpp, tests/pydevtest/test_icommands_file_operations.py
Ensures that rodsusers cannot use admin flag. Ensures that admin flag allows for both generation and verification of checksums.
The check for user privilege in dataObjChksumAndRegInfo was added since the function is publicly available through the header file, but it is only currently called after the check in _rsDataObjChksum, so it may not be required.
=> [#3265] Fix ichksum admin flag

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_imeta_set.py
passed Jenkins test on 4-2-stable
=> [#3787] added imeta mod functionality for moving to/from blank units

plugins/database/src/db_plugin.cpp
Changed **imeta mod** command to be able to deal with zero-length units. Deleted some old code that had been commented out.
=> 4 2 stable deleting old commented-out code from db_plugin.cpp

scripts/irods/test/test_irepl.py, scripts/run_tests.py
This is the same code from the master branch, but the unused imports have been removed.
=> [#3659] Added test cases for irepl.

plugins/network/ssl/libssl.cpp, scripts/irods/test/test_ssl.py, scripts/run_tests.py
=> [#3609] Added validity check for pointer. Corrected data type for variable. Added new test.

.gitignore, lib/core/include/rodsError.h, lib/core/src/chksumUtil.cpp, lib/core/src/regUtil.cpp, plugins/resources/replication/irods_repl_rebalance.cpp, scripts/irods/test/test_ichksum.py, scripts/irods/test/test_ireg.py, scripts/run_tests.py, server/api/src/rsPhyPathReg.cpp, server/re/src/irods_re_serialization.cpp
Added the ichksum test from master as well.  Updated .gitignore to ignore .pyc files just like master.  These all passed Jenkins with the ichksum test included as well!
=> Bundle of Bug Fixes

.gitignore, lib/core/src/rodsPath.cpp, scripts/irods/test/test_ireg.py, scripts/irods/test/test_log_levels.py, server/api/src/rsPhyPathReg.cpp, server/core/src/rodsServer.cpp
[#3658] ireg and server both trim trailing slashes from physical paths
[#858] add entries into .gitignore
[#3865] Added correct treatment of ENV variable "spLogSql" in the server
=> Collection of bug fixes: [#3658] [#858] [#3865]

scripts/irods/test/test_native_rule_engine_plugin.py
Rule engine server occasionally wakes up (every 30s by default) and causes this test to erroneously record two messages to the log where it is expecting only one, causing the test to fail.
This change adjusts rule_engine_server_sleep_time_in_seconds in server_config.json to a longer period of time to avoid waking up while the test is running. The setting is restored after the test completes.
--
Jenkins tests passed before rebase on top of 96107c5cc79d47aead0eb0273a8874124d4056dc. Running again.
=> [#3689] Extend RE sleep time for test_network_pep

iRODS/lib/core/src/scanUtil.cpp, tests/pydevtest/test_iscan.py
Adapted from SHA c9ec3b37bd98a0dafabbb4c0c7b2103059b88a69
=> [#3681] Fixed iscan return codes and error messages

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iadmin.py
=> Fixes Issue 3859 - Checks parent/child resource relationship before removal

scripts/irods/test/test_irepl.py, server/api/src/rsDataObjRepl.cpp, server/core/src/dataObjOpr.cpp
=> [#3885] irepl now handles -R as specified in the documentation

cmake/development_library.cmake, lib/core/include/termiosUtil.hpp, lib/core/src/clientLogin.cpp, lib/core/src/obf.cpp, scripts/irods/test/test_ipasswd.py, scripts/irods/test/test_util.py, scripts/run_tests.py
CI test successful: http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/861/
=> [#3580] ipasswd issues (was: stty path hard-coded in clientLogin.cpp)

iRODS/lib/core/include/irods_enhanced_logger.hpp, iRODS/lib/core/include/irods_server_properties.hpp, iRODS/lib/core/src/rodsLog.cpp.src, iRODS/server/core/src/rodsAgent.cpp, iRODS/server/core/src/rsApiHandler.cpp, plugins/resources/replication/irods_create_write_replicator.cpp, plugins/resources/replication/librepl.cpp, plugins/resources/unixfilesystem/libunixfilesystem.cpp
Adds a class called enhanced_logger which holds a map of information which can be accessed by logging utilities. The feature is enabled through a new server_config.json string called `enhanced_logging`. This is simply configured by configuring the specified setting to 0 for disable, and any non-zero value for enable. Defaults to 0.
Also added some additional logging in replication resource and the unixfilesystem resource.
---
CI tests still running. Commit message needs #, too. Also remember when reviewing that 4.1.x is pre-C++11. :)
=> [#3927] Add enhanced logging server feature (4-1-stable)

scripts/irods/test/resource_suite.py, scripts/irods/test/test_auth.py, scripts/irods/test/test_resource_types.py, scripts/irods/test/test_ssl.py
3939 fixes pam tests
3779 removes roundrobin
=> tests changed

scripts/irods/test/resource_suite.py, scripts/irods/test/test_auth.py, scripts/irods/test/test_resource_types.py, scripts/irods/test/test_ssl.py
3939 pam test fixes
3779 remove roundrobin from MultiLayered tests.
=> 4-2-stable multiple test changes

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/cache.cpp
Adds a size checking guard at the front of copyCache in order to ensure a hashtable size that is greater than 0. Also adds some explanation for the calculation being done for the hashtable.
---
Thanks, @dworkin!
=> [#3932] More size checking in RE cache copying (master)

lib/core/include/rodsErrorTable.h, lib/core/src/miscUtil.cpp, lib/core/src/putUtil.cpp, lib/core/src/rcMisc.cpp, lib/core/src/rsyncUtil.cpp, scripts/irods/test/resource_suite.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_iput_options.py, scripts/irods/test/test_irepl.py, scripts/irods/test/test_irm.py, scripts/irods/test/test_itrim.py, scripts/irods/test/test_resource_types.py, scripts/run_tests.py, server/api/src/rsDataObjRepl.cpp, server/api/src/rsDataObjTrim.cpp, server/api/src/rsDataObjUnlink.cpp, server/api/src/rsRmColl.cpp, server/core/include/irods_at_scope_exit.hpp, server/core/src/dataObjOpr.cpp, server/core/src/irods_file_object.cpp
=> Bundle of Fixes for 4.2.3 (master)

lib/core/include/rodsErrorTable.h, lib/core/src/miscUtil.cpp, lib/core/src/putUtil.cpp, lib/core/src/rcMisc.cpp, lib/core/src/rsyncUtil.cpp, scripts/irods/test/resource_suite.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_iput_options.py, scripts/irods/test/test_irepl.py, scripts/irods/test/test_irm.py, scripts/irods/test/test_itrim.py, scripts/irods/test/test_resource_types.py, scripts/run_tests.py, server/api/src/rsDataObjRepl.cpp, server/api/src/rsDataObjTrim.cpp, server/api/src/rsDataObjUnlink.cpp, server/api/src/rsRmColl.cpp, server/core/include/irods_at_scope_exit.hpp, server/core/src/dataObjOpr.cpp, server/core/src/irods_file_object.cpp
=> Bundle of Fixes for 4.2.3 (4-2-stable)

plugins/database/src/general_query.cpp, scripts/irods/test/test_catalog.py, server/api/src/rsCollCreate.cpp, server/core/src/specColl.cpp
[#3913] silent failure of imkdir -p with long path containing white space
=> [#3913] silent failure of imkdir -p with long path containing white space

CMakeLists.txt, cmake/development_library.cmake, lib/core/include/irods_exception.hpp, lib/core/include/irods_path_recursion.hpp, lib/core/include/rcMisc.h, lib/core/src/irods_exception.cpp, lib/core/src/irods_path_recursion.cpp, lib/core/src/miscUtil.cpp, lib/core/src/putUtil.cpp, lib/core/src/rcMisc.cpp, lib/core/src/rsyncUtil.cpp, scripts/irods/test/test_chunkydevtest.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_iput_options.py, scripts/irods/test/test_irsync.py, scripts/irods/test/test_resource_types.py, scripts/irods/test/test_symlink_operations.py, scripts/irods/test/ustrings.py, scripts/run_tests.py
CI build 1156 passed.
CI build 1165 with final changes - passed.
=> [#3988] iput/irsync - file system loop prevention - symbolic links

scripts/irods/test/test_native_rule_engine_plugin.py, server/core/src/reServerLib.cpp
Cherry-picks of changes from #3942 and #4017 
---
[CI tests running.](http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/1169/)
=> Delay queue fixes (4-2-stable)

irods_consortium_continuous_integration_build_hook.py
=> [#3412] bump externals in CI build hook

lib/core/src/packStruct.cpp
When creating a delayed rule, a copy of the REI and top-level arguments is preserved.  Unfortunately, when one of the top level arguments is an output parameter that has not been assigned a value yet, packing would fail with the error SYS_PACK_INSTRUCT_FORMAT_ERR, preventing the delayed rule from being started.
Handle the particular case that prevented successful packing: when packing an uninitialised parameter, the `type` is a NULL pointer, and thus the type of `inOutStruct` cannot be determined. However, `inOutStruct` is also a NULL pointer, so the type is irrelevant for the purpose of packing.  Force the type to `STR_PTR_PI`.
It would be cleaner to introduce a new type for this particular purpose, something like `VOID_PTR_PI`, but such a change would affect much more code.
=> [#3906] Pack and unpack output parameters 

scripts/irods/test/test_native_rule_engine_plugin.py
Output parameter causing writeLine output in delay block to be short-circuited. Need a test to ensure messages from a delay block are written when an output variable is being used.
---
[CI tests running.](http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/1236/)
=> [#3906] Add test for output with delay block (4-2-stable)

lib/core/src/packStruct.cpp, scripts/irods/test/test_native_rule_engine_plugin.py
[#3906] Pack and unpack output parameters without value.
(cherry-picked from SHA: 886f21f)
[#3906] Add test for output with delay block
(cherry-picked from SHA: c553f66)
---
[CI tests passed](http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/1240/) before rebase. Let me know if we want to run it again.
=> #3906 cherry-pick (master)

scripts/irods/test/rule_texts_for_tests.py
fixed some typos that caused regression in PREP testing
=> [#4007] fixed regression in PREP test (for 4-2-stable)

scripts/irods/test/rule_texts_for_tests.py
Fixed typos in previous commits that caused regression.
=> [#4007] fixed regression in PREP test (for master)

server/api/src/rsPhyPathReg.cpp
When the size KW is provided in the call to rsPhyPathReg, there is no need to stat the file. As such, there is no need to redirect to the remote server at all. This also resolves an issue with stat'ing 0-length files even in the presence of the size KW.
(cherry-picked from SHA: 14a868df0fbaf9ca09b0ab13adb41da5d6a237df)
---
[CI tests running.](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1337/) Will update commit message with new SHA when 4-2-stable version is merged.
=> [#4066] Skip redirect in reg with size KW (master)

iRODS/lib/core/src/scanUtil.cpp, tests/pydevtest/test_iscan.py
(adapted from SHA: 22d55d75a53558e151185057c70049f12b03cafe)
---
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1338/)
=> [#4029] Correct checking of statPhysFile return codes in scanObjCol (4-1-stable)

scripts/irods/paths.py, scripts/run_tests.py
cherry-pick of https://github.com/irods/irods/pull/4162
=> [#4146] Added plugins test directory and 'run_plugin_tests' option

CMakeLists.txt, irods_consortium_continuous_integration_build_hook.py, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_linked_list_iterator.cmake, unit_tests/cmake/utils.cmake, unit_tests/main.cpp, unit_tests/test_irods_linked_list_iterator.cpp
Depends on: [irods/externals#14]
Passed CI.
=> [#4072] Added Catch2 unit-testing framework and one test.

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/functions.cpp, scripts/irods/test/test_federation.py
rei->msParamArray is used in smsi_remoteExec for remote execution and clears the contents after completing. This was being done in the past because state was being stored in the rule execution environment and was used to populate rei.
This has changed as of ced5dd3121ea49fa017bd29e643ab7ac287d30eb.
rei->msParamArray needs to be preserved for code executing after remoteExec.
---
[CI tests passed.](http://172.25.14.125:8080/job/irods-build-and-test-workflow/1110/) Implementation based on smsi_delayExec a few lines above these changes.
=> [#3998] Restore rei->msParamArray in remoteExec (master)

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/functions.cpp, scripts/irods/test/test_federation.py
rei->msParamArray is used in smsi_remoteExec for remote execution
and clears the contents after completing. This was being done in
the past because state was being stored in the rule execution
environment and was used to populate rei.
This has changed as of ced5dd3.
ruleExecOut is no longer being stored in the rule execution
environment. As such, rei->msParamArray needs to be preserved.
(cherry-picked from SHA: ad210e4)
---
[Passed CI tests](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1635/) ([re-ran ub16-mysql](http://172.25.14.63:8080/job/test-ub16-mysql/937/) because of CI hiccup)
=> [#3998] Preserve remoteExecOut in rei->msParamArray (4-2-stable)

scripts/irods/core_file.py, scripts/irods/test/test_iput_options.py, scripts/irods/test/test_prep_genquery_iterator.py, scripts/run_tests.py
Tested green under irods build and test workflow and Python Rule Engine b/t workflow.
Squash of around 34 subcommits mostly to do with debugging interaction with irods core code
=> wrote tests for PREP genquery iterators

lib/core/include/rodsErrorTable.h, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/arithmetics.cpp, scripts/irods/test/test_native_rule_engine_plugin.py
[CI tests running](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1660/)
(cherry-picked from 260253f3a2d5920095fe10ab5c78eda59e204a47)
=> [#4174] implement support of iRODS error codes to the rule language (master)

server/core/src/irods_api_number_validator.cpp
[Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1676/)
=> [#4202] API number validator now checks for unsupported API numbers

lib/core/include/irods_query.hpp
Fixes row_idx_ going out of bounds between page_fetch() calls by
resetting to 0 in the query iterator.
Fixes stacktrace caused by closing all statements in the statement
table in the destructor of the query implementation object. This
has been changed to only close statements generated by that query.
---
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1679/) (and [topo-resc](http://172.25.14.63:8080/job/topo-ub16-psql-resc/249/))
=> [#4204] Fix paging results and closing statements (4-2-stable)

lib/core/include/irods_query.hpp
Fixes row_idx_ going out of bounds between page_fetch() calls by
resetting to 0 in the query iterator.
Fixes stacktrace caused by closing all statements in the statement
table in the destructor of the query implementation object. This
has been changed to only close statements generated by that query.
---
(cherry-picked from SHA 9eb8435f29e1a2737d468bcb11f08105ac116c5f)
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1686/)
=> [#4204] Fix paging results and closing statements (master)

CMakeLists.txt, cmake/development_library.cmake, lib/core/include/irods_state_table.h, lib/core/src/rodsLog.cpp, plugins/rule_engines/CMakeLists.txt, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/libirods_rule_engine_plugin-irods_rule_language.cpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/rules.cpp, plugins/rule_engines/irods_rule_engine_plugin-passthrough/libirods_rule_engine_plugin-passthrough.cpp, scripts/irods/test/test_rule_engine_plugin_framework.py, scripts/irods/test/test_rule_engine_plugin_passthrough.py, scripts/run_tests.py, scripts/setup_irods.py, server/core/src/irods_logger.cpp, server/core/src/rodsAgent.cpp, server/core/src/rodsServer.cpp, server/re/include/irods_re_plugin.hpp, unit_tests/cmake/test_config/irods_linked_list_iterator.cmake
Please review the python test, including it's name.
Are we satisfied with the error codes used in the Passthrough REP?
Should an issue be created for additions to rodsAgent.cpp?
I added lines to set the log levels for each logger category.
[Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1700/)
=> Rule Engine Plugin Framework now supports continuation

scripts/irods/test/test_irule.py, scripts/run_tests.py
Pending successful test on issue [#4189]
Test is: (http://172.25.14.63:8080/job/irods-build-and-test-workflow/1698/)
Dependent on: [this icommands feature branch](https://github.com/d-w-moore/irods_client_icommands/tree/irule_inpparam_fix)
=> Irule inpparam fix test

scripts/irods/test/test_irule.py, scripts/run_tests.py
Before merging, reference the notes on the corresponding the [icommands (*irule*) fix](https://github.com/irods/irods_client_icommands/compare/master...d-w-moore:irule_inpparam_fix_on_master?expand=1):  the [test](  http://172.25.14.63:8080/job/irods-build-and-test-workflow/1708) underway in CI should be allowed to complete successfully.
=> [#4189] test for irule fix regarding bad inpParam

scripts/irods/test/test_rule_engine_plugin_passthrough.py
[Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1726/)
=> [#4226] [4-2-stable] Skip Passthrough REP test.

scripts/irods/test/test_rule_engine_plugin_passthrough.py
[Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1727/)
=> [#4226] [master] Skip Passthrough REP test.

lib/core/src/obf.cpp, plugins/database/src/db_plugin.cpp, scripts/irods/password_obfuscation.py, scripts/irods/test/test_ipasswd.py, scripts/setup_irods.py
cherry-pick of c2174ca6b8ec808439c7b1088882c44b8610fefb
=> [#3972] corrected and enforced size limit on passwords (master)

lib/core/include/irods_query.hpp, lib/core/src/connection_pool.cpp, server/core/src/irodsReServer.cpp
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1813/flowGraphTable/)
=> [#4296] Template irods_query class (4-2-stable)

lib/core/include/irods_query.hpp, lib/core/src/connection_pool.cpp, server/core/src/irodsReServer.cpp
(cherry-picked from db085559893dabcb8e3acd30dbd7c4b65bc110dc)
=> [#4296] Template irods_query class (master)

cmake/server.cmake, packaging/irods.logrotate, packaging/irods.rsyslog, packaging/postinstall.sh, packaging/server_log_setup_instructions.txt, preinst, scripts/irods/controller.py, scripts/irods/logging_infrastructure.py, scripts/setup_irods.py, scripts/setup_rsyslog_and_logrotate.py
- Fixed preinst script bug: "upgrade.tmp" was not being created.
=> [#4310] Added script that configures rsyslog, logrotate, etc. (master)

lib/core/src/putUtil.cpp, packaging/irods.rsyslog, plugins/resources/unixfilesystem/libunixfilesystem.cpp, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_native_rule_engine_plugin.py, scripts/irods/test/test_resource_types.py, server/core/src/irods_report_plugins_in_json.cpp
[CI tests running](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1924/)
=> [#4345] Fix tests failing after logging changes (master)

plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/functions.cpp, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_native_rule_engine_plugin.py, server/core/src/irodsReServer.cpp
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1938/)
=> [#4351] Make delay server more resilient (master)

CMakeLists.txt, lib/core/include/irods_query.hpp, lib/core/src/packStruct.cpp, plugins/rule_engines/CMakeLists.txt, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/include/reFuncDefs.hpp, server/core/src/irodsReServer.cpp, server/re/include/irods_re_structs.hpp, server/re/src/reStruct.cpp
Query iterator and several places in the delay server itself had leaks
detected in Valgrind.
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1967/)
=> [#1376] Fix memory leaks detected in delay server (master)

cmake/development_library.cmake, lib/core/include/query_processor.hpp, lib/core/include/rodsErrorTable.h
Also adds a new error code for situations where the error is unknown.
[Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1998/)
=> [#4369] Added new query_processor library (master)

cmake/development_library.cmake, lib/core/include/query_processor.hpp, lib/core/include/rodsErrorTable.h
Also adds a new error code for situations where the error is unknown.
[Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/2006/)
Passed in Docker.
=> [#4369] Added new query_processor library (4-2-stable)

lib/core/src/fsckUtil.cpp, scripts/irods/test/test_ifsck.py, scripts/run_tests.py
[Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/2012/) and Docker.
=> [#4391] Fixed integer overflow for ifsck (4-2-stable)

lib/core/src/fsckUtil.cpp, scripts/irods/test/test_ifsck.py, scripts/run_tests.py
[Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/2013/) (centos 7 - journald suppressed expected output) and Docker.
=> [#4391] Fixed integer overflow for ifsck (master)

cmake/runtime_library.cmake, cmake/server.cmake
this makes it required for both server and clients
=> [4390] move libxml2 dependency to runtime package (4-2-stable)

cmake/runtime_library.cmake, cmake/server.cmake
this makes it required for both server and clients
=> [4390] move libxml2 dependency to runtime package (master)

plugins/rule_engines/irods_rule_engine_plugin-passthrough/libirods_rule_engine_plugin-passthrough.cpp, scripts/irods/test/test_rule_engine_plugin_framework.py, scripts/irods/test/test_rule_engine_plugin_passthrough.py, server/re/include/irods_re_plugin.hpp
- [Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/2052/)
- Passed Docker
=> [#4383] REPF no longer executes rule code as a microservice on continuation (master)

plugins/rule_engines/irods_rule_engine_plugin-passthrough/libirods_rule_engine_plugin-passthrough.cpp, scripts/irods/test/test_rule_engine_plugin_framework.py, scripts/irods/test/test_rule_engine_plugin_passthrough.py, server/re/include/irods_re_plugin.hpp
- [Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/2053/)
- Passed Docker
=> [#4383] REPF no longer executes rule code as a microservice on continuation (4-2-stable)

lib/core/include/apiHandler.hpp, scripts/irods/test/test_native_rule_engine_plugin.py
All tests passed in CI : 
http://172.25.14.63:8080/job/irods-build-and-test-workflow/2046/
=> [#4404] fix conflation of info/error in API handler

CMakeLists.txt, lib/core/src/rmdirUtil.cpp, scripts/irods/test/test_irmdir.py
[Passed CI with false positive](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/2110/)
=> [#4153] irmdir now properly handles "-p" (4-2-stable)

CMakeLists.txt, lib/core/src/rmdirUtil.cpp, scripts/irods/test/test_irmdir.py
[Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/2109/)
=> [#4153] irmdir now properly handles "-p" (master)

lib/core/src/rcConnect.cpp, scripts/irods/test/test_misc.py, scripts/run_tests.py, server/core/src/initServer.cpp
[Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/2096/)
=> [#4130] Return error on invalid irodsProt value (master)

lib/core/src/rcConnect.cpp, scripts/irods/test/test_misc.py, scripts/run_tests.py, server/core/src/initServer.cpp
[Passed CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/2097/)
=> [#4130] Return error on invalid irodsProt value (4-2-stable)

lib/core/include/rodsErrorTable.h, scripts/irods/test/test_iadmin.py, server/api/src/rsGeneralAdmin.cpp
Docker - Passed
[CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/2105/) - Passed
=> [#4363] Return error when adding child resource creates a hierarchy cycle (4-2-stable)

lib/core/include/rodsErrorTable.h, scripts/irods/test/test_iadmin.py, server/api/src/rsGeneralAdmin.cpp
Docker - Passed
[CI](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/2104/) - Passed (with false positive)
=> [#4363] Return error when adding child resource creates a hierarchy cycle (master)

lib/core/include/rodsPath.h, lib/core/src/lsUtil.cpp, lib/core/src/rodsPath.cpp, scripts/core_tests_list.json, scripts/irods/test/test_ipwd.py
Passed in new CI (core tests only)
=> [#4060] Paths now escape '\f' character (master)

lib/core/src/lsUtil.cpp
=> [#4476] Fix ils -A not showing permissions (master)

scripts/irods/test/test_all_rules.py, scripts/irods/test/test_ibun.py
=> [#4495] Prevent infinite copytree in ibun test (master)

scripts/irods/test/test_all_rules.py, scripts/irods/test/test_ibun.py
=> [#4495] Prevent infinite copytree in ibun test (4-2-stable)

lib/filesystem/src/filesystem.cpp, unit_tests/src/filesystem/test_filesystem.cpp
=> [#4542] Fixed irods::filesystem::get_metadata() collection query (master)

lib/filesystem/src/filesystem.cpp, unit_tests/src/filesystem/test_filesystem.cpp
=> [#4542] Fixed irods::filesystem::get_metadata() collection query (4-2-stable)

lib/filesystem/src/filesystem.cpp, lib/filesystem/src/path.cpp, unit_tests/src/filesystem/test_filesystem.cpp, unit_tests/src/filesystem/test_path.cpp
=> [#4551] irods::filesystem::path::parent_path() is compliant with the standard (master)

irods_consortium_continuous_integration_build_hook.py, unit_tests/unit_tests_list.json
Passed CI using irods/irods_testing_jenkins#38.
=> [#4555] Added support for unit-tests in CI (4-2-stable)

irods_consortium_continuous_integration_build_hook.py, unit_tests/CMakeLists.txt, unit_tests/unit_tests_list.json
Passed CI using irods/irods_testing_jenkins#38.
=> [#4555][#4556] Added support for unit-tests in CI (master)

lib/core/include/connection_pool.hpp, lib/core/src/connection_pool.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_connection_pool.cmake, unit_tests/src/test_connection_pool.cpp, unit_tests/unit_tests_list.json
=> [#4566] Connections can now be released from a connection pool (master)

lib/core/include/connection_pool.hpp, lib/core/src/connection_pool.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_connection_pool.cmake, unit_tests/src/test_connection_pool.cpp, unit_tests/unit_tests_list.json
=> [#4566] Connections can now be released from a connection pool (4-2-stable)

cmake/development_library.cmake, lib/core/include/irods_query.hpp, lib/core/include/query_builder.hpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_query_builder.cmake, unit_tests/src/test_query_builder.cpp, unit_tests/unit_tests_list.json
=> [#4493][#4573][#4574] irods::query now accepts a zone hint (4-2-stable)

cmake/development_library.cmake, lib/core/include/irods_query.hpp, lib/core/include/query_builder.hpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_query_builder.cmake, unit_tests/src/test_query_builder.cpp, unit_tests/unit_tests_list.json
=> [#4493][#4573][#4574] irods::query now accepts a zone hint (master)

lib/filesystem/src/filesystem.cpp
=> [#4570] Zone hint is now set in irods::experimental::filesystem::status (master)

lib/filesystem/src/filesystem.cpp
=> [#4570] Zone hint is now set in irods::experimental::filesystem::status (4-2-stable)

lib/core/src/irods_parse_command_line_options.cpp, scripts/irods/test/test_iput_options.py
=> [#4657] Do not set bulk flag with force flag (master)

lib/core/src/irods_parse_command_line_options.cpp, scripts/irods/test/test_iput_options.py
=> [#4657] Do not set bulk flag with force flag (4-2-stable)

scripts/irods/test/test_irm.py, server/api/src/rsDataObjUnlink.cpp
=> [#4510] Disallow rodsusers irm -U'ing vault data (4-2-stable)

scripts/irods/test/test_irm.py, server/api/src/rsDataObjUnlink.cpp
=> [#4510] Disallow rodsusers irm -U'ing vault data (master)

scripts/irods/test/test_catalog.py, scripts/irods/test/test_iuserinfo.py
=> Fix a couple of tests (4-2-stable)

scripts/irods/test/test_catalog.py, scripts/irods/test/test_iuserinfo.py
=> Fix a couple of tests (master)

lib/core/src/rmUtil.cpp, lib/core/src/trimUtil.cpp, plugins/database/src/db_plugin.cpp, scripts/irods/lib.py, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_control_plane.py, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_dynamic_peps.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_ireg.py, scripts/irods/test/test_irm.py, scripts/irods/test/test_irule.py, scripts/irods/test/test_iunreg.py, scripts/irods/test/test_log_levels.py, scripts/irods/test/test_native_rule_engine_plugin.py, scripts/irods/test/test_resource_types.py, scripts/irods/test/test_rule_engine_plugin_framework.py, scripts/irods/test/test_rulebase.py, server/api/src/rsDataObjUnlink.cpp, server/api/src/rsRmColl.cpp
CI tests are running
Requires irods/irods_client_icommands#114
=> [#4506] Add support for iunreg + fix tests checking logs (4-2-stable)

lib/core/include/connection_pool.hpp, lib/core/src/connection_pool.cpp, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_delay_queue.py, server/core/src/irodsReServer.cpp, server/core/src/irods_server_control_plane.cpp
=> [#4616][#4430] Implement delay server as query processor (4-2-stable)

cmake/development_library.cmake, lib/core/include/rodsKeyWdDef.h, lib/core/include/rodsPath.h, lib/core/src/rodsPath.cpp, plugins/database/src/db_plugin.cpp, scripts/irods/test/test_chunkydevtest.py, scripts/irods/test/test_iadmin.py
Some cleanup in the mod_data_obj_meta database op.
---
=> [#4740] Add support for iadmin modrepl (master)

cmake/development_library.cmake, lib/core/include/rodsKeyWdDef.h, lib/core/include/rodsPath.h, lib/core/src/rodsPath.cpp, plugins/database/src/db_plugin.cpp, scripts/irods/test/test_chunkydevtest.py, scripts/irods/test/test_iadmin.py
Some cleanup in the mod_data_obj_meta database op.
---
CI tests running.
=> [#4740] Add support for iadmin modrepl (4-2-stable)

scripts/irods/test/test_all_rules.py
=> [#3234] Add test for msiDataObjPhymv to hierarchy (master)

scripts/irods/test/test_all_rules.py
=> [#3234] Add test for msiDataObjPhymv to hierarchy (4-2-stable)

scripts/core_tests_list.json, scripts/irods/test/test_delay_queue.py, server/re/src/reSysDataObjOpr.cpp
=> [#4615] Deprecate msiSysChksumDataObj (master)

scripts/core_tests_list.json, scripts/irods/test/test_delay_queue.py, server/re/src/reSysDataObjOpr.cpp
=> [#4615] Deprecate msiSysChksumDataObj (4-2-stable)

packaging/example_cpp_default_delayed_invocation.r, plugins/rule_engines/irods_rule_engine_plugin-cpp_default_policy/libirods_rule_engine_plugin-cpp_default_policy.cpp, scripts/irods/test/test_rule_engine_plugin_framework.py, server/api/src/rsExecMyRule.cpp
=> cpp default rule execution  4668 (4-2-stable)

scripts/irods/test/test_prep_genquery_iterator.py
Tests for [irods/irods_rule_engine_plugin_python#38]
=> Genquery cjsmeele master

scripts/irods/test/test_prep_genquery_iterator.py
Tests for PR [irods/irods_rule_engine_plugin_python#39], porting PREP master branch changes incl @cjsmeele's commit from [irods/irods_rule_engine_plugin_python#34] (now superceded, can be closed) plus doc and functionality improvements
=> Genquery cjsmeele 4 2 stable

scripts/irods/test/test_irepl.py
=> [#4479] Add irepl path_with_no_perms test (master)

scripts/irods/test/test_irepl.py
=> [#4479] Add irepl path_with_no_perms test (4-2-stable)

scripts/irods/test/test_resource_types.py
Accompanied by irods/irods_testing_jenkins#67, the tests pass in CI.
=> Revert "[#4727] Skip Test_Resource_Replication_With_Retry" (master)

plugins/database/src/db_plugin.cpp
The following query has been running for over 15 days on a system with ~8M records and two replicas.
```select distinct data_id from R_DATA_MAIN where data_id in (select data_id from R_DATA_MAIN where resc_id in (10016)) and data_id not in (select data_id from R_DATA_MAIN where resc_id in (10014)) and modify_ts <= '01571939628' limit 500```
Rewriting the query to use `EXCEPT` for the set math seems much faster, returning results in about 70 seconds. The change is implemented in this PR.
This PR is submitted as draft, as I have not tested iRODS with this change. I'd appreciate a review from someone who understands the spirit of the query.
=> Slow rebalance with iRODS 4.2.4 and PostgreSQL 11.1

server/api/src/rsDataObjCopy.cpp
tests in PRC suite [PR for 196](https://github.com/irods/python-irodsclient/pull/196)
=> [#4796] do not copy invalid object paths

plugins/resources/replication/librepl.cpp, scripts/irods/test/test_resource_types.py
=> [#4775] Remove num_repl from replication resource (master)

plugins/resources/replication/librepl.cpp
=> [#3548] Deprecate num_repl keyword (4-2-stable)

lib/core/include/thread_pool.hpp
Just `git checkout`'d the file from master branch.
=> [#4824] Use boost::asio::thread_pool in irods::thread_pool (4-2-stable)

scripts/irods/test/test_ichksum.py, server/api/src/rsDataObjChksum.cpp
Will soon be ready for merge - pending successful CI testing and review.
=> [#4732] (4-2-stable) use query iterator for proper cleanup

scripts/irods/test/test_ichksum.py, server/api/src/rsDataObjChksum.cpp
Will soon be ready for merge - pending successful CI testing and review.
=> [#4732] (master) use query iterator for proper cleanup

scripts/core_tests_list.json, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_icp.py, server/api/include/rsDataObjCopy.hpp, server/api/src/rsDataObjCopy.cpp
CI tests passed. Cherry-picked from #4878 commits.
=> [#4862] Ensure data objects close in rsDataObjCopy (4-2-stable)

scripts/core_tests_list.json, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_icp.py, server/api/include/rsDataObjCopy.hpp, server/api/src/rsDataObjCopy.cpp
=> [#4862] Ensure data objects close in rsDataObjCopy (master)

scripts/irods/test/resource_suite.py, scripts/irods/test/test_chunkydevtest.py, scripts/irods/test/test_iput_options.py, scripts/irods/test/test_resource_types.py
about specifying minimum number of replicas to keep
=> [4860] Updated test cases for deprecated message

CMakeLists.txt, lib/filesystem/include/filesystem/filesystem.hpp, lib/filesystem/src/filesystem.cpp, unit_tests/src/filesystem/test_filesystem.cpp
=> [#4890] Added new filesystem function - add_metadata (4-2-stable)

CMakeLists.txt, lib/filesystem/include/filesystem/filesystem.hpp, lib/filesystem/src/filesystem.cpp, unit_tests/src/filesystem/test_filesystem.cpp
=> [#4890] Added new filesystem function - add_metadata (master)

cmake/development_library.cmake, lib/api/include/atomic_apply_metadata_operations.h, lib/filesystem/include/filesystem/config.hpp, lib/filesystem/include/filesystem/filesystem.hpp, lib/filesystem/include/filesystem/filesystem.tpp, lib/filesystem/src/filesystem.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, server/api/include/rs_atomic_apply_metadata_operations.hpp, unit_tests/src/filesystem/test_filesystem.cpp, unit_tests/src/test_atomic_apply_metadata_operations.cpp
=> [#4898] Filesystem library now supports atomic bulk metadata operations (master)

cmake/development_library.cmake, lib/api/include/atomic_apply_metadata_operations.h, lib/filesystem/include/filesystem/config.hpp, lib/filesystem/include/filesystem/filesystem.hpp, lib/filesystem/include/filesystem/filesystem.tpp, lib/filesystem/src/filesystem.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, server/api/include/rs_atomic_apply_metadata_operations.hpp, unit_tests/src/filesystem/test_filesystem.cpp, unit_tests/src/test_atomic_apply_metadata_operations.cpp
=> [#4898] Filesystem library now supports atomic bulk metadata operations (4-2-stable)

scripts/irods/test/test_all_rules.py
Modified single test, which passes.
=> [#4898] Replace set with add in msi_atomic_apply_metadata_operations test (4-2-stable)

scripts/irods/test/test_all_rules.py
Modified single test, which passes.
=> [#4898] Replace set with add in msi_atomic_apply_metadata_operations test (master)

scripts/irods/test/test_federation.py
=> [#4426] Added federation test for imeta -z qu (4-2-stable)

doxygen/microservices.cpp, scripts/irods/test/test_all_rules.py, server/re/include/reAction.hpp, server/re/include/reSysDataObjOpr.hpp, server/re/src/reSysDataObjOpr.cpp
=> [#4408] Remove msiSetMultiReplPerResc (master)

lib/api/src/rcDataObjPut.cpp, lib/core/src/rsyncUtil.cpp
=> [4987] add file size

CMakeLists.txt, plugins/api/src/atomic_apply_metadata_operations.cpp, server/core/include/catalog.hpp, server/core/include/catalog_utilities.hpp, server/core/src/catalog.cpp, server/core/src/catalog_utilities.cpp, server/re/src/extractAvuMS.cpp
CI tests running. cherry-picked from commits in #5009
=> [#5011] Add catalog utility libraries (4-2-stable)

scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_icommands_file_operations.py
=> test for python rule engine issue #55 fix (master)

lib/core/include/irods_hierarchy_parser.hpp, lib/core/src/irods_hierarchy_parser.cpp, unit_tests/src/test_irods_hierarchy_parser.cpp
=> [#5057] Add add_parent to hierarchy_parser (4-2-stable)

lib/core/include/irods_hierarchy_parser.hpp, lib/core/src/irods_hierarchy_parser.cpp, unit_tests/src/test_irods_hierarchy_parser.cpp
=> [#5057] Add add_parent to hierarchy_parser (master)

lib/core/include/irods_query.hpp, lib/core/src/rcMisc.cpp, lib/core/src/resource_administration.cpp, lib/core/src/user_administration.cpp, lib/filesystem/src/filesystem.cpp, plugins/api/src/atomic_apply_acl_operations.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, scripts/irods/test/test_misc.py, server/api/src/rsDataObjChksum.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjUnlink.cpp, server/api/src/rsPhyPathReg.cpp
This change may require updates to any code that used `irods::query`.
=> DNS bug fix and macros (4-2-stable)

server/api/src/rsDataObjRepl.cpp, server/api/src/rsFileChksum.cpp
This reverts commit 3cd13dd0f7e13536011a65390acdef7e3093af9a.
=> Revert "[#5078] add file size to L1Desc for repl" (master)

server/api/src/rsDataObjRepl.cpp, server/api/src/rsFileChksum.cpp
This reverts commit 33abdf6d08e7a8712bc68c9fd2ab77973f71516a.
=> Revert "[#5078] add file size to L1Desc for repl" (4-2-stable)

lib/core/include/lifetime_manager.hpp, lib/core/include/replica_proxy.hpp, server/api/include/rsPhyBundleColl.hpp, server/api/src/rsChkObjPermAndStat.cpp, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsPhyBundleColl.cpp, server/api/src/rsPhyPathReg.cpp, server/core/include/irods_get_l1desc.hpp, server/core/src/irods_get_l1desc.cpp, unit_tests/src/test_irods_key_value_proxy.cpp, unit_tests/src/test_irods_lifetime_manager.cpp
=> Fix rsPhyPathReg for create + lifetime_manager tweaks + suppress some non-error log messages (4-2-stable)

scripts/irods/test/test_imeta_set.py
This is a companion pull request to irods/irods_client_icommands#155.
I've added a test case for the long mode output from `imeta ls` on the supported object types.
=> [#5111] add test to verify existence of mtime in imeta ls -l output (master)

scripts/irods/test/test_imeta_set.py
This is a companion pull request to irods/irods_client_icommands#156
=> [#5111] add test to verify existence of mtime in imeta ls -l output (4-2-stable)

plugins/microservices/CMakeLists.txt, plugins/microservices/msi_get_agent_pid/CMakeLists.txt, plugins/microservices/msi_get_agent_pid/libmsi_get_agent_pid.cpp, plugins/resources/replication/irods_create_write_replicator.cpp, plugins/resources/replication/irods_repl_retry.cpp, scripts/irods/lib.py, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_native_rule_engine_plugin.py, scripts/irods/test/test_resource_types.py, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjRepl.cpp
=> Remove some server log reading in tests (4-2-stable)

lib/core/src/rodsPath.cpp, scripts/core_tests_list.json, scripts/irods/test/command.py, scripts/irods/test/test_imeta_error_handling.py, scripts/irods/test/test_imeta_set.py
This is a companion PR to irods/irods_client_icommands#162
#5190 cherry-picked into stable
The following issues are addressed by this PR:
- #5021
- #5101
- #5102
- #5184
- #5185
- #5186
=> [#5021,#5101,#5102,#5184,#5185,#5186] imeta error handling fixes and tests (4-2-stable)

scripts/core_tests_list.json, scripts/irods/test/test_catalog.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_izonereport.py, server/core/src/irods_report_plugins_in_json.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_zone_report.cmake, unit_tests/src/test_zone_report.cpp, unit_tests/unit_tests_list.json
#5173 cherry-picked into stable.
Addresses #5170.
Tests are running in jenkins, will update when done
=> [#5170] Add id to resource json serialization (4-2-stable)

scripts/core_tests_list.json, scripts/irods/test/test_imeta_interactive.py
Companion pull request for irods/irods_client_icommands#163
A few tests for interactive `imeta`
Addresses #5081
=> [#5081] Add test class for interactive imeta (master)

CMakeLists.txt, lib/core/include/dstream.hpp, lib/core/src/packStruct.cpp, lib/core/src/rcMisc.cpp, lib/filesystem/include/filesystem/path_traits.hpp, plugins/resources/structfile/libstructfile.cpp, unit_tests/src/filesystem/test_path.cpp, unit_tests/src/test_irods_lifetime_manager.cpp, unit_tests/src/test_irods_linked_list_iterator.cpp
Polished up the changes I've made to my local clone so that I can build with the version of clang I have installed.
I've verified that clang 6 is still happy, too.
See the individual commit messages for more information.
Addresses #5213
=> [#5213] Make Clang 10 happy (master)

.travis.yml, CMakeLists.txt, irods_consortium_continuous_integration_build_hook.py, lib/core/include/irods_client_server_negotiation.hpp, lib/core/src/irods_client_negotiation.cpp, unit_tests/CMakeLists.txt
Waiting for CI tests to complete.
=> Optimized build for Travis-CI (4-2-stable)

.travis.yml, CMakeLists.txt, irods_consortium_continuous_integration_build_hook.py, lib/core/include/irods_client_server_negotiation.hpp, lib/core/src/irods_client_negotiation.cpp, unit_tests/CMakeLists.txt
=> Optimized build for Travis-CI (master)

lib/core/include/data_object_proxy.hpp, lib/core/include/replica.hpp, lib/core/include/replica_proxy.hpp, server/api/src/rsRmColl.cpp, server/core/include/irods_file_object.hpp, server/core/include/irods_physical_object.hpp, server/core/include/irods_resource_manager.hpp, server/core/src/irods_file_object.cpp, server/core/src/irods_physical_object.cpp, server/core/src/irods_resource_manager.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_rc_data_obj.cmake, unit_tests/src/test_data_object_proxy.cpp, unit_tests/src/test_rc_data_obj.cpp, unit_tests/src/test_replica.cpp
replica_state_table to follow later...
=> Miscellaneous machinery in run up to logical locking (master)

lib/core/include/data_object_proxy.hpp, lib/core/include/replica.hpp, lib/core/include/replica_proxy.hpp, scripts/core_tests_list.json, server/api/src/rsRmColl.cpp, server/core/include/irods_file_object.hpp, server/core/include/irods_physical_object.hpp, server/core/include/irods_resource_manager.hpp, server/core/src/irods_file_object.cpp, server/core/src/irods_physical_object.cpp, server/core/src/irods_resource_manager.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_rc_data_obj.cmake, unit_tests/src/test_data_object_proxy.cpp, unit_tests/src/test_rc_data_obj.cpp, unit_tests/src/test_replica.cpp
=> Miscellaneous machinery in run-up to logical locking (4-2-stable)

scripts/core_tests_list.json
=> [#858] Remove Test_Resource_Replication_With_Retry from core_tests_list.json (master)

lib/core/src/replUtil.cpp, plugins/resources/replication/irods_repl_retry.cpp, scripts/irods/test/test_irepl.py, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjCopy.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjRepl.cpp
CI tests are running...
**Read:**
A large number of tests are being added and *skipped* in this PR which are going to lay the groundwork for fixing `irepl` and its various modes of operation. It covers a large matrix of source/destination options and resource hierarchy configurations with expected outputs.
=> [#5263] Fix size/checksum mismatch handling (master)

lib/core/src/replUtil.cpp, plugins/resources/replication/irods_repl_retry.cpp, scripts/irods/test/test_irepl.py, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjCopy.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjRepl.cpp
=> [#5263] Fix size/checksum mismatch handling (4-2-stable)

server/api/src/rsDataObjClose.cpp
CI tests running.
A note about the TODO: This is technically incorrect as we need to check for the expected size of the replica before we determine that it is good. This PR will restore the historical behavior of assuming new replicas with no bytes written are good. Future changes will require more vetting with respect to the expected size of the replica.
=> [#5193] Mark newly created replicas as good with no bytes written (4-2-stable)

scripts/irods/test/test_istream.py
The test for irods/irods_client_icommands#176
=> [#5294] Added test for istream (4-2-stable)

scripts/irods/test/test_istream.py
The test for irods/irods_client_icommands#175
=> [#5294] Added test for istream (master)

CMakeLists.txt
Fixes #5301
Suggestions for a shorter commit message are welcome
=> [#5301] Make ninja happy (master)

lib/api/include/dataObjChksum.h, lib/api/src/rcDataObjChksum.cpp, lib/core/include/parseCommandLine.h, lib/core/include/rodsClient.h, lib/core/include/rodsError.h, lib/core/include/rodsErrorTable.h, lib/core/include/rodsKeyWdDef.h, lib/core/src/chksumUtil.cpp, lib/core/src/parseCommandLine.cpp, scripts/irods/test/test_chunkydevtest.py, scripts/irods/test/test_ichksum.py, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_irsync.py, scripts/irods/test/test_resource_types.py, server/api/include/rsDataObjChksum.hpp, server/api/src/rsBulkDataObjPut.cpp, server/api/src/rsDataObjChksum.cpp, server/api/src/rsDataObjPut.cpp, unit_tests/src/test_rc_data_obj.cpp
Needs to be run through CI.
However, all tests in `test_ichksum.py` pass.
=> [#5251][#5252] Fixed the checksum API (master)

lib/filesystem/src/filesystem.cpp
=> [#5319] Filesystem library deallocates memory correctly for C structures (master)

scripts/irods/test/test_misc.py, server/core/src/rodsServer.cpp
=> [#5224] Server removes leftover rulebase files on startup (master)

scripts/irods/test/test_misc.py, server/core/src/rodsServer.cpp
=> [#5224] Server removes leftover rulebase files on startup (4-2-stable)

lib/api/include/specificQuery.h, lib/core/include/irods_query.hpp, lib/core/include/query_processor.hpp, lib/core/include/replica.hpp, lib/core/include/transport/default_transport.hpp, lib/core/src/chksumUtil.cpp, scripts/irods/test/test_ichksum.py, unit_tests/src/filesystem/test_filesystem.cpp, unit_tests/src/test_get_file_descriptor_info.cpp
This change will likely break code using the `query_processor` due to a change in the interface. Fixing the broken plugins, etc. should be an easy fix.
=> Fixed memory leaks and ichksum -r output (master)

scripts/irods/controller.py, scripts/irods/execute.py, scripts/irods/start_options.py, scripts/irods_control.py, scripts/setup_irods.py
Fixes #5356
Fixes #5361 for master
Addresses the main concern of #5363 for master
=> [#5356,#5361,#5363] script output fixes (master)

scripts/irods/start_options.py, scripts/irods_control.py, scripts/setup_irods.py
Cherry-pick of #5357 (minus last commit) into stable
Fixes #5361 for stable
Addresses the main concern of #5363 for stable
=> [#5361,#5363] script output fixes (4-2-stable)

scripts/irods/test/test_iquest.py, scripts/irods/test/test_iticket.py
=> [#4887][#4744] Added tests for iquest and iticket (4-2-stable)

scripts/irods/test/test_iquest.py, scripts/irods/test/test_iticket.py
=> [#4887][#4744] Added tests for iquest and iticket (master)

scripts/irods/test/test_irodsctl.py
=> [#5386] Fixed irodsctl CI tests (master)

scripts/irods/test/test_irodsctl.py
=> [#5386] Fixed irodsctl CI tests (4-2-stable)

scripts/irods/test/test_iput_options.py, server/api/src/rsBulkDataObjPut.cpp
=> [#5288] Checksums are now stored in catalog on bulk upload (master)

scripts/irods/test/test_iput_options.py, server/api/src/rsBulkDataObjPut.cpp
=> [#5288] Checksums are now stored in catalog on bulk upload (4-2-stable)

lib/core/include/lifetime_manager.hpp, scripts/irods/test/test_dynamic_peps.py, server/re/src/irods_re_serialization.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_re_serialization.cmake, unit_tests/src/test_re_serialization.cpp, unit_tests/unit_tests_list.json
Hi,
As discussed previously, here's a pull request with the serializer for openedDataObjInp_t.
- ilari
=> Add serializers for data types openedDataObjInp_t and bytesBuf_t

CMakeLists.txt, lib/hasher/include/ADLER32Strategy.hpp, lib/hasher/include/HashStrategy.hpp, lib/hasher/include/MD5Strategy.hpp, lib/hasher/include/SHA1Strategy.hpp, lib/hasher/include/SHA512Strategy.hpp, lib/hasher/include/checksum.hpp, lib/hasher/src/ADLER32Strategy.cpp, lib/hasher/src/MD5Strategy.cpp, lib/hasher/src/SHA1Strategy.cpp, lib/hasher/src/SHA256Strategy.cpp, lib/hasher/src/SHA512Strategy.cpp, lib/hasher/src/irods_hasher_factory.cpp, server/api/src/rsFileChksum.cpp
see [irods/irods_client_globus_connector#9]
sha512
sha1
adler32
=> [5392] added additional hash algorithms

scripts/irods/controller.py
Clean up shared memory on startup and shutdown of server.
=> delete s3 shmem files on startup/shutdown

scripts/irods/test/test_icp.py, scripts/irods/test/test_iphymv.py, scripts/irods/test/test_irepl.py, server/api/src/rsDataObjCopy.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjRepl.cpp
Cherry-picked from changes in #5480
=> [#5478] Set numThreads in rsDataObjCopy/Repl/Phymv (4-2-stable)

scripts/irods/test/test_icp.py, scripts/irods/test/test_iphymv.py, scripts/irods/test/test_irepl.py, server/api/src/rsDataObjCopy.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjRepl.cpp
=> [#5478] Set numThreads in rsDataObjCopy/Repl/Phymv (master)

lib/core/include/rcMisc.h, lib/core/src/rcMisc.cpp, scripts/irods/test/test_rule_engine_plugin_framework.py, server/re/src/irods_re_structs.cpp, server/re/src/reSysDataObjOpr.cpp
Test passes at bench, now running in CI
=> [4055] Restore effect of time units s,m,h,d,y for delayExec PLUSET tag - 4-2-stable

scripts/irods/test/test_all_rules.py, server/re/src/genQueryMS.cpp
this is a workaround until the new parser lands
test passes
=> [4697] change genQuery SELECT to select (4-2-stable)

scripts/irods/test/test_all_rules.py, server/re/src/genQueryMS.cpp
this is a workaround until the new parser lands
test passes
=> [4697] change genQuery SELECT to select (master)

scripts/irods/test/test_iphymv.py
Demonstrates that `iphymv` can move replicas within hierarchies.
Tests passed
=> [#4212] Add more assertions to phymv tests in hierarchies (master)

scripts/irods/test/test_iphymv.py
Ensures that the tests assert correctness in replica location and
statuses before and after phymvs occur in hierarchies.
---
cherry-picked from changes in #5550. Running tests
=> [#4212] Add more assertions to phymv tests in hierarchies (4-2-stable)

lib/core/include/irods_configuration_parser.hpp, lib/core/include/irods_load_plugin.hpp, lib/core/include/irods_server_properties.hpp, lib/core/src/irods_configuration_parser.cpp, lib/core/src/rcMisc.cpp, lib/core/src/rmUtil.cpp, lib/core/src/sockComm.cpp, scripts/irods/test/test_irm.py, server/api/src/rsDataObjOpen.cpp, server/api/src/rsGenQuery.cpp, server/core/src/client_api_whitelist.cpp, server/core/src/dataObjOpr.cpp
=> Little fixes (4-2-stable)

lib/core/include/irods_configuration_parser.hpp, lib/core/include/irods_load_plugin.hpp, lib/core/include/irods_server_properties.hpp, lib/core/src/irods_configuration_parser.cpp, lib/core/src/rcMisc.cpp, lib/core/src/rmUtil.cpp, lib/core/src/sockComm.cpp, scripts/irods/test/test_irm.py, server/api/src/rsDataObjOpen.cpp, server/api/src/rsGenQuery.cpp, server/core/src/client_api_whitelist.cpp, server/core/src/dataObjOpr.cpp
=> Little fixes (master)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_icp.py, scripts/irods/test/test_iphymv.py, scripts/irods/test/test_iput.py, scripts/irods/test/test_irepl.py, server/api/src/rsDataObjCopy.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsDataObjUnlink.cpp, server/api/src/rsPhyPathReg.cpp, server/core/include/replica_state_table.hpp, server/core/src/irods_resource_manager.cpp, server/core/src/logical_locking.cpp, server/core/src/replica_state_table.cpp, unit_tests/src/test_rc_data_obj.cpp, unit_tests/src/test_replica_state_table.cpp
Still need to run the mungefs tests, but here is the start. Companion PR is irods/irods_client_icommands#201
=> [#5360] Add iphymv exit code tests (master)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_icp.py, scripts/irods/test/test_iphymv.py, scripts/irods/test/test_iput.py, scripts/irods/test/test_irepl.py, server/api/src/rsDataObjCopy.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsDataObjUnlink.cpp, server/api/src/rsPhyPathReg.cpp, server/core/include/replica_state_table.hpp, server/core/src/irods_resource_manager.cpp, server/core/src/logical_locking.cpp, server/core/src/replica_state_table.cpp, unit_tests/src/test_rc_data_obj.cpp, unit_tests/src/test_replica_state_table.cpp
Cherry-picked from changes made for #5555 
=> [#3490][#5360] Fix failure behavior in phymv/cp (4-2-stable)

scripts/irods/test/test_iput.py, server/api/src/rsDataObjPut.cpp
=> [#5575] Various fixes in rsDataObjPut (master)

server/api/src/rsDataObjClose.cpp
=> [#5576] Rearranged PUT-specific checksum code for tape (master)

server/api/src/rsDataObjClose.cpp
=> [#5576] Rearranged PUT-specific checksum code for tape (4-2-stable)

scripts/irods/test/test_iput.py, server/api/src/rsDataObjPut.cpp
Cherry-picked from changes in #5580 
=> [#5575] Various fixes in rsDataObjPut (4-2-stable)

plugins/api/src/get_file_descriptor_info.cpp, plugins/api/src/replica_close.cpp, plugins/api/src/replica_open.cpp, scripts/irods/test/test_istream.py
cherry-picked from changes made for #5551 
=> [#5187][#5422] Stale sibling replicas on write (4-2-stable)

lib/core/src/fsckUtil.cpp, scripts/irods/test/test_ifsck.py
Passed CI on 5afcef3fb446e9e4b9415b87c3285fafd8a64dca
=> [#5358] ifsck does not terminate on sub-directory permission error (4-2-stable)

lib/core/src/fsckUtil.cpp, scripts/irods/test/test_ifsck.py
=> [#5358] ifsck does not terminate on sub-directory permission error (master)

scripts/irods/test/test_icommands_file_operations.py
Adds a test similar to test_cancel_large_iput but for a forced overwrite
of a data object. The test especially ensures that the checksum is
updated and is not equal to the old checksum which would be incorrect
given the partial overwrite of the data.
---
As this only adds a test, I only ran the one test and it passes. The old test which was renamed passes as well.
=> [#3091] Cancel large iput -f test (master)

scripts/irods/test/test_icommands_file_operations.py
cherry-picked from changes made for #5595
=> [#3091] Cancel large iput -f test (4-2-stable)

lib/core/include/data_object_proxy.hpp, scripts/irods/test/test_ichksum.py, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjRename.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsDataObjTrim.cpp, server/api/src/rsDataObjUnlink.cpp, server/core/include/logical_locking.hpp, server/core/src/logical_locking.cpp, server/core/src/voting.cpp, unit_tests/src/test_logical_locking.cpp, unit_tests/src/test_replica_open_and_close.cpp
cherry-picked from changes for #5589
=> [#5421] Enforce ILL in unlink/rename/trim (4-2-stable)

scripts/irods/lib.py, scripts/irods/test/test_iget.py, server/api/src/rsDataObjGet.cpp
=> [#4475] Make -R a directive for iget (master)

scripts/irods/lib.py, scripts/irods/test/test_iget.py, server/api/src/rsDataObjGet.cpp
cherry-picked from changes made for #5610 
CI tests will run in a bit
=> [#4475] Make -R a directive for iget (4-2-stable)

scripts/irods_control.py
Cherry-pick of #5622 into stable
Fixes #5383 for stable
=> [#5383] irods_control.py: incrememnt verbosity counter for status (4-2-stable)

scripts/irods_control.py
Fixes #5383 for master
If this looks OK, I'll # and backport.
=> [#5383] irods_control.py: incrememnt verbosity counter for status (master)

plugins/database/src/db_plugin.cpp
=> [#5613] Fix potential use-after-free (4-2-stable)

scripts/irods/test/test_ibun.py, server/api/src/rsStructFileBundle.cpp
New test passes, will run through CI, too
=> [#5426] Fix force flag usage in rsStructFileBundle (master)

unit_tests/src/test_rc_data_obj.cpp, unit_tests/src/unit_test_utils.hpp
cherry-picked from work for #5624 
Passed CI several times
=> [#5605] Wait for agent close before asserting (4-2-stable)

unit_tests/src/test_rc_data_obj.cpp, unit_tests/src/unit_test_utils.hpp
Adds a unit test utility to get the PID of the connected agent. This
allows us to wait for the remote agent to go away after suddenly
disconnecting before making any assertions about what should and should
not be in the catalog.
---
As only a unit test was touched for this change, I only ran the affected unit tests and they pass.
=> [#5605] Wait for agent close before asserting (master)

scripts/irods/test/test_ibun.py, server/api/src/rsStructFileBundle.cpp
cherry-picked from changes for #5629 
Haven't run this yet but I don't imagine it will be much different from master, so I'm making a PR
=> [#5426] Fix force flag usage in rsStructFileBundle (4-2-stable)

scripts/core_tests_list.json, scripts/irods/test/test_special_collections.py, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjUnlink.cpp
CI tests passed except for known failure in `test_iticket`
=> [#5457] Fix overwriting/unlinking in special collections (master)

scripts/core_tests_list.json, scripts/irods/test/test_special_collections.py, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjUnlink.cpp
cherry-picked from #5636 commits
CI tests to run later
=> [#5457] Fix overwriting/unlinking in special collections (4-2-stable)

lib/api/include/data_object_finalize.h, plugins/api/src/atomic_apply_acl_operations.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, plugins/api/src/data_object_finalize.cpp, plugins/api/src/replica_close.cpp, plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_iticket.py, server/api/src/rsBulkDataObjReg.cpp, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRename.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsDataObjUnlink.cpp, server/core/include/catalog_utilities.hpp, server/core/include/finalize_utilities.hpp, server/core/include/irods_database_constants.hpp, server/core/include/logical_locking.hpp, server/core/include/replica_state_table.hpp, server/core/src/catalog_utilities.cpp, server/core/src/finalize_utilities.cpp, server/core/src/initServer.cpp, server/core/src/logical_locking.cpp, server/core/src/replica_state_table.cpp, server/icat/include/icatHighLevelRoutines.hpp, server/icat/src/icatHighLevelRoutines.cpp, unit_tests/src/test_data_object_finalize.cpp
cherry-picked from work for #5594 
=> [#4331] Bumpers for data_object_finalize (4-2-stable)

lib/api/include/data_object_finalize.h, plugins/api/src/data_object_finalize.cpp, plugins/api/src/replica_close.cpp, plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iticket.py, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRepl.cpp, server/core/include/finalize_utilities.hpp, server/core/include/irods_database_constants.hpp, server/core/include/logical_locking.hpp, server/core/include/replica_state_table.hpp, server/core/src/finalize_utilities.cpp, server/core/src/logical_locking.cpp, server/core/src/replica_state_table.cpp, server/icat/include/icatHighLevelRoutines.hpp, server/icat/src/icatHighLevelRoutines.cpp, unit_tests/src/test_data_object_finalize.cpp
=> [#4331] Add ticket support to data_object_finalize (master)

scripts/irods/test/test_federation.py, server/api/src/rsDataObjCopy.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPut.cpp, server/core/include/rodsConnect.h, server/core/src/objDesc.cpp, server/core/src/rodsConnect.cpp
cherry-picked from work for #5645 and test was adjusted to pass in CI.
=> Various fixes for federation (4-2-stable)

scripts/irods/test/test_federation.py
Automated testing has a very specific setup for federation tests so this
change makes adjustments to test_federation.test_dynamic_peps to
accommodate as well as renames the test to avoid collisions.
---
Adjusted the one test which passed in CI
=> [#5017] Fix dynPEP in federation test for CI (master)

plugins/api/src/data_object_finalize.cpp, plugins/resources/compound/libcompound.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsPhyPathReg.cpp, server/api/src/rsStructFileExtAndReg.cpp, server/core/src/fileOpr.cpp, server/core/src/objDesc.cpp
cherry-picked from work in #5652 
CI tests are running
=> [#5657] Fix a few memleaks (4-2-stable)

plugins/api/src/data_object_finalize.cpp, plugins/resources/compound/libcompound.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsPhyPathReg.cpp, server/api/src/rsStructFileExtAndReg.cpp, server/core/src/fileOpr.cpp, server/core/src/objDesc.cpp
=> [#5657] Fix a few memleaks (master)

scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_iqmod.py, scripts/irods/test/test_rulebase.py
=> [#4094] Fix acPostProcForPut test (4-2-stable)

scripts/irods/test/test_iput.py, server/api/src/rsDataObjPut.cpp
cherry-picked from work done for #5676 
CI tests running soon...
=> [#5675] Set L1desc input data size for put (4-2-stable)

scripts/irods/test/test_iput.py, server/api/src/rsDataObjPut.cpp
=> [#5675] Set L1desc input data size for put (master)

server/api/src/rsDataObjOpen.cpp
cherry-picked from changes made for #5686
CI tests running.
=> [#5682] Query for missing replica info in create (master)

scripts/irods/test/test_ichksum.py, scripts/irods/test/test_iphymv.py, scripts/irods/test/test_iput.py, scripts/irods/test/test_irepl.py, scripts/irods/test/test_iticket.py, scripts/irods/test/test_native_rule_engine_plugin.py, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRepl.cpp, server/core/src/irods_resource_redirect.cpp
cherry-picked from efforts for #5692 
=> [#5691] Relax usage of default resource for put (master)

plugins/api/src/data_object_finalize.cpp
cherry-picked from work done for #5714 
=> [#5689] Limit redirection in data_object_finalize (master)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_quotas.py
=> [#5733] Only commit for tickets in check_permission_to_modify_data_object (4-2-stable)

lib/api/src/rcDataObjGet.cpp, lib/core/src/irods_client_negotiation.cpp, plugins/network/ssl/libssl.cpp, server/core/src/miscServerFunct.cpp
=> [#5699] initialize bytesBuf structs before use (4-2-stable)

lib/api/src/rcDataObjGet.cpp, lib/core/src/irods_client_negotiation.cpp, plugins/network/ssl/libssl.cpp, server/core/src/miscServerFunct.cpp
=> [#5699] initialize bytesBuf structs before use (master)

server/core/src/finalize_utilities.cpp
=> [#5744] Prevent use of non-existent L1 descriptor (master)

scripts/irods/test/test_misc.py, server/core/include/process_manager.hpp, server/core/src/rodsServer.cpp
This provides a partial solution to issue 4977 and provides a framework which provides for tasks that should be executed at a given interval to be built.
=> Delay server and Agent server watchers

scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_iget.py, scripts/irods/test/test_iput_options.py, server/api/src/rsDataObjOpen.cpp
=> [#5760] Prevent staling replicas on open for read + test_delay_queue resilience (master)

CMakeLists.txt, cmake/server.cmake, lib/core/include/irods_configuration_parser.hpp, lib/core/include/irods_server_properties.hpp, lib/core/src/irods_client_negotiation.cpp, lib/core/src/irods_configuration_parser.cpp, lib/core/src/irods_server_properties.cpp, lib/core/src/rcMisc.cpp, lib/core/src/sockComm.cpp, plugins/database/src/db_plugin.cpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/libirods_rule_engine_plugin-irods_rule_language.cpp, scripts/irods/test/test_remote_server_properties.py, server/api/src/rsFileChksum.cpp, server/core/src/client_api_whitelist.cpp, server/core/src/initServer.cpp, server/core/src/irodsReServer.cpp, server/core/src/irods_configuration_test_harness.cpp, server/core/src/irods_logger.cpp, server/core/src/irods_server_control_plane.cpp, server/core/src/miscServerFunct.cpp, server/core/src/rodsAgent.cpp, server/core/src/rodsServer.cpp, server/icat/src/icatHighLevelRoutines.cpp, server/re/src/irods_re_namespaceshelper.cpp, server/re/src/irods_re_plugin.cpp
add remoteconfiguration endpoint via http
=> [5602] refactor server properties to use nlohmann::json

lib/core/include/rodsErrorTable.h
Added error code for when replication fails.
=> [5760] Added error when staging fails.

lib/api/src/rcBulkDataObjPut.cpp
The file says that it is generated code, but I could find the files which were used as source. Please update the source files.
The lib/api/README.txt file indicates "All functions are automatically generated by the apiGen script in the scripts directory."
But I could not find such a script in the respository.
=> [#858] Fix typos. The file says that it is generated code, but I could find the files which were used as source. Please update the source files.

plugins/api/src/touch.cpp, scripts/irods/test/test_ipwd.py
cherry-picked from work done in #5846 (additional commits after original cherry-pick)
Tests to be run overnight
=> [#5774] Propagate errors from touch API on CSC (master)

plugins/api/src/atomic_apply_acl_operations.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, plugins/api/src/data_object_finalize.cpp, plugins/api/src/touch.cpp, scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_ipwd.py, scripts/irods/test/test_native_rule_engine_plugin.py, scripts/run_tests.py, server/api/src/rsRuleExecSubmit.cpp, server/core/include/catalog_utilities.hpp, server/core/include/rodsConnect.h, server/core/include/rsGlobalExtern.hpp, server/core/src/catalog_utilities.cpp
cherry-picked from work done for #5844
=> Fix redirection logic and add hostname configuration to run_tests.py (4-2-stable)

server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjOpen.cpp, server/core/src/logical_locking.cpp, unit_tests/src/test_logical_locking.cpp, unit_tests/src/test_rc_data_obj.cpp
cherry-picked from work for #5855
Tests passed in CI
=> [#5548] and [#5848] Multi-1247 parallel transfer fixes (4-2-stable)

server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjOpen.cpp, server/core/src/logical_locking.cpp, unit_tests/src/test_logical_locking.cpp, unit_tests/src/test_rc_data_obj.cpp
CI tests running for good faith effort but non-cleaned-up branch from before completed tests successfully
=> [#5548] and [#5848] Multi-1247 parallel transfer fixes (master)

lib/core/include/stream_factory_utility.hpp, plugins/api/src/replica_close.cpp, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjPhymv.cpp, server/api/src/rsDataObjPut.cpp, server/core/src/initServer.cpp, unit_tests/src/test_logical_locking.cpp, unit_tests/src/test_rc_data_obj.cpp, unit_tests/src/unit_test_utils.hpp
cherry-picked from work for #5871
=> [#5863] Update mtime for creates/non-empty writes (4-2-stable)

.github/workflows/build-irods-centos.yml
=> [858] update centos github action (master)

.github/workflows/build-irods-centos.yml
=> [858] update centos github action (4-2-stable)

CMakeLists.txt, cmake/development_library.cmake, lib/core/include/irods_query.hpp, plugins/database/src/db_plugin.cpp, scripts/core_tests_list.json, scripts/irods/lib.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_igroupadmin.py, server/api/src/rsGeneralAdmin.cpp, server/api/src/rsUserAdmin.cpp, server/core/include/administration_utilities.hpp, server/core/include/user_validation_utilities.hpp, server/core/src/administration_utilities.cpp, server/core/src/user_validation_utilities.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_server_utilities.cmake, unit_tests/src/test_server_utilities.cpp
Haven't run CI yet
cherry-picked from work for #5971
=> [#4231] Disallow remote groups (master)

CMakeLists.txt, cmake/development_library.cmake, lib/core/include/irods_query.hpp, plugins/database/src/db_plugin.cpp, scripts/core_tests_list.json, scripts/irods/lib.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_igroupadmin.py, server/api/src/rsGeneralAdmin.cpp, server/api/src/rsUserAdmin.cpp, server/core/include/administration_utilities.hpp, server/core/include/user_validation_utilities.hpp, server/core/src/administration_utilities.cpp, server/core/src/user_validation_utilities.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_server_utilities.cmake, unit_tests/src/test_server_utilities.cpp
CI tests to run, all the new tests pass at the bench.
=> [#4231] Disallow remote groups (4-2-stable)

scripts/irods/test/test_control_plane.py, server/core/include/irods_server_control_plane.hpp, server/core/src/irods_server_control_plane.cpp
=> [#5700] Control plane uses server_config.json to resolve hostnames (main)

lib/core/src/msParam.cpp, scripts/irods/test/test_all_rules.py, server/api/src/rsExecMyRule.cpp, server/core/src/rodsAgent.cpp, server/re/src/reDataObjOpr.cpp
=> [#4649] Fix leaks observed on rule invocation (4-2-stable)

lib/core/src/msParam.cpp, scripts/irods/test/test_all_rules.py, server/api/src/rsExecMyRule.cpp, server/re/src/reDataObjOpr.cpp
cherry-picked from work done for #6034
=> [#4649] Fix leaks observed on rule invocation (master)

scripts/irods/test/test_resource_types.py
cherry-picked from work done for #6048
=> [#6029] Fix test ils with space in name (master)

packaging/irods
prevents a non-zero return value when the file does not exist
=> [6053] more graceful stop when server already stopped (master)

.github/workflows/build-irods-centos.yml, .github/workflows/build-irods-ubuntu.yml, irods_consortium_continuous_integration_build_hook.py
=> [5669] Bump CMake extern to 3.21.4

lib/core/include/replica.hpp, scripts/irods/lib.py, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_ireg.py, server/api/src/rsDataObjRepl.cpp, server/re/src/reDataObjOpr.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_rc_data_obj_repl.cmake, unit_tests/src/test_rc_data_obj_repl.cpp, unit_tests/unit_tests_list.json
I split this up into two parts: the API changes and the microservice changes. Willing to squash it down.
This passed in CI
=> [#5927] Add checksum verification keywords to replication API and microservice (4-2-stable)

scripts/run_tests.py, unit_tests/cmake/test_config/irods_client_server_negotiation.cmake
Confirmed that `--run_specific_tests` still works as expected and passing nothing still runs all of the tests.
=> Some fixes for running tests in main

lib/core/include/replica.hpp, scripts/irods/lib.py, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_ireg.py, server/api/src/rsDataObjRepl.cpp, server/re/src/reDataObjOpr.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_rc_data_obj_repl.cmake, unit_tests/src/test_rc_data_obj_repl.cpp, unit_tests/unit_tests_list.json
cherry-picked from work done for #6096 
I have confirmed that this builds, but haven't run through testing yet as things have moved enough such that our testing infrastructure doesn't support main right now. Workin' on it
=> [#5927] Add checksum verification keywords to replication API and microservice (main)

doxygen/microservices.cpp, plugins/database/src/db_plugin.cpp, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_imeta_set.py, scripts/irods/test/test_iput_options.py, server/re/include/reAction.hpp, server/re/include/reSysDataObjOpr.hpp, server/re/src/reSysDataObjOpr.cpp
=> Remove msiSetRescSortScheme and check error codes in db_plugin (main)

plugins/resources/compound/libcompound.cpp, scripts/irods/test/test_resource_types.py, server/api/src/rsDataObjClose.cpp
cherry-picked from work for #6110
I think this is ready to merge based on testing from 4-2-stable.
=> [#6089] Prevent checksums on archive replicas (main)

scripts/irods/test/test_iput_options.py, scripts/irods/test/test_isysmeta.py
=> Test fixes (4-2-stable)

lib/core/src/regUtil.cpp, scripts/irods/lib.py, scripts/irods/test/test_chunkydevtest.py, scripts/irods/test/test_ireg.py, scripts/irods/test/test_iscan.py, scripts/irods/test/test_itrim.py
Companion to https://github.com/irods/irods_client_icommands/pull/275
=> [#2919] Add recursive option to regUtil (main)

lib/core/src/lsUtil.cpp, lib/core/src/miscUtil.cpp, plugins/api/src/atomic_apply_acl_operations.cpp, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_ils.py, server/core/include/catalog_utilities.hpp, server/core/src/catalog_utilities.cpp
=> Atomic APIs / ils bug fixes and tests (4-2-stable)

server/core/include/irods/irods_resource_manager.hpp, server/core/src/initServer.cpp, server/core/src/irods_resource_manager.cpp
Rewrites init_from_catalog to use the irods::query iterator for fetching
information about existing resources and populating the resource
manager.
---
All tests passed
=> [#3404] Refactor resource_manager::init_from_catalog (main)

scripts/irods/test/rule_texts_for_tests.py, scripts/irods/test/test_rulebase.py, server/api/src/rsExecMyRule.cpp
=> [#4260] Enforce valid hostname for remote rule execution (main)

scripts/setup_irods.py
cherry-picked from work for #6245
=> Handling of federated groups (4-2-stable)

VERSION.json.dist.in, plugins/database/packaging/localhost_setup_mysql.input, plugins/database/packaging/localhost_setup_oracle.input, plugins/database/packaging/localhost_setup_postgres.input, plugins/database/src/db_plugin.cpp, scripts/irods/configuration.py, scripts/irods/database_connect.py, scripts/irods/database_interface.py, scripts/irods/database_upgrade.py, scripts/setup_irods.py, server/api/src/rsGeneralAdmin.cpp, server/core/include/irods/irods_database_constants.hpp, server/icat/include/irods/icatHighLevelRoutines.hpp, server/icat/src/icatHighLevelRoutines.cpp, server/main_server/src/rodsServer.cpp
still wip...
but this gets the configuration bits in the right place
- setup
- upgrade
- database operation for `iadmin set_delay_server`
=> delay server, setup and migration (main)

server/core/src/client_api_allowlist.cpp
This PR also changes the log level used for client api allowlist messages to trace.
Running core tests.
=> [#6295] "client_api_allowlist_policy" defaults to "enforce" when not defined in server_config.json (main)

packaging/core.re.template, plugins/rule_engines/src/cpp_default_policy.cpp
needs a run through CI...
probably missed a couple places in the tests that need to be tweaked for the new default.
=> [3461] change default server SSL policy to CS_NEG_REFUSE (master)

doxygen/microservices.cpp, packaging/core.re.template, scripts/irods/test/test_all_rules.py, server/re/include/irods/reAction.hpp, server/re/include/irods/reSysDataObjOpr.hpp, server/re/src/reSysDataObjOpr.cpp
Companion PR: https://github.com/irods/irods_client_icommands/pull/303
=> Removed microservice: msiSortDataObj (main)

schemas/configuration/v4/unattended_installation.json.in, scripts/setup_irods.py
=> [#6330] Updated unattended installation logic and schema (main)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_quotas.py
Companion PR: https://github.com/irods/irods_client_icommands/pull/304
=> [#4481] Disabled support for setting non-zero user quotas (main)

plugins/auth/CMakeLists.txt, plugins/auth/include/irods/plugins/auth/native.hpp, plugins/auth/include/irods/plugins/auth/pam_password.hpp, plugins/auth/src/native.cpp, plugins/auth/src/pam_password.cpp, plugins/database/CMakeLists.txt, plugins/database/src/db_plugin.cpp, scripts/irods/test/test_auth.py, server/core/src/rodsAgent.cpp
companion PR: https://github.com/irods/irods_client_icommands/pull/305
---
Confirmed that tests pass in testing environment.
=> Rename new pam plugin to pam_password (main)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_imeta_error_handling.py, scripts/irods/test/test_imeta_interactive.py, scripts/irods/test/test_ssl.py
Full test suite is running now, but individual tests passed at the bench.
=> Fixes for several failing tests (main)

lib/api/include/irods/apiNumber.h
=> Fix scope issue in apiNumber.h.

lib/api/include/irods/apiNumber.h
cherry-picked from work done for #6449
=> [#6448] Fix scope issue in apiNumber.h. (4-3-stable)

scripts/irods/test/test_misc.py
Cherry-picked from https://github.com/irods/irods/pull/6438
=> [#858] Skip test for PREP (4-3-stable)

lib/CMakeLists.txt, lib/administration/CMakeLists.txt, lib/administration/ticket/CMakeLists.txt, lib/administration/ticket/include/irods/ticket_administration.hpp, lib/administration/ticket/src/ticket_administration.cpp, server/CMakeLists.txt, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_ticket_administration.cmake, unit_tests/src/test_ticket_administration.cpp, unit_tests/unit_tests_list.json
=> [#5176] Added Ticket Administration Library (main)

.gitignore, lib/core/CMakeLists.txt, lib/core/include/irods/irods_server_properties.hpp, lib/core/include/irods/json_events.hpp, lib/core/include/irods/rodsErrorTable.h, lib/core/src/irods_server_properties.cpp, lib/core/src/json_events.cpp, plugins/microservices/CMakeLists.txt, plugins/microservices/src/get_server_property.cpp, scripts/core_tests_list.json, scripts/irods/controller.py, scripts/irods/test/test_configuration_reload.py, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_icommands_file_operations.py, server/control_plane/include/irods/irods_server_control_plane.hpp, server/core/src/miscServerFunct.cpp, server/delay_server/src/irodsDelayServer.cpp, server/irods_grid/src/irods-grid.cpp, server/main_server/src/main_server_control_plane.cpp, server/main_server/src/rodsServer.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_json_events.cmake, unit_tests/src/test_json_events.cpp, unit_tests/src/test_server_properties.cpp, unit_tests/unit_tests_list.json
This contains:
* The original configuration reload work
* The `get_script_output_single_line` rewrite
* The `irods-grid reload` command
=> Add nice stuff to 4.3 stable

scripts/irods/test/test_configuration_reload.py
"test_configuration_reload.TestConfigurationReload.test_reload_command__issue_6529" was merged broken, this fixes the test so that it functions properly.
=> Fix "irods-grid reload" test

.gitmodules
=> [#6517] remove .gitmodules (main)

.gitmodules
Addresses #6517 for 4-3-stable
=> [#6517] remove .gitmodules (4-3-stable)

scripts/irods/test/test_configuration_reload.py
cherry-picked from work done for #6542 
Sorry, I missed this diff in the code review.
=> [#6529] Fix "irods-grid reload" test (4-3-stable)

plugins/rule_engines/irods_rule_language/src/functions.cpp, scripts/irods/test/test_rule_engine_plugin_framework.py
Replaces https://github.com/irods/irods/pull/6467
=> [_6465] allow remote(...) hints to target INST_NAME

lib/core/include/irods/irods_logger.hpp, lib/core/include/irods/irods_logger.tpp, plugins/api/src/register_physical_path.cpp, plugins/database/src/db_plugin.cpp, server/api/src/rsAuthCheck.cpp, server/api/src/rsBulkDataObjPut.cpp, server/api/src/rsDataObjRename.cpp, server/api/src/rsGeneralAdmin.cpp, server/api/src/rsGetRescQuota.cpp, server/api/src/rsModAccessControl.cpp, server/api/src/rsUserAdmin.cpp
I haven't gotten everything, but at least there'll be a few less :)
=> [#4367] rodsLog cleanup (main)

lib/core/include/irods/irods_logger.hpp, lib/core/include/irods/irods_logger.tpp, plugins/api/src/register_physical_path.cpp, plugins/database/src/db_plugin.cpp, server/api/src/rsAuthCheck.cpp, server/api/src/rsBulkDataObjPut.cpp, server/api/src/rsDataObjRename.cpp, server/api/src/rsGeneralAdmin.cpp, server/api/src/rsGetRescQuota.cpp, server/api/src/rsModAccessControl.cpp, server/api/src/rsUserAdmin.cpp
=> [#4367] rodsLog cleanup (4-3-stable)

server/api/src/rsDataObjOpen.cpp
All unit tests and core tests pass (except test_configuration_reload.py, which is expected).
=> Server does not modify access flags on open (main)

server/api/src/rsDataObjOpen.cpp
=> [#6600] Server no longer modifies access mode on call to open (4-3-stable)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_imeta_error_handling.py, server/core/src/finalize_utilities.cpp
Core tests are running now
The latest commit on this branch includes some renames and comments. I'm not sure how helpful these changes are so I decided not to squash them yet until I got some feedback.
=> [#6504] Make AVU-by-condInput association atomic (main)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_imeta_error_handling.py, server/core/src/finalize_utilities.cpp
cherry-picked from work done for #6508
=> [#6504] Make AVU-by-condInput association atomic (4-3-stable)

unit_tests/src/test_rc_data_obj.cpp
=> [#6600] Added unit test that proves the server honors the openmode (main)

lib/core/src/irods_server_properties.cpp, scripts/irods/test/test_configuration_reload.py, server/core/src/miscServerFunct.cpp, server/main_server/src/rodsServer.cpp, server/re/src/extractAvuMS.cpp
=> [#6569] Fixed issues with configuration reload tests (main)

lib/core/src/irods_server_properties.cpp, scripts/irods/test/test_configuration_reload.py, server/core/src/miscServerFunct.cpp, server/main_server/src/rodsServer.cpp, server/re/src/extractAvuMS.cpp
=> [#6569] Fixed issues with configuration reload (4-3-stable)

lib/CMakeLists.txt, lib/administration/CMakeLists.txt, lib/administration/ticket/CMakeLists.txt, lib/administration/ticket/include/irods/ticket_administration.hpp, lib/administration/ticket/src/ticket_administration.cpp, server/CMakeLists.txt, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_ticket_administration.cmake, unit_tests/src/test_ticket_administration.cpp, unit_tests/unit_tests_list.json
=> [#5716] Added Ticket Administration Library (4-3-stable)

plugins/resources/CMakeLists.txt, plugins/resources/unixfilesystem/CMakeLists.txt, plugins/resources/unixfilesystem/include/irods/private/irods_is_in_host_list.hpp, plugins/resources/unixfilesystem/src/irods_is_in_host_list.cpp, plugins/resources/unixfilesystem/src/unixfilesystem.cpp, scripts/irods/paths.py, scripts/irods/test/test_resource_types.py, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_host_list_context_string.cmake, unit_tests/src/test_host_list_context_string.cpp
All unixfilesystem tests were run and passed.
=> [4421] Added detached mode for unixfilesystem resource (4-3-stable)

lib/core/include/irods/rodsGenQuery.h, lib/core/include/irods/rodsGenQueryNames.h, plugins/database/src/general_query_setup.cpp, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_icd.py
Addresses #6624
Cherry-picked from #6637
=> Add token create/modify times to GenQuery (4-3-stable)

scripts/irods/test/test_iadmin.py
=> [#6624] Remove f-string from iadmin test (main)

lib/core/include/rodsGenQuery.h, lib/core/include/rodsGenQueryNames.h, plugins/database/src/general_query_setup.cpp, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_icd.py
Addresses https://github.com/irods/irods/issues/6624
Cherry-picked from https://github.com/irods/irods/pull/6637
=> Add token create/modify times to GenQuery (4-2-stable)

server/core/src/irodsReServer.cpp
Addresses #6323 
Cherry-picked from https://github.com/irods/irods/pull/6325/commits/c32213b91534c3e0b41a8656841100efdb2acfff and https://github.com/irods/irods/pull/6272/commits/49226ae39ef03ccd9ec6276fe6dba2b32e2efbca
---
Core tests are running now.
=> Ensure delay rules are removed from queue (4-2-stable)

.github/workflows/linter-irods-clang-tidy.yml, lib/CMakeLists.txt, lib/administration/CMakeLists.txt, lib/administration/user/CMakeLists.txt, lib/administration/user/include/irods/user_administration.hpp, lib/administration/user/src/user_administration.cpp, lib/administration/user/src/utilities.cpp, lib/administration/zone/CMakeLists.txt, lib/administration/zone/include/irods/zone_administration.hpp, lib/administration/zone/include/irods/zone_type.hpp, lib/administration/zone/src/zone_administration.cpp, lib/core/CMakeLists.txt, lib/core/include/irods/library_features.h, server/CMakeLists.txt, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_zone_administration.cmake, unit_tests/src/test_packstruct.cpp, unit_tests/src/test_zone_administration.cpp, unit_tests/unit_tests_list.json
This PR was created from work in #6593 that was mostly complete. This also helps to get these features into upstream faster since there are fewer things to think about.
=> Implemented new C++ library for zone administration (main)

.github/workflows/linter-irods-clang-tidy.yml, lib/CMakeLists.txt, lib/administration/CMakeLists.txt, lib/administration/user/CMakeLists.txt, lib/administration/user/include/irods/user_administration.hpp, lib/administration/user/src/user_administration.cpp, lib/administration/user/src/utilities.cpp, lib/administration/zone/CMakeLists.txt, lib/administration/zone/include/irods/zone_administration.hpp, lib/administration/zone/include/irods/zone_type.hpp, lib/administration/zone/src/zone_administration.cpp, lib/core/CMakeLists.txt, lib/core/include/irods/library_features.h, server/CMakeLists.txt, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_zone_administration.cmake, unit_tests/src/test_packstruct.cpp, unit_tests/src/test_zone_administration.cpp, unit_tests/unit_tests_list.json
=> Implemented new C++ library for zone administration (4-3-stable)

lib/administration/resource/CMakeLists.txt, lib/administration/ticket/CMakeLists.txt, lib/administration/user/CMakeLists.txt, lib/administration/zone/CMakeLists.txt
Addresses #6665 for 4-3-stable
=> [#6665] Pass down proper include dirs from administration libraries (4-3-stable)

lib/administration/resource/CMakeLists.txt, lib/administration/ticket/CMakeLists.txt, lib/administration/user/CMakeLists.txt, lib/administration/zone/CMakeLists.txt
=> [#6665] Pass down proper include dirs from administration libraries (main)

plugins/rule_engines/irods_rule_language/src/cache.cpp, plugins/rule_engines/irods_rule_language/src/configuration.cpp, server/core/include/irods/initServer.hpp, server/core/include/irods/rodsAgent.hpp, server/core/include/irods/rodsConnect.h, server/core/src/initServer.cpp, server/core/src/rodsAgent.cpp, server/main_server/include/irods/rodsServer.hpp, server/main_server/src/rodsServer.cpp, server/re/include/irods/sharedmemory.hpp, server/re/src/sharedmemory.cpp
Rebased work done by @june-releford on main.
Running through testing environment.
=> [#6473] Main server clean up (main)

lib/api/include/irods/apiNumberData.h, lib/api/include/irods/apiTable.hpp, lib/api/include/irods/simpleQuery.h, lib/api/src/rcSimpleQuery.cpp, lib/core/include/irods/rodsErrorTable.h, plugins/database/src/db_plugin.cpp, server/api/include/irods/rsSimpleQuery.hpp, server/api/src/rsSimpleQuery.cpp, server/core/include/irods/irods_api_calling_functions.hpp, server/core/include/irods/irods_database_constants.hpp, server/core/src/irods_api_calling_functions.cpp, server/icat/include/irods/icatHighLevelRoutines.hpp
Addresses #6638 
Cherry-picked from #6657
=> [#6638] Deprecate SimpleQuery (4-3-stable)

plugins/rule_engines/irods_rule_language/src/cache.cpp, plugins/rule_engines/irods_rule_language/src/configuration.cpp, server/core/include/irods/initServer.hpp, server/core/include/irods/rodsAgent.hpp, server/core/include/irods/rodsConnect.h, server/core/src/initServer.cpp, server/core/src/rodsAgent.cpp, server/main_server/include/irods/rodsServer.hpp, server/main_server/src/rodsServer.cpp, server/re/include/irods/sharedmemory.hpp, server/re/src/sharedmemory.cpp
=> [#6473] Main server clean up (4-3-stable)

lib/core/src/user_administration.cpp
Cherry-picked from #6593
Will run unit tests to make sure the changes are good.
=> [#6680] Fixed query functions provided by user administration library (4-2-stable)

scripts/irods/test/test_rulebase.py, server/core/src/objDesc.cpp
Addresses https://github.com/irods/irods/issues/6622
Cherry-picked from https://github.com/irods/irods/pull/6676
Tests are running
=> closeAllL1Desc modifications + test (4-2-stable)

plugins/api/src/atomic_apply_acl_operations.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, plugins/api/src/authenticate.cpp, plugins/api/src/data_object_finalize.cpp, plugins/api/src/data_object_modify_info.cpp, plugins/api/src/experimental_api_plugin_adaptor.cpp, plugins/api/src/get_file_descriptor_info.cpp, plugins/api/src/helloworld.cpp, plugins/api/src/register_physical_path.cpp, plugins/api/src/replica_close.cpp, plugins/api/src/replica_open.cpp, plugins/api/src/switch_user.cpp, plugins/api/src/touch.cpp, server/core/include/irods/client_api_allowlist.hpp, server/core/src/client_api_allowlist.cpp, server/core/src/rsApiHandler.cpp, server/main_server/src/rodsServer.cpp
=> [#6639] Refactored client_api_allowlist interface (main)

plugins/api/src/atomic_apply_acl_operations.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, plugins/api/src/authenticate.cpp, plugins/api/src/data_object_finalize.cpp, plugins/api/src/data_object_modify_info.cpp, plugins/api/src/experimental_api_plugin_adaptor.cpp, plugins/api/src/get_file_descriptor_info.cpp, plugins/api/src/helloworld.cpp, plugins/api/src/register_physical_path.cpp, plugins/api/src/replica_close.cpp, plugins/api/src/replica_open.cpp, plugins/api/src/switch_user.cpp, plugins/api/src/touch.cpp, server/core/include/irods/client_api_allowlist.hpp, server/core/src/client_api_allowlist.cpp, server/core/src/rsApiHandler.cpp, server/main_server/src/rodsServer.cpp
=> [#6639] Refactored client_api_allowlist interface (4-3-stable)

server/core/src/irodsReServer.cpp, server/re/src/reSysDataObjOpr.cpp
Ported from d9a85abce36cdf496b59c0b570509f50e3e6571a
=> [#6327] Server does not log stacktrace for config properties that have a default value (4-2-stale)

lib/core/include/irods/irods_logger.hpp, lib/core/src/irods_logger.cpp, server/delay_server/src/irodsDelayServer.cpp, server/main_server/src/rodsServer.cpp
=> Adjusted log message structure (4-3-stable) 

lib/administration/resource/include/irods/resource_administration.hpp, lib/administration/resource/src/resource_administration.cpp, unit_tests/cmake/test_config/irods_filesystem.cmake, unit_tests/cmake/test_config/irods_resource_administration.cmake, unit_tests/cmake/test_config/irods_zone_report.cmake, unit_tests/src/filesystem/test_filesystem.cpp, unit_tests/src/test_data_object_finalize.cpp, unit_tests/src/test_logical_locking.cpp, unit_tests/src/test_parallel_transfer_engine.cpp, unit_tests/src/test_replica.cpp, unit_tests/src/test_resource_administration.cpp, unit_tests/src/test_zone_report.cpp, unit_tests/src/unit_test_utils.hpp
=> [#6619] Refactored resource administration lib to prefer exceptions (4-3-stable)

scripts/irods/test/test_auth.py, scripts/irods/test/test_rulebase.py
Addresses #6693
Unskipped test, confirmed that it is passing
Also, typo
=> [#6693] Fix test_auth (main)

scripts/irods/test/test_auth.py, scripts/irods/test/test_rulebase.py
Addresses #6693 
Cherry-picked from #6704
=>  [#6693] Fix test_auth (4-3-stable)

scripts/irods/test/test_auth.py
Addresses #6693
Cherry-picked from #6722
=> [#6693] test_auth: Newer OpenSSL requires 2048 numbits (4-3-stable)

lib/core/src/stringOpr.cpp
Update `rstrcpy` logging to produce shorter, informative messages.
=> Modify `rstrcpy` to improve error logs (main)

plugins/microservices/src/get_hostname.cpp, server/core/src/client_api_allowlist.cpp, server/delay_server/src/irodsDelayServer.cpp, server/main_server/src/rodsServer.cpp, unit_tests/src/test_dstream.cpp, unit_tests/src/test_resource_administration.cpp, unit_tests/src/test_zone_report.cpp, unit_tests/src/unit_test_utils.hpp
=> Client API Allowlist / Delay Server Migration / gethostname (4-3-stable)

lib/administration/user/CMakeLists.txt, lib/administration/user/include/irods/user_administration.hpp, lib/administration/user/src/detail.cpp, lib/administration/user/src/user_administration.cpp, lib/administration/user/src/utilities.cpp, lib/api/include/irods/generalAdmin.h, unit_tests/cmake/test_config/irods_atomic_apply_acl_operations.cmake, unit_tests/cmake/test_config/irods_user_administration.cmake, unit_tests/src/test_rc_switch_user.cpp, unit_tests/src/test_ticket_administration.cpp, unit_tests/src/test_user_administration.cpp
=> Refactored user administration library to throw exceptions (4-3-stable)

lib/core/src/stringOpr.cpp
Update log level to show rstrcpy arguments, stop rstrcpy printing stacktrace
=> [5916,6674] Improve `rstrcpy` logging (4-3-stable)

lib/core/src/stringOpr.cpp
Update log level to show rstrcpy arguments, stop rstrcpy printing stacktrace.
=> [5916,6674] Improve rstrcpy logging (4-2-stable)

scripts/irods/test/test_ichmod.py
This test ensures the new ichmod corrected the behavior seen in this issue.
=> [2570] Verify ichmod respects ACLs

lib/core/CMakeLists.txt, lib/core/include/irods/base64.h, lib/core/include/irods/base64.hpp, lib/core/src/base64.cpp, lib/core/src/packStruct.cpp, lib/hasher/src/ADLER32Strategy.cpp, lib/hasher/src/SHA1Strategy.cpp, lib/hasher/src/SHA256Strategy.cpp, lib/hasher/src/SHA512Strategy.cpp, plugins/auth/src/native.cpp
This is simply a cherry-pick of 6716 for 4-3-stable.
=> [6716] Put base64 methods in irods namespace (4-3-stable)

scripts/irods/test/test_iadmin.py, scripts/system_identification.py, server/api/src/rsGeneralAdmin.cpp
Replaces PR #6466
Will run tests soon.
=> Prevent inappropriate rodsadmin downgrades in same zone (main) (updated)

scripts/irods/test/test_iadmin.py, scripts/system_identification.py, server/api/src/rsGeneralAdmin.cpp
=> Prevent inappropriate rodsadmin downgrades in same zone (4-3-stable)

plugins/auth/src/pam_password.cpp
Addresses lingering issue found here (i.e. not the main issue, which has already been fixed): https://github.com/irods/irods/issues/3564#issuecomment-1256617949
Confirmed that the issue is resolved only at the bench because the issue manifests as log noise, as far as I can tell. If anybody can think of a way in which this might present a more serious problem which we can capture in a test, I will write an automated test.
=> [#3564] pam_password: CSP redirect only enables SSL if necessary (main)

server/core/include/objDesc.hpp, server/core/src/finalize_utilities.cpp, server/core/src/objDesc.cpp
=> [#6611] Removed potential for segfault with l1 descriptors (4-2-stable)

scripts/irods/test/test_iadmin.py, server/api/src/rsGeneralAdmin.cpp
Cherry-picked from #6774
Tests running. Will report results once complete.
=> Prevent inappropriate rodsadmin downgrades in same zone (4-2-stable)

plugins/auth/src/pam_password.cpp
Addresses https://github.com/irods/irods/issues/3564#issuecomment-1256617949
Cherry-picked from https://github.com/irods/irods/pull/6755
=> [#3564] pam_password: CSP redirect only enables SSL if necessary (4-3-stable)

server/core/include/irods/objDesc.hpp, server/core/src/finalize_utilities.cpp, server/core/src/objDesc.cpp
Taken from #6673.
Will run tests soon.
=> L1 descriptor fixes (main)

scripts/irods/test/test_iquest.py, server/api/src/rsGenQuery.cpp
Addresses #6101
Leaving in draft because I'm not sure how I feel about the `std::regex` approach, but wanted to put this up so I don't lose the work. Open to advice, of course.
Core tests are running. They passed before when I ran it back in October, but I made a couple of tweaks (seen in separate commits) which may have broken something. Will report results.
=> [#6101] Fix GenQuery operators for DATA_RESC_HIER (main)

server/core/include/irods/objDesc.hpp, server/core/src/finalize_utilities.cpp, server/core/src/objDesc.cpp
Taken from #6673.
Cherry-picked from #6792.
Will add the #'s if there are no objections.
=> L1 descriptor fixes (4-3-stable)

plugins/database/src/mid_level_routines.cpp, scripts/irods/test/test_iticket.py
Running unit tests and core tests.
=> [#5913] Restored ability to create data objects using write tickets (main)

scripts/irods/test/test_iquest.py, server/api/src/rsGenQuery.cpp
Addresses #6101 
Cherry-picked from #6751 
Running tests
=> [#6101] Fix GenQuery operators for DATA_RESC_HIER (4-3-stable)

scripts/irods/test/test_iquest.py, server/api/src/rsGenQuery.cpp
Addresses #6101
Cherry-picked and adapted from #6751 
All tests passed. Will squash the "adaptation" commits upon successful review.
=> [#6101] Fix GenQuery operators for DATA_RESC_HIER (4-2-stable)

scripts/irods/test/test_federation.py, scripts/irods/test/test_irepl.py, scripts/irods/test/test_irm.py, scripts/irods/test/test_rulebase.py, server/api/include/irods/rsModColl.hpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsModColl.cpp
Addresses #6068
Addresses #6100 
Addresses #6285
Addresses #6365 
Addresses #6428 
Unit tests passed. Core tests are running now.
Confirmed that test for #6428 passes when run in topology from provider and consumer. Noticed that some other tests failed, so I will need to look into these.
=> Various bug fixes and tests (main)

scripts/irods/test/test_auth.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_native_rule_engine_plugin.py, scripts/irods/test/test_quotas.py, scripts/irods/test/test_resource_types.py, scripts/irods/test/test_rule_engine_plugin_framework.py, scripts/irods/test/test_rulebase.py
Remove unneeded sleep calls. Ran core tests and all passed.
=> [2279] Remove unneeded sleep calls, leave imports for other functions (4-3-stable)

scripts/irods/test/test_federation.py, scripts/irods/test/test_irepl.py, scripts/irods/test/test_irm.py, scripts/irods/test/test_rulebase.py, server/api/include/irods/rsModColl.hpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsModColl.cpp
Addresses https://github.com/irods/irods/issues/6068
Addresses https://github.com/irods/irods/issues/6100
Addresses https://github.com/irods/irods/issues/6285
Addresses https://github.com/irods/irods/issues/6365
Addresses https://github.com/irods/irods/issues/6428
Cherry-picked from #6799
=> Various bug fixes and tests (4-3-stable)

scripts/irods/lib.py, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_irepl.py, scripts/irods/test/test_irm.py, scripts/irods/test/test_rulebase.py, server/api/include/rsModColl.hpp, server/api/src/rsDataObjCopy.cpp, server/api/src/rsDataObjRepl.cpp, server/api/src/rsModColl.cpp, server/core/include/catalog_utilities.hpp, server/core/src/catalog_utilities.cpp
Addresses https://github.com/irods/irods/issues/6068
Addresses https://github.com/irods/irods/issues/6100
Addresses https://github.com/irods/irods/issues/6285
Addresses https://github.com/irods/irods/issues/6365
Addresses https://github.com/irods/irods/issues/6428
Addresses https://github.com/irods/irods/issues/6838
Cherry-picked and adapted from https://github.com/irods/irods/pull/6836
Note the base commit which was cherry-picked from main so that I could build this.
Running core tests again
=> Various bug fixes and tests (4-2-stable) 

plugins/api/include/irods/plugins/api/api_plugin_number.h, plugins/api/include/irods/plugins/api/api_plugin_number_map.hpp
=> Fixed potential ODR violations for API plugin number headers (4-3-stable)

plugins/api/include/api_plugin_number_map.hpp
=> Fixed potential ODR violation for API plugin number header (4-2-stable)

lib/core/src/obf.cpp, scripts/irods/lib.py, scripts/irods/test/test_misc.py
This is a test to go along with the corresponding iinit change in icommands.
=> [5411] Test for `iinit`

lib/core/src/obf.cpp, scripts/irods/lib.py, scripts/irods/test/test_misc.py
Create test for iinit, refactor and improve error returned
from obf.cpp.
Cherry-picked from #6787.
=> [5411] Test and Improvements for iinit

scripts/irods/test/test_itouch.py
=> [6434] Update itouch tests to check return code (4-3-stable)

lib/core/include/irods/key_value_proxy.hpp, plugins/api/src/replica_close.cpp, plugins/resources/src/compound.cpp, scripts/irods/test/test_resource_types.py, server/api/src/rsDataObjPut.cpp, server/core/src/initServer.cpp, server/core/src/rodsAgent.cpp, unit_tests/cmake/test_config/irods_key_value_proxy.cmake, unit_tests/src/test_replica_access_table.cpp
Addresses https://github.com/irods/irods/issues/6154
Addresses https://github.com/irods/irods/issues/6378
Addresses https://github.com/irods/irods/issues/6479
Addresses https://github.com/irods/irods/issues/6880
Addresses https://github.com/irods/irods/issues/6882
Addresses https://github.com/irods/irods/issues/6886
Cherry-picked from https://github.com/irods/irods/pull/6884
Core tests and unit tests passed
=> Ensure that data objects cannot get stuck in locked status (4-3-stable)

scripts/irods/test/test_itouch.py
=> [#6434] Update itouch tests to check return code (main)

scripts/irods/test/test_igroupadmin.py, server/api/src/rsUserAdmin.cpp
cherry-picked after applying review changes  and running full CI suite with all tests passing
=> [#6887] allow igroupadmin mkuser to initialize the new user's password (main)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_imeta_set.py
=> [4063] Ensure AVUs set properly (main)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_imeta_set.py
Cherry-pick of #6853.
Ran core & cpp tests, all passed.
=> [4063] Ensure AVUs set properly (4-3-stable)

scripts/irods/test/test_iqstat.py
To go along with https://github.com/irods/irods_client_icommands/pull/349
=> [#6740] tests for iqstat (4-2-stable)

scripts/core_tests_list.json, scripts/irods/database_upgrade.py, scripts/irods/test/test_specific_queries.py, version.json.dist.in
=> [#6900] Restored specific query, DataObjInCollReCur, for MySQL 8 (4-3-stable)

scripts/irods/test/test_configuration_reload.py
Addresses #6956
There are two commits in this pull request. They are alternative solutions, so only one should be accepted. Please read the commit messages for explanations.
=> Fix test_reload_command__issue_6529 (main)

scripts/irods/test/test_configuration_reload.py
Addresses #6956
Cherry-picked from https://github.com/irods/irods/pull/6957
=> [#6956] Config reload test asserts changes in test-running host (4-3-stable)

lib/core/src/irods_client_negotiation.cpp, scripts/irods/test/test_federation.py
Addresses #6827
Tests are running now
=> [#6827] Search all catalog_provider_hosts in federation stanza (main)

scripts/irods/test/test_quotas.py
=> [#3513] Added use of istream to quota test case (4-3-stable)

lib/core/src/irods_client_negotiation.cpp, scripts/irods/test/test_federation.py
Addresses https://github.com/irods/irods/issues/6827
Cherry-picked from https://github.com/irods/irods/pull/6950
Some adaptations had to be made for this cherry-pick due to how the server configuration interface changed between 4-2-stable and main/4-3-stable.
Core tests, unit tests, and federation tests passed
=> [#6827] Search all catalog_provider_hosts in federation stanza (4-2-stable)

scripts/irods/test/test_iquest.py, server/api/src/rsGenQuery.cpp
Addresses #6912 
Cherry-picked/Adapted from #6955 
The adaptation was exclusively in the tests:
- Replaced f-strings with `str.format`
- Removed `unittest.subTest` because it's not available in python2's version of `unittest`
Core tests and unit tests passed
=> [#6912] GenQuery: Add support for || with DATA_RESC_HIER (4-2-stable)

server/control_plane/CMakeLists.txt
In service of #6974 
Cherry-picked from https://github.com/irods/irods/pull/6978
NB: @ll4strw has author credit
=> [#6974] Fixed LD_LIBRARY_PATH for avrogencpp. (4-3-stable)

CMakeLists.txt, cmake/development_library.cmake, doxygen/microservices.cpp, lib/core/include/msParam.h, lib/core/include/objInfo.h, lib/core/include/process_stash.hpp, lib/core/include/rodsErrorTable.h, lib/core/src/msParam.cpp, lib/core/src/process_stash.cpp, plugins/microservices/CMakeLists.txt, plugins/microservices/msi_json/CMakeLists.txt, plugins/microservices/msi_json/json_common.hpp, plugins/microservices/msi_json/json_compare.cpp, plugins/microservices/msi_json/json_contains.cpp, plugins/microservices/msi_json/json_dump.cpp, plugins/microservices/msi_json/json_free.cpp, plugins/microservices/msi_json/json_handles.cpp, plugins/microservices/msi_json/json_names.cpp, plugins/microservices/msi_json/json_parse.cpp, plugins/microservices/msi_json/json_size.cpp, plugins/microservices/msi_json/json_type.cpp, plugins/microservices/msi_json/json_value.cpp, plugins/microservices/msi_json/msi_preconditions.hpp, plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/conversion.cpp, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_iexit.py
=> Microservices for JSON data / per-process key-value store API (4-2-stable)

unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_process_stash.cmake, unit_tests/src/test_process_stash.cpp, unit_tests/unit_tests_list.json
Passed in the testing environment.
=> [#6999] Added unit test for irods::process_stash library (4-2-stable)

unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_process_stash.cmake, unit_tests/src/test_process_stash.cpp, unit_tests/unit_tests_list.json
=> [#6999] Added unit test for irods::process_stash library (4-3-stable)

plugins/resources/compound/libcompound.cpp
Delete replica in cache when staging to cache fails
=> [7002] Use replica status for staging decision (4-2-stable)

plugins/database/src/db_plugin.cpp
Cherry-pick of #6977. Ran tests, all passed!
=> [6495] Improve imkdir inheritance performance (4-3-stable)

plugins/database/src/db_plugin.cpp
=> [#6495] Improve imkdir inheritance performance (main)

scripts/irods/lib.py
=> [#6690] Added lib.remove_file_if_exists() and lib.make_arbitrary_file() (main)

scripts/irods/lib.py
=> [#6690] Added lib.remove_file_if_exists() and lib.make_arbitrary_file() (4-3-stable)

packaging/core.re.template, plugins/database/src/db_plugin.cpp, plugins/resources/src/compound.cpp, plugins/resources/src/mockarchive.cpp, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_resource_types.py
This is a cherry-pick from 4-2-stable with minor necessary changes.
It has passed all CI and unit tests.
=> Issue 6502 main

scripts/irods/test/test_itree.py
Testing for path arguments to itree which are not collections, or do not exist.
=> [#6627] tests for itree with invalid arguments (4-2-stable)

scripts/irods/test/test_itree.py
Cherry-picked from https://github.com/irods/irods/pull/7007
Testing for path arguments to itree which are not collections, or do not exist.
=> [_6627] tests for itree with invalid arguments. (main)

scripts/irods/test/test_itree.py
Cherry-picked from https://github.com/irods/irods/pull/7025
Testing for path arguments to itree which are not collections, or do not exist.
=> [_6627] tests for itree with invalid arguments.(4-3-stable)

plugins/resources/src/compound.cpp, plugins/resources/src/passthru.cpp, scripts/core_tests_list.json, scripts/irods/lib.py, scripts/irods/test/test_targeting_specific_replica_number.py, server/api/src/rsDataObjOpen.cpp, server/core/include/irods/voting.hpp, server/core/src/irods_resource_redirect.cpp, server/core/src/voting.cpp
Addresses #6896
Core tests are now running
=> [#6896] Requested replica always wins the vote (main)

plugins/resources/src/compound.cpp, plugins/resources/src/passthru.cpp, scripts/core_tests_list.json, scripts/irods/lib.py, scripts/irods/test/test_targeting_specific_replica_number.py, server/api/src/rsDataObjOpen.cpp, server/core/include/irods/voting.hpp, server/core/src/irods_resource_redirect.cpp, server/core/src/voting.cpp
Addresses #6896 
Cherry-picked from #6923
=> [#6896] Requested replica always wins the vote (4-3-stable)

plugins/microservices/msi_tests/CMakeLists.txt, plugins/microservices/msi_tests/libmsi_test_scoped_client_identity.cpp, plugins/microservices/msi_tests/libmsi_test_scoped_permission.cpp, plugins/microservices/msi_tests/msi_assertion_macros.hpp, plugins/resources/compound/libcompound.cpp, scripts/irods/test/resource_suite.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_misc.py, scripts/irods/test/test_resource_types.py, server/api/src/rsDataObjUnlink.cpp, server/api/src/rsModAccessControl.cpp, server/api/src/rsModColl.cpp, server/core/include/scoped_permission.hpp
In service of #6997 
Core tests and topology tests pass (still need to run unit tests)
=> [#6997] Fix stage-to-cache with read-only permission (4-2-stable)

lib/core/src/fsckUtil.cpp, scripts/irods/test/test_ifsck.py
Fix for 6467 on main branch.  I made one change to the test which is in its own commit.
All tests (CI and unit) passed.
=> Issue 6367 main

plugins/resources/src/compound.cpp, scripts/irods/test/resource_suite.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_ibun.py, scripts/irods/test/test_resource_types.py, scripts/irods/test/test_targeting_specific_replica_number.py
Addresses #6997 
Reverts work done for #7038 
Cherry-picked from #7055 
Tests are running now
=> [#6997] Stage-to-cache is performed by admin user (main)

scripts/irods/test/test_all_rules.py, server/re/src/reDataObjOpr.cpp
Addresses #6118 
Unit tests passed. Running other tests now
=> [#6118] msiDataObjChksum: Add ADMIN_KW for admins (4-2-stable)

lib/core/src/msParam.cpp, scripts/irods/test/test_all_rules.py, server/re/src/reDataObjOpr.cpp
Cherry-pick of #7049. All tests passed!
=> [#6918] Correct msiAddKeyVal behavior (4-3-stable)

lib/core/src/msParam.cpp, scripts/irods/test/test_all_rules.py, server/re/src/reDataObjOpr.cpp
=> [#6918] Correct msiAddKeyVal behavior (main)

scripts/irods/test/test_all_rules.py, server/re/src/reDataObjOpr.cpp
Addresses #6118 
Cherry-picked from #7062 
Unit tests passed, core tests are running but almost finished
The only diff with 4-2-stable is shown in the latest commit.
=> [#6118] msiDataObjChksum: Add ADMIN_KW for admins (main)

scripts/irods/test/test_all_rules.py, server/re/src/reDataObjOpr.cpp
Addresses #6118
Cherry-picked from #7070
=> [#6118] msiDataObjChksum: Add ADMIN_KW for admins (4-3-stable) 

plugins/resources/src/compound.cpp, server/api/src/rsDataObjClose.cpp, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRepl.cpp, server/core/include/irods/finalize_utilities.hpp, server/core/src/finalize_utilities.cpp
Addresses #6997
Cherry-picked from #7073 
Uses the same tests in S3 as the change in main: https://github.com/irods/irods_resource_plugin_s3/pull/2108
=> [#6997] Add admin keyword support to trim_replica (4-3-stable)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_all_rules.py, server/core/src/objMetaOpr.cpp
Addresses #7050
Cherry-picked from #7082
=> Fix statement leaks (4-3-stable)

scripts/irods/test/test_rulebase.py
=> [#4094] Skip NREP-only test for PREP (main)

scripts/irods/test/test_rulebase.py
=> [#4094] Skip NREP-only test for PREP (4-3-stable)

scripts/irods/test/test_misc.py
Addresses #5411
Cherry-picked from #7092
=> [#5411] Skip iinit test when SSL is enabled (main)

scripts/irods/test/test_misc.py
Addresses #5411 
Cherry-picked from #7093
=> [#5411] Skip iinit test when SSL is enabled (4-3-stable)

scripts/irods/test/test_rulebase.py
Addresses #2279
This change will only exist in 4-2-stable.
=> [#2279] Skip fast updates test when SSL is enabled (4-2-stable)

scripts/irods/test/test_targeting_specific_replica_number.py
=> [#7133] Add test for ichksum -n (main)

scripts/irods/test/test_targeting_specific_replica_number.py
Addresses #7133 
Cherry-picked from https://github.com/irods/irods/pull/7135
=> [#7133] Add test for ichksum -n (4-3-stable)

scripts/irods/test/test_targeting_specific_replica_number.py
Addresses #7133 (the rest of it)
Tests passed
=> [#7133] Add test for msiDataObjChksum replNum keyword (main)

scripts/irods/test/test_targeting_specific_replica_number.py
Addresses #7133 
Cherry-picked from #7146
=> [#7133] Add test for msiDataObjChksum replNum keyword (4-3-stable)

lib/core/include/irods/irods_configuration_keywords.hpp, lib/core/src/irods_configuration_keywords.cpp, packaging/server_config.json.template, schemas/configuration/v4/server_config.json.in, server/main_server/src/rodsServer.cpp
Addresses #6342 
Addresses #6370 
Cherry-picked from #6762
=> Expose some new configuration values (CRON tasks, socket timeouts) (4-3-stable)

scripts/irods/lib.py, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_dynamic_peps.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_ibun.py, scripts/irods/test/test_ichksum.py, scripts/irods/test/test_iget.py, scripts/irods/test/test_iquest.py, scripts/irods/test/test_ireg.py, scripts/irods/test/test_irepl.py, scripts/irods/test/test_itrim.py, scripts/irods/test/test_resource_types.py, scripts/irods/test/test_rulebase.py, scripts/irods/test/test_special_collections.py, scripts/irods/test/test_targeting_specific_replica_number.py
Rename user parameter to session and make it the first parameter
=> [7152] Refactor lib.py functions (4-3 stable)

lib/core/include/irods/irods_load_plugin.hpp
Addresses #7158 for main.
Prerequisite for irods/irods_rule_engine_plugin_python#157
=> [#7158] Determine RTLD flags from DT_FLAGS_1 for loading plugins

scripts/irods/test/test_iticket.py
Connected to https://github.com/irods/irods_client_icommands/pull/395
=> [7103] Test for iticket create with relative paths (main)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iticket.py
Update the modification time for tickets in the catalog
=> [7125] Update modification time for tickets (main)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iticket.py
Update the modification time for tickets in the catalog Add auto rollback to ticket operations on fail
Cherry picked from https://github.com/irods/irods/pull/7129.
=> [7125] Update modification time for tickets (4-3-stable)

scripts/irods/test/test_auth.py
Addresses #7102
Addresses #7120 
Cherry-picked from #7189
=> [#7102,#7120] Fail auth test when missing irodsauthuser (4-3-stable)

server/core/include/irods/irods_file_object.hpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_file_object.cmake, unit_tests/src/test_file_object.cpp, unit_tests/unit_tests_list.json
=> [7154] Change irods::file_object size to rodsLong_t (4-3-stable)

unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_file_object.cmake, unit_tests/src/test_file_object.cpp, unit_tests/unit_tests_list.json
=> [7154] Unit test for irods::file_object size (main)

lib/core/include/irods/getRodsEnv.h, lib/core/src/getRodsEnv.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_environment_variables.cmake, unit_tests/src/test_environment_variables.cpp, unit_tests/unit_tests_list.json
Cherry pick from https://github.com/irods/irods/pull/7184
=> [6866] Add bound checks for environment variables (4-3-stable)

lib/administration/ticket/include/irods/ticket_administration.hpp, server/core/src/rodsAgent.cpp
=> A couple of small fixes for libstdc++ (main)

.clang-tidy, doxygen/microservices.cpp, lib/core/src/getUtil.cpp, lib/core/src/putUtil.cpp, scripts/irods/test/test_all_rules.py, server/re/CMakeLists.txt, server/re/include/irods/reAction.hpp, server/re/src/icatAdminMS.cpp, server/re/src/irods_re_serialization.cpp, unit_tests/cmake/test_config/irods_environment_variables.cmake
Still need to write a test for the microservice.
=> Multiple simple improvements (main)

.clang-tidy, doxygen/microservices.cpp, lib/core/src/getUtil.cpp, lib/core/src/putUtil.cpp, scripts/irods/test/test_all_rules.py, server/re/CMakeLists.txt, server/re/include/irods/reAction.hpp, server/re/src/icatAdminMS.cpp, server/re/src/irods_re_serialization.cpp, unit_tests/cmake/test_config/irods_environment_variables.cmake
=> Multiple simple improvements (4-3-stable)

lib/core/include/irods/getRodsEnv.h, lib/core/include/irods/irods_configuration_keywords.hpp, lib/core/include/irods/rodsErrorTable.h, lib/core/include/irods/sockComm.h, lib/core/src/getRodsEnv.cpp, lib/core/src/irods_configuration_keywords.cpp, lib/core/src/sockComm.cpp, schemas/configuration/v4/service_account_environment.json.in, scripts/irods/test/test_misc.py, server/core/src/miscServerFunct.cpp
Addresses https://github.com/irods/irods/issues/2533, https://github.com/irods/irods/issues/3824
Cherry-picked from  #7215
=> [#2533,#3824] Add TCP keepalive option configs (4-3-stable)

lib/core/include/irods/rodsError.h, lib/core/src/clientLogin.cpp, lib/core/src/rcConnect.cpp, lib/core/src/rcMisc.cpp, lib/core/src/rodsError.cpp, scripts/irods/test/test_ipasswd.py
Addresses #7048, #7161
Cherry-picked from https://github.com/irods/irods/pull/7149
=> [#7048,#7161] Use error stack for clientLogin (4-3-stable)

scripts/irods/test/test_resource_types.py, unit_tests/src/test_rc_data_obj.cpp
=> Add tests for dataSize of -1 (main)

scripts/irods/test/test_resource_types.py, unit_tests/src/test_rc_data_obj.cpp
=> Add tests for dataSize of -1 (4-3-stable)

server/api/src/rsDataObjGet.cpp
=> [#6260] Get API: Clarify log message (main)

server/api/src/rsDataObjGet.cpp
Addresses #6260
Cherry-picked from https://github.com/irods/irods/pull/7257
=> [#6260] Get API: Clarify log message (4-3-stable)

plugins/database/src/db_plugin.cpp, plugins/database/src/general_query.cpp, plugins/database/src/mid_level_routines.cpp, unit_tests/src/test_rc_data_obj.cpp, unit_tests/src/unit_test_utils.hpp
I verified that the unit tests correctly reproduces the issue of #7250.
Will run unit and core tests.
=> [#7250] Updating ticket stats now call commit or rollback (main)

plugins/database/src/db_plugin.cpp, plugins/database/src/general_query.cpp, plugins/database/src/mid_level_routines.cpp, unit_tests/src/test_rc_data_obj.cpp, unit_tests/src/unit_test_utils.hpp
=> [#7250] Updating ticket stats now call commit or rollback (4-3-stable)

server/api/src/rsDataObjRsync.cpp
This is caused by rsSyncDataToData performing a checksum on a potentially nonexistent data object. If it doesn't exist, it will toss out a CAT_NO_ROWS_FOUND, which is caught and produces the stacktrace.
=> [7134] msiCollRsync spurious stacktrace (main)

server/api/src/rsDataObjRsync.cpp
=> [7134] msiCollRsync spurious stacktrace (4-3-stable)

lib/core/CMakeLists.txt, lib/core/include/irods/rcMisc.h, lib/core/src/cpUtil.cpp, lib/core/src/lsUtil.cpp, lib/core/src/mcollUtil.cpp, lib/core/src/miscUtil.cpp, lib/core/src/msParam.cpp, lib/core/src/putUtil.cpp, lib/core/src/rcMisc.cpp, lib/core/src/rmUtil.cpp, lib/core/src/rmtrashUtil.cpp, plugins/api/src/atomic_apply_acl_operations.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, plugins/api/src/register_physical_path.cpp, plugins/api/src/switch_user.cpp, server/api/src/rsDataObjOpen.cpp, server/api/src/rsDataObjRename.cpp, server/api/src/rsDataObjTrim.cpp, server/api/src/rsExecMyRule.cpp, server/api/src/rsGeneralAdmin.cpp, server/api/src/rsGetHostForGet.cpp, server/api/src/rsRmColl.cpp, server/api/src/rsServerReport.cpp, server/api/src/rsZoneReport.cpp, server/core/src/irods_file_object.cpp
All unit tests and core tests passed.
All leaks fixed by this PR were discovered by running the unit tests with address sanitizer enabled.
We need to do the same thing with the core tests at some point.
=> Address Sanitizer fixes (main)

scripts/irods/test/test_icommands_file_operations.py, scripts/irods/test/test_iput.py, scripts/irods/test/test_iput_options.py, server/api/src/rsBulkDataObjPut.cpp
Addresses #7110 
Cherry-picked from #7244
=> [#7110] Disallow iput -rbf (4-3-stable)

plugins/auth/src/pam_password.cpp, plugins/auth_legacy/src/pam.cpp, plugins/database/src/db_plugin.cpp, server/api/src/rsPamAuthRequest.cpp, server/icat/include/irods/icatHighLevelRoutines.hpp, server/icat/src/icatHighLevelRoutines.cpp
Addresses #7098 
Cherry-picked from https://github.com/irods/irods/pull/7245
=> [#7098] pam_password: Remove password_length config (4-3-stable)

plugins/database/src/db_plugin.cpp, unit_tests/src/test_irods_lifetime_manager.cpp
=> Trivial bug fixes (4-3-stable)

lib/core/include/irods/connection_pool.hpp, lib/core/src/connection_pool.cpp, unit_tests/src/test_connection_pool.cpp, unit_tests/src/test_metadata.cpp
=> [#7287] Connection pool's behavior is now configurable (4-3-stable)

scripts/irods/lib.py, scripts/setup_irods.py
=> [7023] fix swapping of provider/consumer in setup_irods.py (4-3-stable)

scripts/setup_irods.py
oops, missed this in my local diff.
added some comments.
same as https://github.com/irods/irods/pull/7307
=> [7023] fix for catalog_service_roles, no longer a set (main)

server/delay_server/src/irodsDelayServer.cpp
This appears to fail tests, though I'm baffled as to why. Putting this here to get more eyes on it, maybe?
The last run I had, these tests fail: 
EDIT: 
```
test_resource_types.Test_Resource_Replication test_resource_types.Test_Resource_ReplicationToTwoCompoundResourcesWithPreferArchive test_resource_types.Test_Resource_WeightedPassthru test_rule_engine_plugin_framework test_rule_engine_plugin_passthrough test_rulebase test_specific_queries test_ssl test_symlink_operations test_targeting_specific_replica_number
```
Observed behaviors:
Commenting out line 845 does not appear to fix it; simply calling the function in the loop causes the issue
Commenting out lines 695 - 719 (and manually returning true) **does** appear to fix the issue
The function never returns false during testing.
=> Leader conflict draft

server/delay_server/src/irodsDelayServer.cpp
Cherry-pick of #7294. Tests pass.
=> No more leader conflict (4-3-stable)

lib/filesystem/src/filesystem.cpp
=> [#7327] Filesystem library now understands 4.2 permission strings (main)

.github/workflows/build-irods-debian.yml, .github/workflows/build-irods-ubuntu.yml, lib/core/include/irods/irods_configuration_keywords.hpp, lib/core/include/irods/irods_random.hpp, lib/core/include/irods/rodsErrorTable.h, lib/core/src/irods_configuration_keywords.cpp, lib/core/src/irods_random.cpp, plugins/api/src/set_grid_configuration_value.cpp, plugins/database/CMakeLists.txt, plugins/database/src/db_plugin.cpp, scripts/core_tests_list.json, scripts/irods/database_upgrade.py, scripts/irods/test/test_iadmin_set_grid_configuration.py, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_generate_random_alphanumeric_string.cmake, unit_tests/src/test_generate_random_alphanumeric_string.cpp, unit_tests/unit_tests_list.json
In service of #6597
Addresses #7098 
In service of #7266 
In service of #7283 
Addresses #7274 
Companion PR: https://github.com/irods/irods_client_icommands/pull/407
=> Move auth configs to `R_GRID_CONFIGURATION`, plus fixes (main)

.github/workflows/build-irods-debian.yml, .github/workflows/build-irods-ubuntu.yml, lib/core/include/irods/irods_configuration_keywords.hpp, lib/core/include/irods/irods_random.hpp, lib/core/include/irods/rodsErrorTable.h, lib/core/src/irods_configuration_keywords.cpp, lib/core/src/irods_random.cpp, plugins/api/src/set_grid_configuration_value.cpp, plugins/database/CMakeLists.txt, plugins/database/src/db_plugin.cpp, scripts/core_tests_list.json, scripts/irods/database_upgrade.py, scripts/irods/test/test_iadmin_set_grid_configuration.py, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_generate_random_alphanumeric_string.cmake, unit_tests/src/test_generate_random_alphanumeric_string.cpp, unit_tests/unit_tests_list.json
In service of https://github.com/irods/irods/issues/6597
Addresses https://github.com/irods/irods/issues/7098
In service of https://github.com/irods/irods/issues/7266
Addresses https://github.com/irods/irods/issues/7274
In service of https://github.com/irods/irods/issues/7283
Companion PR: https://github.com/irods/irods_client_icommands/pull/415
Cherry-picked from https://github.com/irods/irods/pull/7331
=> Move auth configs to R_GRID_CONFIGURATION, plus fixes (4-3-stable)

lib/api/src/rc_atomic_apply_acl_operations.cpp, lib/api/src/rc_atomic_apply_metadata_operations.cpp, lib/api/src/rc_data_object_finalize.cpp, lib/api/src/rc_get_file_descriptor_info.cpp, lib/api/src/rc_replica_open.cpp, plugins/api/src/atomic_apply_acl_operations.cpp, plugins/api/src/atomic_apply_metadata_operations.cpp, plugins/api/src/data_object_finalize.cpp, plugins/api/src/data_object_modify_info.cpp, plugins/api/src/get_file_descriptor_info.cpp, plugins/api/src/register_physical_path.cpp, plugins/api/src/replica_close.cpp, plugins/api/src/replica_open.cpp, plugins/api/src/touch.cpp, unit_tests/src/test_atomic_apply_acl_operations.cpp, unit_tests/src/test_atomic_apply_metadata_operations.cpp, unit_tests/src/test_data_object_finalize.cpp, unit_tests/src/test_data_object_modify_info.cpp, unit_tests/src/test_get_file_descriptor_info.cpp, unit_tests/src/test_rc_data_obj.cpp, unit_tests/src/test_replica_open_and_close.cpp
=> Updated API plugin configurations (4-3-stable)

plugins/database/src/db_plugin.cpp, scripts/core_tests_list.json, scripts/irods/database_upgrade.py, scripts/irods/test/test_auth.py, scripts/irods/test/test_pam_password.py
In service of #7274 
New test passes and unit tests are passing. Running core tests.
=> Fixes and tests for auth configuration (main)

plugins/database/src/db_plugin.cpp, scripts/core_tests_list.json, scripts/irods/database_upgrade.py, scripts/irods/test/test_auth.py, scripts/irods/test/test_pam_password.py
In service of #7274 
Cherry-picked from #7347
=> Fixes and tests for auth configuration (4-3-stable)

lib/api/include/irods/get_resource_info_for_operation.h, server/api/include/irods/rs_get_resource_info_for_operation.hpp, server/api/src/rs_get_resource_info_for_operation.cpp, unit_tests/src/test_get_resource_info_for_operation.cpp, unit_tests/unit_tests_list.json
The unit test passes at the bench.
Will check the documentation to verify it is rendered correctly.
=> [#7256] Unit tests and other tweaks to new API endpoint (main)

lib/core/src/clientLogin.cpp, plugins/database/src/db_plugin.cpp, scripts/core_tests_list.json, scripts/irods/database_upgrade.py, scripts/irods/test/test_iadmin_set_grid_configuration.py, scripts/irods/test/test_native_authentication.py, scripts/irods/test/test_pam_password_authentication.py
Addresses #7274
Cherry-picked from #7356
=> Make auth config namespace more general, fix native auth config, and add more tests (4-3-stable)

CMakeLists.txt
Cherry-pick of #7366
Addresses #7364 for 4-3-stable
=> [#7364] Relax version matching for find_package (4-3-stable)

lib/api/include/irods/apiTable.hpp, lib/core/include/irods/rcMisc.h, lib/core/src/rcMisc.cpp, plugins/api/src/set_grid_configuration_value.cpp, scripts/irods/lib.py, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_ireg.py, scripts/irods/test/test_pam_password_authentication.py, scripts/irods/test/test_rulebase.py, server/api/src/rsTicketAdmin.cpp
Possibly addresses #7000
Cherry-picked from https://github.com/irods/irods/pull/6995
---
Haven't run topology tests all the way through (keeps failing due to #6954 at random places) but putting this up for transparent progress.
=> [#7000] Fix tests for running in topology (main)

lib/api/include/irods/apiTable.hpp, lib/core/include/irods/rcMisc.h, lib/core/src/rcMisc.cpp, plugins/api/src/set_grid_configuration_value.cpp, scripts/irods/lib.py, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_ireg.py, scripts/irods/test/test_pam_password_authentication.py, scripts/irods/test/test_rulebase.py, server/api/src/rsTicketAdmin.cpp
Addresses #7000
Cherry-picked from https://github.com/irods/irods/pull/7363
=> [#7000] Fix tests for running in topology (4-3-stable)

lib/core/src/process_stash.cpp
cherry-pick of https://github.com/irods/irods/pull/7405
=> [858] fix typo (4-3-stable)

server/core/include/irods/rodsConnect.h
=> [7418] Re-remove resolveHostByDataObjInfo declaration (main)

server/core/include/irods/rodsConnect.h
Addresses #7418 for 4-3-stable
=> [7418] Re-remove resolveHostByDataObjInfo declaration (4-3-stable)

scripts/irods/test/test_native_authentication.py, scripts/irods/test/test_pam_password_authentication.py
Adds test for #3742 and #5096
The tests both pass.
=> [#3742][#5096] Add test for password_max_time > 1209600 (main)

scripts/irods/test/test_native_authentication.py, scripts/irods/test/test_pam_password_authentication.py
Adds tests for #3742 and #5096
Cherry-picked from #7417
=> [#3742][#5096] Add test for password_max_time > 1209600 (4-3-stable)

scripts/irods/test/test_prep_genquery_iterator.py, scripts/irods/test/test_resource_types.py, scripts/irods/test/test_rulebase.py
In service of irods/irods_rule_engine_plugin_python#183
Companion to irods/irods_rule_engine_plugin_python#185
=> [irods/irods_rule_engine_plugin_python#183] PREP tests: update references to global_vars (main)

plugins/resources/src/structfile.cpp, scripts/irods/test/test_ibun.py
All tests passed.
I verified the new test failed when the code changes were not included and passed with the code changes.
=> [7474] Changed ibun tar format from ustar to pax (4-3-stable)

plugins/resources/src/structfile.cpp, scripts/irods/test/test_ibun.py
This is the exact same as the pull request for 4-3-stable.  All tests were re-run and passed.  I also verified the new test passed when the skip was removed and failed when the code change was not in place.
=> [7474] Changed ibun tar format from ustar to pax (main)

LICENSE
=> Update license file (4-3-stable)

cmake/packaging.cmake, scripts/irods/database_connect.py, scripts/irods/database_upgrade.py
cherry-pick of #7485 into 4-3-stable
=> [#7345,#7469,#7484] A few mariadb fixes (4-3-stable)

plugins/resources/replication/src/irods_create_write_replicator.cpp, scripts/irods/test/replica_status_test.py, scripts/irods/test/resource_suite.py, scripts/irods/test/test_delay_queue.py, scripts/irods/test/test_irepl.py, scripts/irods/test/test_resource_types.py, scripts/run_tests.py, server/api/src/rsDataObjRepl.cpp, server/core/src/voting.cpp
=> Change voting for write operations + associated replication fallout (4-3-stable)

.github/workflows/build-irods-debian.yml, .github/workflows/build-irods-ubuntu.yml, .github/workflows/linter-irods-clang-tidy.yml, cmake/packaging.cmake
All unit tests pass for Ub20/22.
Preparing to run core tests for those platforms.
=> [#7525] Remove dependency on "super" package (main)

server/re/src/reDataObjOpr.cpp
=> [6435] update msiDataObjChksum documentation (4-3-stable)

.github/workflows/build-irods-debian.yml, .github/workflows/build-irods-ubuntu.yml, .github/workflows/linter-irods-clang-tidy.yml, cmake/packaging.cmake
=> [#7525] Remove dependency on "super" package (4-3-stable)

doxygen/microservices.cpp, server/re/src/mailMS.cpp
=> [#7562] Deprecate msiSendMail (4-3-stable)

lib/core/src/irods_parse_command_line_options.cpp, lib/core/src/parseCommandLine.cpp, scripts/irods/test/test_iput.py, scripts/irods/test/test_irsync.py
=> [#7537] Add `--ignore-symlinks` alias for `--link` option (main)

scripts/irods/test/test_iadmin.py, server/api/src/rsGeneralAdmin.cpp
Cherry-pick of https://github.com/irods/irods/pull/7533
=> Server-side code to only allow removal of appropriate entity (4-3-stable)

lib/administration/user/src/user_administration.cpp
Cherry-pick of https://github.com/irods/irods/pull/7589
=> [7380] Fix user_administration library to account for new API changes (4-3-stable)

lib/api/include/irods/dataObjRepl.h, lib/api/src/rcDataObjRepl.cpp, lib/core/include/irods/msParam.h, lib/core/include/irods/objInfo.h, lib/core/include/irods/parseCommandLine.h, lib/core/include/irods/rodsKeyWdDef.h, lib/core/src/replUtil.cpp, packaging/core.dvm.template, plugins/rule_engines/irods_rule_language/src/reVariableMap.gen.cpp, server/api/src/rsChkObjPermAndStat.cpp, server/core/src/irods_resource_backport.cpp, server/core/src/irods_resource_redirect.cpp, server/re/src/reDataObjOpr.cpp
Addresses #6953 
Cherry-picked from https://github.com/irods/irods/pull/7591
Companion PR: https://github.com/irods/irods_client_icommands/pull/458
=> [#6953] Deprecate BACKUP_RESC_NAME_KW (4-3-stable)

lib/api/include/irods/apiNumberData.h, lib/api/include/irods/apiTable.hpp, lib/api/include/irods/generalUpdate.h, lib/core/include/irods/rodsGeneralUpdate.h, plugins/database/src/db_plugin.cpp, plugins/database/src/general_update.cpp, server/api/include/irods/rsGeneralUpdate.hpp, server/api/src/rsGeneralUpdate.cpp, server/core/include/irods/irods_api_calling_functions.hpp, server/core/include/irods/irods_database_constants.hpp, server/core/src/irods_api_calling_functions.cpp, server/icat/include/irods/icatHighLevelRoutines.hpp
=> [#7554] Deprecate GeneralUpdate API (4-3-stable)

scripts/irods/test/test_native_rule_engine_plugin.py, server/re/src/icatGeneralMS.cpp
=> [#7319] Make `msiSetResource` not crash agent (4-3-stable)

scripts/core_tests_list.json, scripts/irods/lib.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_irepl.py, server/api/src/rsDataObjRepl.cpp
Addresses #7444 
Addresses #7465 
Need to run full test suite. New tests pass, of course.
=> [#7444,#7465] Prevent replication with insufficient permissions (main)

scripts/core_tests_list.json, scripts/irods/lib.py, scripts/irods/test/test_federation.py, scripts/irods/test/test_irepl.py, server/api/src/rsDataObjRepl.cpp
Addresses https://github.com/irods/irods/issues/7444
Addresses https://github.com/irods/irods/issues/7465
Cherry-picked from https://github.com/irods/irods/pull/7593
=> [#7444,#7465] Prevent replication with insufficient permissions (4-3-stable)

server/core/src/rodsAgent.cpp
=> [#7614] Improve handling of invalid message during agent initialization (4-3-stable)

README.md, SECURITY.md
=> [#7618] Document process for reporting security vulnerabilities (4-3-stable)

server/api/src/rsCollRepl.cpp
Cherry-pick of https://github.com/irods/irods/pull/7624
=> [7540] Fix double-free in rsCollRepl (4-3-stable)

server/api/src/rsModDataObjMeta.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_rc_mod_data_obj_meta.cmake, unit_tests/src/test_rc_mod_data_obj_meta.cpp, unit_tests/unit_tests_list.json
Addresses #7626
Unit tests pass. Need to run the core tests.
=> [#7626] ModDataObjMeta: Fix ADMIN_KW usage with ALL_KW (main)

server/api/src/rsModDataObjMeta.cpp, unit_tests/CMakeLists.txt, unit_tests/cmake/test_config/irods_rc_mod_data_obj_meta.cmake, unit_tests/src/test_rc_mod_data_obj_meta.cpp, unit_tests/unit_tests_list.json
Addresses #7626 
Cherry-picked from https://github.com/irods/irods/pull/7632
=> [#7626] ModDataObjMeta: Fix ADMIN_KW usage with ALL_KW (4-3-stable)

doxygen/microservices.cpp
=> [#7570] Add GenQuery2 microservices to doxygen page (4-3-stable)

doxygen/microservices.cpp
Cherry-picked from https://github.com/irods/irods/pull/7642
=> [#858] Fix typo in Doxygen's Microservices page (4-3-stable)

scripts/irods/controller.py, scripts/irods/test/test_irodsctl.py
Addresses #7619 
Cherry-picked from https://github.com/irods/irods/pull/7629
=> [#7619] irodsctl stop: Fix orphan agent cleanup (4-3-stable)

scripts/irods/test/test_iquery.py
All tests in `test_iquery.py` passed at the bench.
They also passed in the testing environment.
=> GenQuery2 tests for various GenQuery1 / iquest issues (main)

doxygen/microservices.cpp, server/re/src/icatGeneralMS.cpp
Update documentation on `msiSetResource(...)` to note its deprecation.
=> [#7602] Deprecate msiSetResource (main)

scripts/irods/test/test_iquery.py
=> GenQuery2 tests for various GenQuery1 / iquest issues (4-3-stable)

doxygen/microservices.cpp, server/re/src/icatGeneralMS.cpp
=> [#7602] Deprecate msiSetResource (4-3-stable)

lib/api/src/rcDataObjCopy.cpp, lib/api/src/rcDataObjGet.cpp, lib/api/src/rcDataObjPut.cpp, lib/api/src/rcDataObjRepl.cpp, lib/core/include/irods/rodsKeyWdDef.h, lib/core/src/irods_parse_command_line_options.cpp, lib/core/src/rcPortalOpr.cpp, server/core/include/irods/miscServerFunct.hpp, server/core/src/miscServerFunct.cpp
Deprecated rbudpRemLocCopy and svrPortalPutGetRbudp
=> [6610] Deprecated RBUDP. (main)

doxygen/microservices.cpp, lib/api/include/irods/replica_truncate.h, scripts/core_tests_list.json, scripts/irods/test/test_all_rules.py, server/api/include/irods/rs_replica_truncate.hpp, server/re/include/irods/reAction.hpp, server/re/include/irods/reDataObjOpr.hpp, server/re/src/reDataObjOpr.cpp
Addresses https://github.com/irods/irods/issues/7577
Addresses https://github.com/irods/irods/issues/7650
Cherry-picked from https://github.com/irods/irods/pull/7663
=> Add replica_truncate microservice, fix Doxygen (4-3-stable)

doxygen/microservices.cpp, plugins/rule_engines/irods_rule_language/src/functions.cpp
This is the same as the pull request for 4-3-stable.
=> [7388][7630] Documenting the writeLine() function/microservice (main)

scripts/setup_irods.py
Addresses #7590 
Tested manually on Debian 12.
=> [#7590] irods_setup: Prevent local resource creation when user says no (main)

scripts/setup_irods.py
Addresses #7590 
Cherry-picked from https://github.com/irods/irods/pull/7665
=> [#7590] setup_irods: Prevent local resource creation when user says no (4-3-stable)

server/re/src/reDataObjOpr.cpp
In service of #6656 
Related to but not necessarily a companion PR for https://github.com/irods/irods_client_icommands/pull/465
=> [#6656] Add symlink restriction to msiTarFileExtract Doxygen (main)

server/re/src/reDataObjOpr.cpp
In service of #6656
Cherry-picked from https://github.com/irods/irods/pull/7670
Related to but not necessarily a companion PR for https://github.com/irods/irods_client_icommands/pull/466
=> [#6656] Add symlink restriction to msiTarFileExtract Doxygen (4-3-stable)

lib/core/src/irods_logger.cpp
=> [#7687] Change log level severity of fallback log message: warn -> trace (4-3-stable)

packaging/server_config.json.template
=> [#7570] Add genquery2 log category to server_config.json.template (4-3-stable)

scripts/irods/test/test_dynamic_peps.py, server/re/src/irods_re_serialization.cpp
Still drafty, because I'd like some assistance in figuring out a real test case because I'm a NREP noob. `writeLine` at a PEP seems to work, but a lot of the members seem to not have values at first blush. It does print the rule text, though, which is nice, I guess.
Code for the `MsParamArray` is mostly copied from https://github.com/irods/irods/pull/7691, and will probably be updated in lockstep with the other.
=> [7552] Serialize ExecMyRuleInp

scripts/irods/test/test_dynamic_peps.py, server/re/src/irods_re_serialization.cpp
Cherry-pick of https://github.com/irods/irods/pull/7693
=> [7552] Serialize ExecMyRuleInp (4-3-stable)

scripts/irods/test/test_dynamic_peps.py, server/re/src/irods_re_serialization.cpp
Cherry-pick of https://github.com/irods/irods/pull/7668
=> [7413] Add serialize function for StructFileExtAndRegInp (4-3-stable)

scripts/irods/test/test_dynamic_peps.py, server/re/src/irods_re_serialization.cpp
First attempt. Couple of things that need to be checked:
Is the type `MsParamArray**` or `MsParamArray*`? The two api calls in the api table that seem to use it both use this double-pointer. The other place where it seems like it could be used is `ExecMyRuleInp`'s member `inpParamArray`, which is a `MsParamArray*`
What is the minimum functionality that could trigger something for this? I tried doing a pep with `pep_api_exec_my_rule_post`, but couldn't seem to get any entries.
Still needs a test, once I know what to test for.
=> [7553] Serialize function for MsParamArray (main)

scripts/irods/test/test_dynamic_peps.py, server/re/src/irods_re_serialization.cpp
Cherry-pick of https://github.com/irods/irods/pull/7691
=> [7553] Added serialize function for MsParamArray** (4-3-stable)

Doxyfile
Forgot to get this in before the release.   Caused the docs hiccup I experienced during rollout.
Will make sure to get it into the release activites issues from here forward.
=> [7686] bump Doxyfile version (4-3-stable)

.github/workflows/build-irods-ubuntu.yml
=> [#7592] Add github action for Ubuntu 24.04 (main)

.github/workflows/build-irods-ubuntu.yml
=> [#7592] Add github action for Ubuntu 24.04 (4-3-stable)

plugins/database/src/general_query.cpp
This doesn't require testing. If it compiles, we can ship it.
=> [#7820] Change log level of ticket log message from LOG_NOTICE to LOG_DEBUG (4-3-stable)

plugins/database/src/general_query.cpp
=> [#7820] Change log level of ticket log message from LOG_NOTICE to LOG_DEBUG (main)

scripts/irods/test/test_irodsctl.py, scripts/irods/test/test_irsync.py, scripts/irods/test/test_itrim.py
Addresses #7718 
Addresses #7721 
Addresses #7725 
Confirmed that these tests now pass consistently when run with topology-on-consumer. Need to run full test suite for core tests,  topology-on-consumer, and topology-on-provider.
=> Various test fixes (main)

scripts/irods/test/test_irodsctl.py, scripts/irods/test/test_irsync.py, scripts/irods/test/test_itrim.py
Addresses https://github.com/irods/irods/issues/7718
Addresses https://github.com/irods/irods/issues/7721
Addresses https://github.com/irods/irods/issues/7725
Cherry-picked from https://github.com/irods/irods/pull/7839
=> Various test fixes (4-3-stable)

scripts/irods/test/test_all_rules.py
In service of #7760 
Companion PR: https://github.com/irods/irods/pull/7830
Companion PR: https://github.com/irods/irods_client_icommands/pull/490
=> [#7760] Stage irodsServerMonPerf for msiServerMonPerf test (4-3-stable)

scripts/irods/database_connect.py
=> [#7844] `database_connect.py:get_odbc_driver_paths`: Update for MySQL 8.x and deprioritize MariaDB (main)

scripts/irods/database_connect.py
=> [#7844] `database_connect.py:get_odbc_driver_paths`: Update for MySQL 8.x and deprioritize MariaDB (4-3-stable)

server/genquery2/dsl/lexer.l, server/genquery2/dsl/parser.y, server/genquery2/include/irods/private/genquery2_ast_types.hpp, server/genquery2/include/irods/private/genquery2_scanner.hpp, server/genquery2/src/genquery2_sql.cpp, unit_tests/src/test_rc_genquery2.cpp
Works. Just have to add tests and wrap a set of common lines in a function.
=> GenQuery2 Enhancements: Nested/Multi-argument functions in WHERE/ORDER-BY clause (4-3-stable)

server/genquery2/dsl/lexer.l, server/genquery2/dsl/parser.y, server/genquery2/include/irods/private/genquery2_ast_types.hpp, server/genquery2/include/irods/private/genquery2_scanner.hpp, server/genquery2/src/genquery2_sql.cpp, unit_tests/src/test_rc_genquery2.cpp
=> GenQuery2 Enhancements: Nested/Multi-argument functions in WHERE/ORDER-BY clause (main)

scripts/core_tests_list.json, scripts/irods/test/test_irepl.py, server/api/src/rsDataObjRepl.cpp
Addresses #7816 
Cherry-picked from https://github.com/irods/irods/pull/7827
=> [#7816] Check group permissions for replication (4-3-stable)

scripts/irods/test/test_resource_types.py
Addresses #5593 
Only ran the modified tests (many times in a row, each) in order to confirm that they are now passing consistently.
=> [#5593] Fix test_iget/irepl_with_purgec assumptions (main)

scripts/irods/test/test_resource_types.py
Addresses #5593 
Cherry-picked from https://github.com/irods/irods/pull/7854
=> [#5593] Fix test_iget/irepl_with_purgec assumptions (4-3-stable)

lib/core/include/irods/rcMisc.h, scripts/irods/test/test_irule.py
=> [#7704] Deprecate trimPrefix(...), trimSpaces(...), add irule test (4-3-stable)

scripts/irods/test/test_igroupadmin.py
Adds a test to clarify expected groupadmin behavior when misusing igroupadmin.
Based on the comments linked in the issue, it seems that one test may be enough, though if there are some other cases, suggestions are encouraged.
=> [#7707] Clarify groupadmin behavior with test (main)

scripts/irods/test/test_igroupadmin.py
=> [#7707] Clarify groupadmin behavior with test (4-3-stable)

.github/workflows/build-irods-centos.yml
=> [#7865] Migrate EL7 GH action away from mirrorlist (4-3-stable)

.github/workflows/build-irods-centos.yml
=> [#7865] Migrate EL7 GH action away from mirrorlist (main)

plugins/rule_engines/irods_rule_language/include/irods/private/re/configuration.hpp, plugins/rule_engines/irods_rule_language/include/irods/private/re/rules.hpp, plugins/rule_engines/irods_rule_language/src/configuration.cpp, plugins/rule_engines/irods_rule_language/src/rules.cpp
=> [5210] Rewrite make_copy so it stores rule files in memory (4-3-stable)

lib/administration/resource/include/irods/resource_administration.hpp
=> [#7877] Adjust error message in resource administration library (4-3-stable)

.github/workflows/build-irods-centos.yml
=> [#7885] Use old node version for EL7 GH action (main)

.github/workflows/build-irods-centos.yml
=> [#7885] Use old node version for EL7 GH action (4-3-stable)

plugins/microservices/src/atomic_apply_acl_operations.cpp, plugins/microservices/src/atomic_apply_metadata_operations.cpp
=> [#7870] Improve documentation for atomic acls/metadata microservices (4-3-stable)

plugins/microservices/src/atomic_apply_acl_operations.cpp, plugins/microservices/src/atomic_apply_metadata_operations.cpp
Example code works as intended.
=> [#7870] Improve documentation for atomic acls/metadata microservices (main)

server/re/src/reDataObjOpr.cpp
identical - cherry pick from https://github.com/irods/irods/pull/7897
=> [7724] add filesize clarification for msiDataObjChksum (main)

plugins/database/src/low_level_odbc.cpp
This was used to figure out where the post-install test was failing when using MariaDB ODBC drivers to communicate with MariaDB 11.4.
=> [#7907] Add trace level logging to low-level ODBC code (4-3-stable) 

plugins/database/src/low_level_odbc.cpp
=> [#7907] Add trace level logging to low-level ODBC code (main)

plugins/api/src/atomic_apply_acl_operations.cpp, unit_tests/src/test_atomic_apply_acl_operations.cpp
First shot at this. Any comments welcome.
=> [7408] Atomic ACLs consider zone of user (main)

plugins/api/src/atomic_apply_acl_operations.cpp, unit_tests/src/test_atomic_apply_acl_operations.cpp
=> [7408] Atomic ACLs consider zone of user (4-3-stable)

scripts/irods/test/test_prep_genquery_iterator.py
Companion PR for irods/irods_rule_engine_plugin_python#206.
Leaving as draft until the PREP PR is done.
Current tests pass. Feel free to review them.
=> [#7909,irods/irods_rule_engine_plugin_python#182] Add genquery2 tests for genquery python module (4-3-stable)

scripts/irods/test/test_prep_genquery_iterator.py
=> [#7909,irods/irods_rule_engine_plugin_python#182] Add genquery2 tests for genquery python module (main)

scripts/irods/test/test_prep_genquery_iterator.py
Depends on irods/irods_rule_engine_plugin_python#206.
This PR covers the following GenQuery2 features for the PREP genquery.py module.
- order-by clause
- `close()` member function
The new tests pass.
=> [#7909,irods/irods_rule_engine_plugin_python#182] Add genquery2 order-by test for genquery python module (4-3-stable)

scripts/irods/test/test_prep_genquery_iterator.py
=> [#7909,irods/irods_rule_engine_plugin_python#182] Add genquery2 order-by test for genquery python module (main)

server/api/src/rs_replica_truncate.cpp, unit_tests/src/test_replica_truncate.cpp
Addresses #7918
Unit tests are passing. Also confirmed that the replica_truncate unit tests fail as expected before the change. That is, successful truncates return `nullptr` for the output string before the changes, and after the changes they correctly return a message and replica information.
While the writing tests, I noticed one case which produced results which differed from my expectations and I went ahead and changed this as well in the API. I feel like not everybody may agree with the decision, so I wanted to highlight the test case section named `resource_name_with_no_replica` for review/discussion.
Running core tests now.
=> [#7918] replica_truncate: Fix JSON output for some cases (4-3-stable)

server/api/src/rs_replica_truncate.cpp, unit_tests/src/test_replica_truncate.cpp
Addresses #7918 
Cherry-picked from https://github.com/irods/irods/pull/7921
=> [#7918] replica_truncate: Fix JSON output for some cases (main)

plugins/database/src/mid_level_routines.cpp, scripts/irods/test/test_iticket.py
This change makes the ticket failure only trigger when the uses count is updated. Ran just the test for `iticket`, but not sure if this breaks anything else (haven't run full test suite yet).
=> [7967] Change if statement so it only triggers on first pass (main)

plugins/database/src/mid_level_routines.cpp, scripts/irods/test/test_iticket.py
=> [7967] Change if statement so ticket use count is only updated on first pass (4-3-stable)

schemas/configuration/v4/server_config.json.in
Not sure if anything else is required for this.
=> [8017] Modify schema file to enforce required attributes (main)

schemas/configuration/v4/server_config.json.in
Cherry-pick of https://github.com/irods/irods/pull/8035
=> [8017] Modify schema file to enforce required attributes (4-3-stable)

unit_tests/src/test_rc_switch_user.cpp
=> Fixes for rc_switch_user unit tests (4-3-stable)

server/main_server/src/rodsServer.cpp
Will run unit/core tests soon.
=> [#8050] Fix error handling logic for heartbeat operation (4-3-stable)

scripts/irods/test/test_icommands_file_operations.py
sibling icommands PR at https://github.com/irods/irods_client_icommands/pull/509
=> [8084] remove igetwild test (main)

lib/api/include/irods/apiNumberData.h, lib/api/include/irods/apiTable.hpp, lib/api/include/irods/dataObjLock.h, lib/api/src/rcDataObjLock.cpp, server/api/include/irods/rsDataObjLock.hpp
I think I hit all the relevant locations; feel free to comment if I missed anything.
=> [7979] Deprecate dataObjLock and dataObjUnlock (4-3-stable)

lib/core/include/irods/irods_query.hpp, lib/core/include/irods/rcMisc.h, server/re/src/genQueryMS.cpp
=> [#8088] Deprecate `fillGenQueryInpFromStrCond()` (4-3-stable)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iadmin.py
=> [7778] User removal now also removes ACLs (main)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iadmin.py
Cherry-pick of https://github.com/irods/irods/pull/8105
=> [7778] User removal now also removes ACLs (4-3-stable)

doxygen/microservices.cpp, server/re/include/irods/reAction.hpp, server/re/include/irods/reIn2p3SysRule.hpp, server/re/src/reIn2p3SysRule.cpp
Think I got everything. Let me know if I didn't!
=> [7977] Deprecate server monitoring microservices (4-3-stable)

scripts/irods/test/test_imeta_interactive.py
Test should no longer fail after this change.
=> [7961] Update test for imeta deprecation message (4-3-stable)

lib/core/src/obf.cpp, lib/core/src/rcConnect.cpp, lib/core/src/rcMisc.cpp, server/api/src/rsExecCmd.cpp
Think I got them all. Let me know if I missed any.
=> [6234] Remove some nonexistent includes (4-3-stable)

lib/core/src/obf.cpp, lib/core/src/rcConnect.cpp, lib/core/src/rcMisc.cpp, server/api/src/rsExecCmd.cpp
(Mostly) a cherry-pick of https://github.com/irods/irods/pull/8128 with the exception of `server/api/src/rsExecCmd.cpp` which I had to redo by hand because of a merge conflict.
=> [6234] Remove some nonexistent includes (main)

lib/api/include/irods/replica_open.h
In service of #2600
Cherry-pick of #8139
=> [#2600] Doxygen: Add replica_open.h (main)

server/core/src/json_deserialization.cpp
Built and tested. Only `test_imeta_interactive` fails, but the failure is unlikely unrelated to this PR.
Suggestions for further tests would be appreciated!
=> [#8110] Correct narrowing of floating point values (4-3-stable)

lib/core/src/rcConnect.cpp, unit_tests/src/test_rcConnect.cpp
Cherry-pick of https://github.com/irods/irods/pull/8137
=> [8120] Avoid segfault in rcDisconnect (4-3-stable)

server/main_server/src/main.cpp
=> [#8151] Remove orphan declaration print_configuration_template (main)

server/core/src/json_deserialization.cpp
=> [#8110] Cherry-pick: Correct narrowing of floating point values (main)

lib/core/include/irods/rodsErrorTable.h, lib/core/src/rcMisc.cpp, scripts/irods/test/test_iquest.py
=> [#8080] Return error on invalid GenQuery1 aggregate function (4-3-stable)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iadmin.py, server/api/src/rsGeneralAdmin.cpp, server/core/include/irods/administration_utilities.hpp, server/core/src/administration_utilities.cpp
=> [#7722] Validate and reject invalid zone names (4-3-stable)

plugins/database/src/db_plugin.cpp, scripts/irods/test/test_iadmin.py, server/api/src/rsGeneralAdmin.cpp, server/core/include/irods/administration_utilities.hpp, server/core/src/administration_utilities.cpp
=> [#7722] Validate and reject invalid zone names (main)

plugins/rule_engines/irods_rule_language/include/irods/private/re/configuration.hpp, plugins/rule_engines/irods_rule_language/src/configuration.cpp
=> [#8111] Cherry-pick: Remove ctor from Cache in NREP to allow for memset (main)

server/api/src/rsDataObjUnlink.cpp
=> [#7953] Do not log message unless oprType is changed to UNREG_OPR (main)

lib/api/include/irods/apiTable.hpp, lib/api/include/irods/getMiscSvrInfo.h, lib/core/include/irods/rcMisc.h, lib/core/src/rcMisc.cpp, scripts/irods/test/test_imiscsvrinfo.py, server/api/src/rsGetMiscSvrInfo.cpp
Leaving as draft for now. Still needs:
- Freeing of the bytesbuf buffer
- Determine what we actually want in the output
- Exception handling
- A test
For the icommands: https://github.com/irods/irods_client_icommands/pull/539
=> [7986] Add SSL info to imiscsvrinfo (main)

lib/api/include/irods/apiTable.hpp, lib/api/include/irods/getMiscSvrInfo.h, lib/core/include/irods/rcMisc.h, lib/core/src/rcMisc.cpp, scripts/irods/test/test_imiscsvrinfo.py, server/api/src/rsGetMiscSvrInfo.cpp
Cherry-pick of https://github.com/irods/irods/pull/8236
=> [7986] Add JSON-formatted SSL/TLS cert info to MiscSvrInfo API (4-3-stable)

lib/core/src/trimUtil.cpp, scripts/irods/test/resource_suite.py, scripts/irods/test/test_all_rules.py, scripts/irods/test/test_chunkydevtest.py, scripts/irods/test/test_iadmin.py, scripts/irods/test/test_ibun.py, scripts/irods/test/test_iput_options.py, scripts/irods/test/test_ireg.py, scripts/irods/test/test_itrim.py, scripts/irods/test/test_iunreg.py, scripts/irods/test/test_resource_types.py, scripts/irods/test/timing_tests.py, server/api/src/rsDataObjTrim.cpp
In service of #4685
In service of #4861 
Companion PR: https://github.com/irods/irods_resource_plugin_s3/pull/2230
Unit tests passed. Core tests running now.
=> [#4861] DataObjTrim: Lift deprecation of COPIES_KW (main)

packaging/postinstall.sh, packaging/server_upgrade_instructions.txt, server/CMakeLists.txt, server/main_server/src/main.cpp
=> [#8074] Instruct admin to run upgrade_irods.py (main)

scripts/irods/test/test_iquery.py, server/genquery2/src/genquery2_sql.cpp
=> [#8259] Make GenQuery2 honor group permissions (4-3-stable)

server/main_server/src/main.cpp
=> [#8381] Do not connect to server unless there are access time updates in the queue (main)

schemas/configuration/v5/server_config.json.in
Will run the unit tests to confirm things are still good.
=> Add missing server config properties to schema / Limit acceptable values for port numbers in schema (main)

lib/core/src/msParam.cpp, scripts/irods/test/test_python_rule_engine_plugin.py
=> [#8265] Restore support for KeyValPair in Python REP (main)

scripts/irods/test/test_iput.py, scripts/irods/test/test_pam_password_authentication.py, scripts/irods/test/test_prep_genquery_iterator.py, scripts/irods/test/test_python_rule_engine_plugin.py
Companion PR at https://github.com/irods/irods_rule_engine_plugin_python/pull/238.
All tests pass for the PREP with this PR.
Will merge soon.
=> iRODS 5: Test fixes for Python REP (main)

plugins/database/src/low_level_odbc.cpp, server/core/include/irods/catalog.hpp, server/core/src/catalog.cpp
=> Remove `irodsOdbcDSN` environment variable / Do not read server config when creating database connections (main)

scripts/irods/test/test_irm.py, server/api/src/rsDataObjUnlink.cpp
In service of #4367
Addresses #8441
Unit and core tests passed.
=> [#8441] DataObjUnlink: Unregister before unlinking (main)

plugins/database/src/db_plugin.cpp
=> [8392] Change query in db_set_avu_metadata_op for efficiency (4-3-stable)

plugins/database/src/low_level_odbc.cpp
=> [#8318] Change log level on bindvar message (main)

lib/core/include/irods/irods_configuration_keywords.hpp, lib/core/include/irods/irods_logger.hpp, lib/core/src/irods_configuration_keywords.cpp, packaging/server_config.json.template.in, plugins/database/src/general_query.cpp, schemas/configuration/v5/server_config.json.in, server/icat/include/irods/icatHighLevelRoutines.hpp, server/icat/src/icatHighLevelRoutines.cpp, server/main_server/src/agent_main.cpp
Leaving in draft because of the single TODO, but rest of it is open for review too. 
Compiles.
=> [8319] GenQuery1 log category and replacement (main)

lib/api/include/irods/dataObjCopy.h, lib/api/include/irods/dataObjCreate.h, lib/api/include/irods/dataObjCreateAndStat.h, lib/api/include/irods/dataObjOpen.h, lib/api/include/irods/dataObjOpenAndStat.h, lib/api/include/irods/dataObjPut.h, lib/api/src/rcDataObjCopy.cpp, lib/api/src/rcDataObjCreate.cpp, lib/api/src/rcDataObjCreateAndStat.cpp, lib/api/src/rcDataObjPut.cpp, lib/api/src/rcDataObjRepl.cpp, lib/core/src/cpUtil.cpp, lib/core/src/irods_parse_command_line_options.cpp, lib/core/src/miscUtil.cpp, lib/core/src/putUtil.cpp, plugins/api/src/data_object_finalize.cpp, plugins/api/src/register_physical_path.cpp, plugins/auth/src/native.cpp, scripts/irods/test/resource_suite.py, server/api/src/rsDataObjOpen.cpp, server/core/include/irods/objDesc.hpp, server/core/src/objDesc.cpp, server/delay_server/src/irodsDelayServer.cpp, server/re/src/reDataObjOpr.cpp
In service of https://github.com/irods/irods/issues/4932
In service of https://github.com/irods/irods/issues/8334
Cherry-picked from https://github.com/irods/irods/pull/8467
All tests passed
=> Fix some memleaks reported by ASAN (4-3-stable)

lib/core/include/irods/irods_logger.hpp, lib/core/include/irods/rodsLog.h, lib/core/src/rodsLog.cpp, scripts/irods/test/test_rule_engine_plugin_passthrough.py, server/main_server/src/agent_main.cpp, server/main_server/src/main.cpp
Required by irods/irods_capability_indexing#172.
=> [#7229] Increase rodsLog verbosity (main)

plugins/database/src/general_query.cpp
As titled. It compiles, so that's a good sign.
=> [8319] Replace genquery1 printf logging with new log category (main)

.github/workflows/build-irods-enterprise-linux-9.yml
=> [#8533] CI: Use new location of Rocky Linux images (main)

server/api/src/rsDataObjClose.cpp
All tests passed.  This goes along with irods/irods_resource_plugin_s3#2259 to fix issue irods/irods_resource_plugin_s3#2146. 
This is to fix S3 issue 2146. The issue occurs on large file transfers when the resource is in attached and decoupled modes and a redirect is required.  The following is the rough description assuming the client is connected to server A and the resource is attached to server B.
1. s3_resolve_resc_hier_operation is run on server A.
2. The db_reg_data_obj_op operation is called on the catalog provider to create the data object entry. After this there is a record in the database for the replica.
3. The request is redirected to server B.
4. On server B, in s3_file_create_operation the physical path is paved over. This allows the plugin to write to the correct S3 key. …
=> [irods/irods_resource_plugin_s3#2146] Calling fileNotify on close (main)

lib/core/include/irods/miscUtil.h, lib/core/src/miscUtil.cpp, lib/core/src/rsyncUtil.cpp, scripts/irods/test/test_irsync.py
My first stab at option 3 as mentioned in the original issue.
Seems to work when run in a docker container and with the original test case.
Taking suggestions on naming, style, or anything, as always.
=> [7774] irsync -l no longer creates target collection (4-3-stable)

scripts/irods/test/test_iquery.py, server/genquery2/dsl/parser.y, server/genquery2/include/irods/private/genquery2_ast_types.hpp, server/genquery2/src/genquery2_sql.cpp
=> [8093] group by functions (4-3-stable)

scripts/irods/test/test_iquery.py, server/genquery2/dsl/parser.y, server/genquery2/include/irods/private/genquery2_ast_types.hpp, server/genquery2/src/genquery2_sql.cpp
=> [8093] group by functions  (5-0-stable)

lib/core/include/irods/miscUtil.h, lib/core/src/miscUtil.cpp, lib/core/src/rsyncUtil.cpp, scripts/irods/test/test_irsync.py, server/api/src/rsDataObjPut.cpp, server/api/src/rsDataObjRsync.cpp
Cherry-pick of https://github.com/irods/irods/pull/8573, https://github.com/irods/irods/pull/8592, and https://github.com/irods/irods/pull/8608
=> Various irsync bugfixes (5-0-stable)

server/irods_grid/src/irods-grid.cpp
Companion PR at irods/irods_docs#386.
Will confirm the help text is printed correctly soon.
=> [#8479] Deprecate irods-grid command (4-3-stable)

scripts/setup_irods.py
=> [#8577] Do not prompt for server host on unattended install (5-0-stable)

lib/core/src/rsyncUtil.cpp, scripts/irods/test/test_irsync.py, server/api/src/rsDataObjRsync.cpp
Leaving in draft for now, since we agreed to stare at this first.
Solves the cases in the issues listed, but incurs another genquery. Taking suggestions, criticisms, etc.
Whatever we eventually end up agreeing on, it'll need a test as well.
=> [8590] Overwrite on no good replicas+rsync only trusts good replica checksum (4-3-stable)

lib/core/src/rsyncUtil.cpp, scripts/irods/test/test_irsync.py, server/api/src/rsDataObjRsync.cpp
Cherry-pick of https://github.com/irods/irods/pull/8631
=> [8590] Overwrite on no good replicas+rsync only trusts good replica checksum (main)

scripts/irods/upgrade_configuration.py, scripts/upgrade_irods.py
=> [#8676] Do not stacktrace on detection of server downgrade (main)
